//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@interface NSMutableDictionary (SWTokenEngine)
+ (void)testSWTokenEngine;
- (id)addDensity;
- (id)addVendor;
- (id)addIP;
- (id)addModel;
- (id)addUa;
- (id)addOriginalUa;
- (id)addOsv;
- (id)addOpenUDID;
- (id)addMachineModel;
- (id)addIdfv;
- (id)addCarrier;
- (id)addNetworkInfo;
- (id)addTs;
- (id)addResolution;
- (id)addWeiboAid;
- (id)addTimezone;
- (id)addLang;
- (id)addDevice_id;
- (id)addApiKey;
- (id)addDevicePlatm;
- (id)addDeviceVersion;
- (id)addOS;
- (id)addPVer;
- (id)addDevice;
- (id)addToken;
- (id)addPid;
- (id)addIdfa;
- (id)addUid;
- (id)addSv;
- (id)addPd1;
- (id)addPv;
- (id)addPt1;
- (id)addPt;
@end

