//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BBAConfigSource.h"

@class NSArray, NSMutableArray;

@interface BBAConfig : BBAConfigSource
{
    NSMutableArray *_readableConfigSources;
    NSMutableArray *_writableConfigSources;
}

+ (id)novelConfig;
@property(readonly, nonatomic) NSArray *writableConfigSources; // @synthesize writableConfigSources=_writableConfigSources;
@property(readonly, nonatomic) NSArray *readableConfigSources; // @synthesize readableConfigSources=_readableConfigSources;
- (void).cxx_destruct;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (void)addWritableConfigSource:(id)arg1;
- (void)addReadableConfigSource:(id)arg1;
- (id)init;
@property(nonatomic) int novelConfigThemeType;
- (id)novelConfigThemeSource;

@end

