//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIColor, UIImageView;

@interface CatalogCellView : UIView
{
    _Bool _hasRadio;
    int _imgScriptType;
    int _flag;
    int _extendFlag;
    NSString *_title;
    NSString *_detail;
    unsigned long long _detailLinesCnt;
    unsigned long long _listenCnt;
    unsigned long long _favorCnt;
    UIColor *_mainTextColor;
    UIColor *_detailTextColor;
    UIImageView *_iconImageView;
}

@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIColor *detailTextColor; // @synthesize detailTextColor=_detailTextColor;
@property(retain, nonatomic) UIColor *mainTextColor; // @synthesize mainTextColor=_mainTextColor;
@property(nonatomic) unsigned long long favorCnt; // @synthesize favorCnt=_favorCnt;
@property(nonatomic) unsigned long long listenCnt; // @synthesize listenCnt=_listenCnt;
@property(nonatomic) int extendFlag; // @synthesize extendFlag=_extendFlag;
@property(nonatomic) _Bool hasRadio; // @synthesize hasRadio=_hasRadio;
@property(nonatomic) int flag; // @synthesize flag=_flag;
@property(nonatomic) int imgScriptType; // @synthesize imgScriptType=_imgScriptType;
@property(nonatomic) unsigned long long detailLinesCnt; // @synthesize detailLinesCnt=_detailLinesCnt;
@property(copy, nonatomic) NSString *detail; // @synthesize detail=_detail;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setIcon:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

