//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class PlayParameInfo;

@interface CSHistoryPlayer : NSObject
{
    PlayParameInfo *_playParameInfo;
}

- (void)alertHint;
- (_Bool)checkOfflinePlayerRecord:(id)arg1;
- (void)showPlayVideoHint:(id)arg1;
- (void)playWithVideoRecordItem:(id)arg1;
- (void)networkAndVersionCheckPlayable:(_Bool)arg1;
- (void)playWithRecordItem:(id)arg1;
- (void)gotoPlayerPage:(id)arg1;

@end

