//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface GXUploadLogRequest : NSObject
{
    NSNumber *createtime_;
    NSString *cid_;
}

- (_Bool)sendRquestToRemote:(id)arg1;
- (id)buildPostBody:(id)arg1 blockCnt:(int)arg2 blockSeq:(int)arg3;
- (_Bool)requestUploadLog:(id)arg1 andBlockCnt:(int)arg2 andBlockSeq:(int)arg3;
- (void)dealloc;
- (id)initWithClientId:(id)arg1 andAppId:(id)arg2 andCreateTime:(double)arg3;

@end

