//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SessionMessageBaseContent.h"

@class NSString;

@interface SessionMessageTipContent : SessionMessageBaseContent
{
    NSString *_actionString;
    NSString *_sceneString;
    NSString *_sessionID;
    long long _type;
}

@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
@property(retain, nonatomic) NSString *sceneString; // @synthesize sceneString=_sceneString;
@property(retain, nonatomic) NSString *actionString; // @synthesize actionString=_actionString;
- (void).cxx_destruct;
- (void)buildCrowdfundingRedPacketGetTip;
- (void)buildCrowdfundingRedPacketSuccessTip;
- (void)buildRedPacketTip;
- (void)buildRevokeTipWithMsglog:(const struct MsgLog *)arg1;
- (void)genPropertyFromMsgLog:(const struct MsgLog *)arg1;

@end

