//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KSSecondLevelViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class KSCourceCalendarConfig, KSCourceCalendarModel, NSMutableArray, NSString, UITableView;

@interface KSCourceCalendarViewController : KSSecondLevelViewController <UITableViewDelegate, UITableViewDataSource>
{
    long long _courseid;
    UITableView *_tableView;
    KSCourceCalendarConfig *_requestConfig;
    KSCourceCalendarModel *_model;
    NSMutableArray *_calendarArray;
}

@property(retain, nonatomic) NSMutableArray *calendarArray; // @synthesize calendarArray=_calendarArray;
@property(retain, nonatomic) KSCourceCalendarModel *model; // @synthesize model=_model;
@property(retain, nonatomic) KSCourceCalendarConfig *requestConfig; // @synthesize requestConfig=_requestConfig;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) long long courseid; // @synthesize courseid=_courseid;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)register_tableView_nib;
- (void)configTavleView;
- (void)configViews;
- (void)handleCalendarData;
- (void)handleData;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

