//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface KSHomepageOperationFetchDataModel : NSObject
{
}

- (_Bool)hasShown:(long long)arg1;
- (void)saveShownInfo:(long long)arg1;
- (void)fetchOperationImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)getSignWithKey:(id)arg1 client:(int)arg2 timestamp:(id)arg3;
- (id)operationDataParametersWithLocation:(long long)arg1;
- (id)operationDataParameters;
- (id)operationDataParametersWithOldVersion:(id)arg1;
- (void)fetchHomepageNewGuideDataSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)fetchOxfordDetailData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchOperationData:(id)arg1 location:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchOperationDataAndImage:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

