//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CBaseCell.h"

#import "KBTableViewCellProtocol-Protocol.h"
#import "QNCircularScrollViewDataSource-Protocol.h"
#import "QNCircularScrollViewDelegate-Protocol.h"

@class CFlagView, CPointArrayView, NSDictionary, NSString, QNAdItem, QNAttributedLabel, QNCircularScrollView, UIView;

@interface QNAdFirstCellContainer : CBaseCell <QNCircularScrollViewDelegate, QNCircularScrollViewDataSource, KBTableViewCellProtocol>
{
    QNCircularScrollView *_containerView;
    CDUnknownBlockType _selectBlock;
    CDUnknownBlockType _visiableBlock;
    NSDictionary *_cellInfo;
    QNAdItem *_adItem;
    CDUnknownBlockType _resetPageIndexBlock;
    CDUnknownBlockType _pageIndexBlock;
    UIView *_titleBackground;
    CPointArrayView *_pageControl;
    CFlagView *_flagView;
    QNAttributedLabel *_titleLbl;
    NSString *_titleStr;
}

+ (double)heightForData:(id)arg1 width:(double)arg2 context:(id)arg3;
+ (id)reuseIdentifierForData:(id)arg1;
+ (double)getCellHeight:(id)arg1 row:(long long)arg2 isNoPicMode:(_Bool)arg3;
+ (id)do_reuseIdentifierForItem:(id)arg1;
@property(copy, nonatomic) NSString *titleStr; // @synthesize titleStr=_titleStr;
@property(retain, nonatomic) QNAttributedLabel *titleLbl; // @synthesize titleLbl=_titleLbl;
@property(retain, nonatomic) CFlagView *flagView; // @synthesize flagView=_flagView;
@property(retain, nonatomic) CPointArrayView *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) UIView *titleBackground; // @synthesize titleBackground=_titleBackground;
@property(copy, nonatomic) CDUnknownBlockType pageIndexBlock; // @synthesize pageIndexBlock=_pageIndexBlock;
@property(copy, nonatomic) CDUnknownBlockType resetPageIndexBlock; // @synthesize resetPageIndexBlock=_resetPageIndexBlock;
@property(retain, nonatomic) QNAdItem *adItem; // @synthesize adItem=_adItem;
@property(retain, nonatomic) NSDictionary *cellInfo; // @synthesize cellInfo=_cellInfo;
@property(copy, nonatomic) CDUnknownBlockType visiableBlock; // @synthesize visiableBlock=_visiableBlock;
@property(copy, nonatomic) CDUnknownBlockType selectBlock; // @synthesize selectBlock=_selectBlock;
@property(retain, nonatomic) QNCircularScrollView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)layoutWithData:(id)arg1 context:(id)arg2;
- (id)_titleAttributedString:(id)arg1 firstLineHeadIndent:(double)arg2;
- (void)p_checkIfAdVisiable:(id)arg1;
- (id)currentAdView;
- (id)allAdViews;
- (id)circularScrollView:(id)arg1 contentForPage:(unsigned long long)arg2;
- (unsigned long long)numberOfPagesInCircularScrollView:(id)arg1;
- (void)circularScrollViewDidScroll:(id)arg1 at:(struct CGPoint)arg2;
- (void)circularScrollView:(id)arg1 currentPageChanged:(long long)arg2;
- (void)p_SetCustomPageControl:(id)arg1;
- (void)p_LayoutTitleAndFlagView:(id)arg1;
- (id)p_ViewItemForIndex:(unsigned long long)arg1;
- (void)setStorePageIndexBlock:(CDUnknownBlockType)arg1;
- (void)setResetIndexblock:(CDUnknownBlockType)arg1;
- (void)setSelectedblock:(CDUnknownBlockType)arg1;
- (void)layoutCell:(id)arg1 row:(long long)arg2 isLastRow:(_Bool)arg3 isNoPicMode:(_Bool)arg4 context:(id)arg5;
- (double)getCellHeight:(id)arg1 isNoPicMode:(_Bool)arg2;
- (void)p_configureAdViewBackgroundColor:(id)arg1;
- (void)do_resetNewsBackgroundColorForAnimation;
- (void)do_resetNewsBackgroundColor;
- (void)do_configNewsBackgroundColor;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

