//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MQQUserDefaults, NSArray, NSLock, NSMutableArray;

@interface MQQCBPhoneNumberStore : NSObject
{
    NSLock *_lock;
    MQQUserDefaults *_userDefaults;
    NSArray *_synchronizedPhoneNumbers;
    NSMutableArray *_temporaryPhoneNumbers;
}

@property(retain, nonatomic) NSMutableArray *temporaryPhoneNumbers; // @synthesize temporaryPhoneNumbers=_temporaryPhoneNumbers;
@property(copy, nonatomic) NSArray *synchronizedPhoneNumbers; // @synthesize synchronizedPhoneNumbers=_synchronizedPhoneNumbers;
- (id)_readSynchronizedPhoneNumbers;
- (_Bool)synchronize;
- (void)resetAllPhoneNumbersThatIncompleted;
- (void)changeAllPhoneNumbersToCompleted;
- (void)deleteAllPhoneNumbers;
- (void)deletePhoneNumberWithNumber:(id)arg1;
- (void)addPhoneNumber:(id)arg1;
- (id)temporaryPhoneNumberList;
- (id)synchronizedPhoneNumberList;
- (void)dealloc;
- (id)initWithFilePath:(id)arg1;

@end

