//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MQQQTAdvertiseFetcherDelegate-Protocol.h"
#import "MQQQTResourceDownloaderDelegate-Protocol.h"

@class MQQQTAdvertiseFetcher, MQQQTResourceDownloader, MQQQTResourceManager, NSString;

@interface MQQMobileCenterQTManager : NSObject <MQQQTAdvertiseFetcherDelegate, MQQQTResourceDownloaderDelegate>
{
    MQQQTAdvertiseFetcher *_advertiseFetcher;
    double _lastUpdateTimestamp;
    MQQQTResourceManager *_resourceManager;
    MQQQTResourceDownloader *_resourceDownloader;
    unsigned long long _backgroundTaskIdentifier;
}

+ (id)sharedManager;
@property(nonatomic) unsigned long long backgroundTaskIdentifier; // @synthesize backgroundTaskIdentifier=_backgroundTaskIdentifier;
@property(readonly, nonatomic) MQQQTResourceDownloader *resourceDownloader; // @synthesize resourceDownloader=_resourceDownloader;
@property(readonly, nonatomic) MQQQTResourceManager *resourceManager; // @synthesize resourceManager=_resourceManager;
@property(nonatomic) double lastUpdateTimestamp; // @synthesize lastUpdateTimestamp=_lastUpdateTimestamp;
@property(retain, nonatomic) MQQQTAdvertiseFetcher *advertiseFetcher; // @synthesize advertiseFetcher=_advertiseFetcher;
- (void)endBackgroundTask;
- (void)beginBackgroundTaskIfNeeded;
- (void)resourceDownloaderDidFinish:(id)arg1;
- (void)downloadResourcesForFetchResultIfNeeded:(id)arg1 startedDownloading:(_Bool *)arg2;
- (void)advertiseFetcher:(id)arg1 didFinishWithResult:(id)arg2 willDownload:(_Bool)arg3;
- (void)startAdvertiseRequest;
- (void)checkForUpdates;
- (void)checkForUpdatesIfNeeded;
- (id)fetchAdvertisesForLeftBar;
- (id)fetchAdvertisesForExtendedUtility;
- (id)fetchAdvertisesForUtility;
- (id)fetchAdvertisesForScrollableBanner;
- (id)fetchAdvertisesForTopBanner;
- (id)fetchAdvertisesForOptions:(id)arg1;
- (_Bool)isAdvertiseAvailable:(id)arg1;
- (id)leftBarPositionOptions;
- (id)extendedUtilityPositionOptions;
- (id)utilityPositionOptions;
- (id)scrollablePositionOptions;
- (id)topBannerPositionOptions;
- (id)requestOptions;
- (id)fetchOptionsWithPositionOptions:(id)arg1;
- (id)imagePathForAdvertise:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

