//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MQQMFBaseCell.h"

#import "MQQMFScrollableViewControllerDelegate-Protocol.h"

@class MQQMFScrollableViewController, MQQMFScrollableViewItem, NSString, UIPageControl;

@interface MQQMFScrollableBannerCell : MQQMFBaseCell <MQQMFScrollableViewControllerDelegate>
{
    MQQMFScrollableViewController *_scrollableViewController;
    UIPageControl *_pageControl;
}

@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) MQQMFScrollableViewController *scrollableViewController; // @synthesize scrollableViewController=_scrollableViewController;
- (void)_autoScrollToItem:(unsigned long long)arg1 inSection:(unsigned long long)arg2;
- (void)_autoScrollFromTheBeginningIfNeededForIndex:(unsigned long long)arg1;
- (void)scrollableViewController:(id)arg1 scrollViewDidEndScrollingAnimation:(id)arg2;
- (void)scrollableViewController:(id)arg1 didEndDecelerating:(id)arg2;
- (void)scrollableViewController:(id)arg1 didEndDragging:(id)arg2 willDecelerate:(_Bool)arg3;
- (void)scrollableViewController:(id)arg1 willBeginDragging:(id)arg2;
- (void)layoutSubviews;
- (unsigned long long)itemCount;
- (void)updateValueForKeyPath:(id)arg1;
- (id)observingKeyPathsForViewItem;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) MQQMFScrollableViewItem *viewItem; // @dynamic viewItem;

@end

