//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IfengStyle.h"

@class NSString, UIColor;

@interface IfengTopicCellStyle : IfengStyle
{
    float thumbilAlpha;
    float commentAlpha;
    UIColor *titleColor;
    UIColor *dateColor;
    UIColor *introbutionColor;
    UIColor *commentCountColor;
    UIColor *commentViewBgColor;
    NSString *thunbilDefaultImage;
    NSString *shadowImage;
    NSString *commentImage;
    UIColor *bgColor;
}

@property(retain, nonatomic) UIColor *bgColor; // @synthesize bgColor;
@property(retain, nonatomic) NSString *commentImage; // @synthesize commentImage;
@property(retain, nonatomic) NSString *shadowImage; // @synthesize shadowImage;
@property(retain, nonatomic) NSString *thunbilDefaultImage; // @synthesize thunbilDefaultImage;
@property(nonatomic) float commentAlpha; // @synthesize commentAlpha;
@property(nonatomic) float thumbilAlpha; // @synthesize thumbilAlpha;
@property(retain, nonatomic) UIColor *commentViewBgColor; // @synthesize commentViewBgColor;
@property(retain, nonatomic) UIColor *commentCountColor; // @synthesize commentCountColor;
@property(retain, nonatomic) UIColor *introbutionColor; // @synthesize introbutionColor;
@property(retain, nonatomic) UIColor *dateColor; // @synthesize dateColor;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor;
- (void).cxx_destruct;
- (void)night;
- (void)day;
- (id)init;

@end

