//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSData, NSURL, UIImage;

@interface ALHImageUploaderQueueRequestItem : NSObject
{
    NSURL *_imageURL;
    NSData *_imageData;
    UIImage *_image;
    CDUnknownBlockType _progressBlk;
    CDUnknownBlockType _completionBlk;
}

@property(copy, nonatomic) CDUnknownBlockType completionBlk; // @synthesize completionBlk=_completionBlk;
@property(copy, nonatomic) CDUnknownBlockType progressBlk; // @synthesize progressBlk=_progressBlk;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
@property(copy, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
- (void).cxx_destruct;
- (void)dealloc;

@end

