//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DownloadModelObserver-Protocol.h"
#import "NBNetworkResponseDelegate-Protocol.h"

@class NSMutableArray, NSString, ObserverContainer, UCReachability;
@protocol DownloadModel;

@interface NBDownloadManager : NSObject <DownloadModelObserver, NBNetworkResponseDelegate>
{
    id <DownloadModel> m_downloadModel;
    NSMutableArray *m_requestWaitList;
    UCReachability *m_reachability;
    NSString *m_homePath;
    NSString *m_downloadPath;
    ObserverContainer *_observerContainer;
}

+ (id)sharedInstance;
@property(retain, nonatomic) ObserverContainer *observerContainer; // @synthesize observerContainer=_observerContainer;
@property(retain, nonatomic) NSString *downloadPath; // @synthesize downloadPath=m_downloadPath;
@property(retain, nonatomic) NSString *homePath; // @synthesize homePath=m_homePath;
@property(retain, nonatomic) UCReachability *reachability; // @synthesize reachability=m_reachability;
@property(retain, nonatomic) NSMutableArray *requestWaitList; // @synthesize requestWaitList=m_requestWaitList;
@property(retain, nonatomic, getter=getDownloadModel) id <DownloadModel> downloadModel; // @synthesize downloadModel=m_downloadModel;
- (id)getParameterInfoDataRequest:(id)arg1 error:(int)arg2;
- (void)onErrorDownloadEntireNovel:(id)arg1;
- (void)notifyDownloadTaskWithInfo:(id)arg1 didChangeStatus:(int)arg2 savePath:(id)arg3;
- (id)findRequestWaitNodeForRequestObject:(id)arg1;
- (void)handleReqeustFailed:(id)arg1;
- (void)reportError:(id)arg1;
- (void)onFailedNotifyWithRequest:(id)arg1;
- (void)onFinishedNotifyWithRequest:(id)arg1;
- (_Bool)canHandleFailedTaskBeforeRetry:(id)arg1;
- (id)filePathForNewFileName:(id)arg1 forTask:(id)arg2;
- (void)downloadModel:(id)arg1 taskDidChangeProgress:(id)arg2;
- (void)downloadModel:(id)arg1 taskDidChangeStatus:(id)arg2;
- (void)notifyDownloadTaskRepeatByDownloadInfo:(id)arg1;
- (void)notifyDownloadTaskFailByBookID:(id)arg1 withError:(id)arg2;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)showOrHideNetworkActivityIndicator;
- (id)requestBookDownloadUrl:(id)arg1;
- (_Bool)processUrlTimeoutDownloadTask:(id)arg1;
- (id)getDownloadDirectory;
- (float)getDownloadProgressByBookID:(id)arg1;
- (_Bool)isExistTask:(id)arg1;
- (_Bool)findSameDownloadTaskByBookID:(id)arg1 andTaskType:(int)arg2;
- (id)findDownloadTaskByBookID:(id)arg1 withType:(int)arg2;
- (id)findDownloadTaskByBookID:(id)arg1 isPrereadTask:(_Bool)arg2;
- (id)findDownloadTaskByBookID:(id)arg1 withFindblock:(CDUnknownBlockType)arg2;
- (int)getProgressDownloadTaskTypeByBookID:(id)arg1;
- (id)getDownloadInfoByBookID:(id)arg1 isPrereadTask:(_Bool)arg2;
- (int)getDownloadTaskStatusByBookID:(id)arg1 isPrereadTask:(_Bool)arg2;
- (void)getStatusWithBookId:(id)arg1 statusBlock:(CDUnknownBlockType)arg2;
- (void)deleteAllDownlodTask;
- (void)stopAllAutoDownloadTasks;
- (void)resumeAllPausedTasks;
- (_Bool)shouldExecuteWithTaskType:(int)arg1 isPrereadTask:(_Bool)arg2;
- (id)deleteDownloadTaskWithTaskList:(id)arg1 isPrereadTask:(_Bool)arg2 bookId:(id)arg3;
- (id)removeRequestWaitNodeIfNeededWithBookID:(id)arg1;
- (void)cancelAllDownloadTaskByBookID:(id)arg1;
- (void)cancelDownloadByBookID:(id)arg1 isPrereadTask:(_Bool)arg2;
- (void)stopDownloadByBookID:(id)arg1 isPrereadTask:(_Bool)arg2;
- (_Bool)startDownloadByBookID:(id)arg1 isPrereadTask:(_Bool)arg2;
- (_Bool)addTaskToWaitServerRequest:(id)arg1;
- (_Bool)startReuqestBookInfoAndDownload:(id)arg1;
- (_Bool)startNBDownloadTaskWithBookInfo:(id)arg1;
- (_Bool)startBookDownloadTaskWithInfo:(id)arg1;
- (void)deleteTaskArray:(id)arg1 shouldDeleteFile:(_Bool)arg2;
- (void)deleteCompletedInvalidTask;
- (void)dealloc;
- (void)commonInitInNextRunLoop;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

