//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NBBookServiceBase-Protocol.h"
#import "NBBookUpdateServiceDelegate-Protocol.h"
#import "NBPAAccountManagerObserver-Protocol.h"
#import "NBPABeanTicketCheckUpdateServiceDelegate-Protocol.h"
#import "NBPADecompressQueueDelegate-Protocol.h"
#import "NBPADownloadServiceDelegate-Protocol.h"
#import "NBPAPageTipAquireDelegate-Protocol.h"
#import "NBPAPreferentialInfoServiceDelegate-Protocol.h"

@class NBPAActivityService, NBPABeanDetailInfo, NBPABeanTicketCheckUpdateService, NBPACheckUpdateService, NBPADecompressQueue, NBPADownloadService, NBPAGrantedBeanTicketDataItem, NBPAPageTipAquire, NBPAPageTipItem, NBPAPreferentialInfoService, NSMutableDictionary, NSString, NSTimer;
@protocol NBPAServiceDelegate;

@interface NBPAService : NSObject <NBPADownloadServiceDelegate, NBPADecompressQueueDelegate, NBPAAccountManagerObserver, NBBookUpdateServiceDelegate, NBPABeanTicketCheckUpdateServiceDelegate, NBPAPageTipAquireDelegate, NBPAPreferentialInfoServiceDelegate, NBBookServiceBase>
{
    id <NBPAServiceDelegate> _delegate;
    NBPAGrantedBeanTicketDataItem *_serverPushedTickets;
    NBPAGrantedBeanTicketDataItem *_activityPresentTickets;
    NBPABeanDetailInfo *_suitableExpireTicket;
    NBPAPageTipItem *_pageTipItem;
    NBPAPreferentialInfoService *_preferentialInfoService;
    NBPADownloadService *_downloadService;
    NBPADecompressQueue *_decompressionQueue;
    NBPACheckUpdateService *_checkUpdateService;
    NBPABeanTicketCheckUpdateService *_beanTicketUpdateService;
    NBPAActivityService *_activityService;
    NSMutableDictionary *_pageTipItemDict;
    NBPAPageTipAquire *_tipAquire;
    NSTimer *_receiptTimer;
    long long _receiptsRetryTime;
    long long _beanTicketAlertFlags;
}

@property(nonatomic) long long beanTicketAlertFlags; // @synthesize beanTicketAlertFlags=_beanTicketAlertFlags;
@property(nonatomic) long long receiptsRetryTime; // @synthesize receiptsRetryTime=_receiptsRetryTime;
@property(retain, nonatomic) NSTimer *receiptTimer; // @synthesize receiptTimer=_receiptTimer;
@property(retain, nonatomic) NBPAPageTipAquire *tipAquire; // @synthesize tipAquire=_tipAquire;
@property(retain, nonatomic) NSMutableDictionary *pageTipItemDict; // @synthesize pageTipItemDict=_pageTipItemDict;
@property(retain, nonatomic) NBPAActivityService *activityService; // @synthesize activityService=_activityService;
@property(retain, nonatomic) NBPABeanTicketCheckUpdateService *beanTicketUpdateService; // @synthesize beanTicketUpdateService=_beanTicketUpdateService;
@property(retain, nonatomic) NBPACheckUpdateService *checkUpdateService; // @synthesize checkUpdateService=_checkUpdateService;
@property(retain, nonatomic) NBPADecompressQueue *decompressionQueue; // @synthesize decompressionQueue=_decompressionQueue;
@property(retain, nonatomic) NBPADownloadService *downloadService; // @synthesize downloadService=_downloadService;
@property(retain, nonatomic) NBPAPreferentialInfoService *preferentialInfoService; // @synthesize preferentialInfoService=_preferentialInfoService;
@property(readonly, retain, nonatomic) NBPAPageTipItem *pageTipItem; // @synthesize pageTipItem=_pageTipItem;
@property(retain, nonatomic) NBPABeanDetailInfo *suitableExpireTicket; // @synthesize suitableExpireTicket=_suitableExpireTicket;
@property(retain, nonatomic) NBPAGrantedBeanTicketDataItem *activityPresentTickets; // @synthesize activityPresentTickets=_activityPresentTickets;
@property(retain, nonatomic) NBPAGrantedBeanTicketDataItem *serverPushedTickets; // @synthesize serverPushedTickets=_serverPushedTickets;
@property(nonatomic) id <NBPAServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)preferentialService:(id)arg1 finishedUpdateInfoForBookIds:(id)arg2;
- (void)preferentialServiceFailedUpdateInfo:(id)arg1;
- (void)ticketServiceDidFinishedUpdateWithSuccess:(_Bool)arg1;
- (void)bookUpdateService:(id)arg1 didFinishBookUpdateWithResult:(_Bool)arg2;
- (void)bookUpdateService:(id)arg1 hasNumberOfIncrChapterUpdates:(long long)arg2;
- (void)bookUpdateService:(id)arg1 hasErrorCorrectionForBookItem:(id)arg2;
- (void)bookUpdateService:(id)arg1 hasIncrChapterUpdateForBookItem:(id)arg2;
- (void)notifyObserversForSelector:(SEL)arg1 withBookItem:(id)arg2;
- (void)didErrorAquireWithResponseData:(id)arg1;
- (void)didFinishAquireText:(id)arg1 url:(id)arg2 bookId:(id)arg3;
- (void)ticketServiceDidFinishedUpdateInfo:(id)arg1;
- (void)accountManager:(id)arg1 didUserIdChangeTo:(id)arg2;
- (void)bookDownloadService:(id)arg1 didChangeDownloadCornerMarkStatusForBookItem:(id)arg2;
- (void)bookDownloadService:(id)arg1 didFinishIncrCacheForChapter:(id)arg2 forBookItem:(id)arg3;
- (void)bookDownloadService:(id)arg1 didFinishOfflineDownloadForBookItem:(id)arg2;
- (void)bookDownloadService:(id)arg1 didFinishTryBagDownloadForBookItem:(id)arg2;
- (void)decompressQueue:(id)arg1 didFailDecompressWithBookItem:(id)arg2 andType:(int)arg3;
- (void)decompressQueue:(id)arg1 didFinishDecompressWithBookItem:(id)arg2 andType:(int)arg3;
- (void)updatePreferentialInfoForBook:(id)arg1;
- (void)removeAllScheduledIssues;
- (_Bool)shouldBookReaderShowBeanAlert;
- (_Bool)shouldBookshelfShowBeanAlert;
- (void)didBookReaderShowBeanAlert;
- (void)didBookshelfShowBeanAlert;
- (id)getPageTipItemWithBookItem:(id)arg1;
- (void)loadPageTipItemWithBookItem:(id)arg1;
- (id)getExpireTicket;
- (id)getActivityPresentTickets;
- (id)getServerPushedTickets;
- (void)triggerBeanTicketUpdateService;
- (void)downloadTaskWithInfo:(id)arg1 didChangeStatus:(int)arg2 savePath:(id)arg3;
- (void)incrUpdateTask:(id)arg1 didFinishDownloadChapterContent:(id)arg2;
- (void)notifyDelegateForFinishBookUpdateWithResult:(id)arg1;
- (void)realBeginQueryBookUpdate;
- (_Bool)shouldShowDownloadCornerMarkForBookItem:(id)arg1;
- (_Bool)beginOfflineDownloadForBookItem:(id)arg1 withExtentedInfo:(id)arg2;
- (void)didEnterShelf;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

