//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NBPABatchInfoResponseData, NBPAPaymentManager, NSDictionary;

@protocol NBPAPaymentManagerObserverProtocol <NSObject>

@optional
- (void)paymentManagerDidShowRechargeController:(NBPAPaymentManager *)arg1;
- (void)paymentManagerDidExitRechargeController:(NBPAPaymentManager *)arg1;
- (void)paymentManagerFailedToGetUserID:(NBPAPaymentManager *)arg1;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedGetBatchInfo:(NSDictionary *)arg2 withResult:(NBPABatchInfoResponseData *)arg3;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedGetBeanTicketForCurrentUserWithDetailInfo:(NSDictionary *)arg2;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedGetBeanTicketAffordBatchCountWithDetailInfo:(NSDictionary *)arg2;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedCheckBeanTicketUpdateWithDetailInfo:(NSDictionary *)arg2;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedGetPresentBeanTicketWithDetailInfo:(NSDictionary *)arg2;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedGetBestTicketSetWithDetailInfo:(NSDictionary *)arg2;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedGetRechargeStatusWithDetailInfo:(NSDictionary *)arg2;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedGetAccountInfoWithDetailInfo:(NSDictionary *)arg2;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedBatchPurchaseWithDetailInfo:(NSDictionary *)arg2;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedGetBatchInfoWithDetailInfo:(NSDictionary *)arg2;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedGetBalanceWithDetailInfo:(NSDictionary *)arg2;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedRechargeWithDetailInfo:(NSDictionary *)arg2;
- (void)paymentManager:(NBPAPaymentManager *)arg1 finishedPurchaseWithDetailInfo:(NSDictionary *)arg2;
@end

