//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;
@protocol NBShelfEmptyViewDelegate;

@interface NBShelfEmptyView : UIView
{
    id <NBShelfEmptyViewDelegate> _delegate;
    UIImageView *_icon;
    UILabel *_titleLabel;
    UIButton *_homeButton;
}

@property(retain, nonatomic) UIButton *homeButton; // @synthesize homeButton=_homeButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
@property(nonatomic) id <NBShelfEmptyViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onHomeButtonClicked;
- (void)updateHomeButton;
- (void)updateTitleLabel;
- (void)updateIcon;
- (void)updateUIComponents;
- (void)layoutHomeButton;
- (void)layoutTitleLabel;
- (void)layoutIcon;
- (void)layoutUIComponents;
- (void)createHomeButton;
- (void)createTitleLabel;
- (void)createIcon;
- (void)createUIComponents;
- (void)updateTheme;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

