//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSData, NSDictionary, NSString;

@protocol PicBDataProviderDelegate <NSObject>
- (unsigned long long)totalPics;
- (void)didPicLoadFaildWithUrl:(NSString *)arg1 error:(long long)arg2;
- (void)didPicFinishLoadWithUrl:(NSString *)arg1 imageData:(NSData *)arg2;

@optional
- (void)didGetRecommendImageWithURL:(NSString *)arg1 imageData:(NSData *)arg2;
- (void)didGetRecommendDataWithQuerys:(NSDictionary *)arg1 recos:(NSDictionary *)arg2;
- (void)didPreloadFinish:(_Bool)arg1;
- (void)didGetDataLength:(long long)arg1 totalLength:(long long)arg2 withUrl:(NSString *)arg3;
- (void)didGetMorePics:(NSArray *)arg1;
@end

