//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSObjectQueueProtocol-Protocol.h"
#import "UCConnectionIntf-Protocol.h"

@class CFStyleConnection, NSString, NSURLConnection;
@protocol UCConnectionDelegate;

@interface UCConnection : NSObject <NSObjectQueueProtocol, UCConnectionIntf>
{
    NSURLConnection *m_urlConn;
    CFStyleConnection *m_cfConn;
    id m_activeConn;
    int m_curType;
    id <UCConnectionDelegate> m_outerDelegate;
    NSString *m_requestKey;
}

+ (id)connectionWithRequest:(id)arg1 delegate:(id)arg2;
+ (id)connectionWithRequest:(id)arg1 delegate:(id)arg2 isByQueue:(_Bool)arg3;
+ (_Bool)canHandleRequest:(id)arg1;
+ (int)selectConnType;
- (void)removeSelfFromQueue;
- (void)scheduleOnQueue:(id)arg1;
- (id)onWillSendRequest:(id)arg1 redirectResponse:(id)arg2;
- (void)onFailed:(int)arg1;
- (_Bool)onRecvFinished;
- (_Bool)onRecvData:(void *)arg1 length:(int)arg2;
- (_Bool)onGotHttpResponse:(id)arg1;
- (id)connection:(id)arg1 willCacheResponse:(id)arg2;
- (void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (_Bool)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)start;
- (id)initWithRequest:(id)arg1 delegate:(id)arg2 startImmediately:(_Bool)arg3;
- (void)cancel;
- (id)initWithRequest:(id)arg1 delegate:(id)arg2;
- (void)dealloc;
- (id)initStaticWithType:(int)arg1 req:(id)arg2 delegate:(id)arg3 isByQueue:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

