//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class UIColor;
@protocol UCDoodleControllerProtocol;

@interface UCDoodlePen : NSObject
{
    _Bool _focus;
    id <UCDoodleControllerProtocol> _doodleController;
    UIColor *_color;
}

@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(nonatomic) _Bool focus; // @synthesize focus=_focus;
@property(nonatomic) id <UCDoodleControllerProtocol> doodleController; // @synthesize doodleController=_doodleController;
- (id)makeLayerWithImageSize:(struct CGSize)arg1 atPoint:(struct CGPoint)arg2;
- (void)dealloc;

@end

