//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSNumber, NSSet, NSString, WXBaseModule, WXBizSyncDataInfo, WXTMStatCommand, WXTMStatInfo;

@protocol WXJSDKBridgeModuleBizDelegate <NSObject>
- (void)bizGetCmsResource:(WXBaseModule *)arg1 params:(NSDictionary *)arg2 andCallback:(void (^)(_Bool, id))arg3;
- (void)bizGetCDParams:(WXBaseModule *)arg1 forKey:(NSString *)arg2 callback:(void (^)(_Bool, id))arg3;
- (void)bizSyncDataInfo:(WXBaseModule *)arg1 info:(WXBizSyncDataInfo *)arg2;
- (void)bizTmStat:(WXBaseModule *)arg1 statCommand:(WXTMStatCommand *)arg2;
- (void)bizTmStat:(WXBaseModule *)arg1 statInfo:(WXTMStatInfo *)arg2;
- (void)bizSetStatusBarStyle:(WXBaseModule *)arg1 style:(NSNumber *)arg2 callback:(void (^)(_Bool, id))arg3;
- (void)bizToggleMenuPanel:(WXBaseModule *)arg1 aid:(NSString *)arg2 cid:(NSNumber *)arg3 callback:(void (^)(_Bool, id))arg4;
- (void)bizShare:(WXBaseModule *)arg1 title:(NSString *)arg2 content:(NSString *)arg3 url:(NSString *)arg4 target:(NSString *)arg5 disableTargets:(NSSet *)arg6 iconUrl:(NSString *)arg7 type:(NSString *)arg8 callback:(void (^)(_Bool, id))arg9;
- (void)bizSaveImage:(WXBaseModule *)arg1 url:(NSString *)arg2 callback:(void (^)(_Bool, id))arg3;
- (void)bizOpenPicViewer:(WXBaseModule *)arg1 title:(NSString *)arg2 picUrl:(NSString *)arg3 itemType:(long long)arg4 ref:(NSString *)arg5 data:(NSArray *)arg6 index:(long long)arg7 time_stat:(NSArray *)arg8 callback:(void (^)(_Bool, id))arg9;
- (void)bizOpenPageUrl:(WXBaseModule *)arg1 url:(NSString *)arg2 biz_type:(NSString *)arg3 biz_info:(NSDictionary *)arg4 time_stat:(NSArray *)arg5 callback:(void (^)(_Bool, id))arg6;
- (void)bizFavoStatusChange:(WXBaseModule *)arg1 action:(NSString *)arg2 url:(NSString *)arg3 aid:(NSString *)arg4 cid:(NSString *)arg5 title:(NSString *)arg6 summary:(NSString *)arg7 sourceName:(NSString *)arg8 iconUrl:(NSString *)arg9 callback:(void (^)(_Bool, id))arg10;
- (void)bizWeatherLocal:(WXBaseModule *)arg1 callback:(void (^)(WXSWeatherModel *))arg2;
- (NSString *)bizEncryptOrDecrypt:(WXBaseModule *)arg1 enc:(long long)arg2 type:(long long)arg3 data:(NSString *)arg4;
- (void)bizCommonStat:(WXBaseModule *)arg1 category:(NSString *)arg2 event_category:(NSString *)arg3 event_action:(NSString *)arg4 key_value:(NSDictionary *)arg5 real_time:(_Bool)arg6 syncOldStat:(_Bool)arg7 callback:(void (^)(_Bool, id))arg8;
@end

