//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class AuthenTouchIDPwdService, NSString, UISwitch;

@interface FixedImageViewSizeTableViewCell : UITableViewCell
{
    UISwitch *_switchButton;
    NSString *_cellTitle;
    NSString *_menuId;
    AuthenTouchIDPwdService *_touchIDObject;
    struct CGSize fixedSize;
}

@property(retain, nonatomic) AuthenTouchIDPwdService *touchIDObject; // @synthesize touchIDObject=_touchIDObject;
@property(retain, nonatomic) NSString *menuId; // @synthesize menuId=_menuId;
@property(retain, nonatomic) NSString *cellTitle; // @synthesize cellTitle=_cellTitle;
@property(retain, nonatomic) UISwitch *switchButton; // @synthesize switchButton=_switchButton;
@property(nonatomic) struct CGSize fixedSize; // @synthesize fixedSize;
- (void).cxx_destruct;
- (void)httpTimeoutFailed:(id)arg1;
- (void)httpTimeoutFinish:(id)arg1;
- (void)touchIDSettingUpdate;
- (id)reSizeImage:(id)arg1 toSize:(struct CGSize)arg2;
- (void)setSwitchButtonOnOrYes;
- (void)openTokenSwitchFail;
- (void)openTokenSwitchSuccess;
- (void)switchButtonAction;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

