//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ICBCIMViewController.h"

#import "JumpToViewControllerDelegate-Protocol.h"
#import "QRPayCheckPasswordViewProtocol-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSString, QRPayCheckPasswordView, QRPayNoCardView, UITableView;

@interface QRPayCardListTableViewController : ICBCIMViewController <QRPayCheckPasswordViewProtocol, JumpToViewControllerDelegate, UITableViewDelegate, UITableViewDataSource>
{
    _Bool _isTouchOwnBankCard;
    int _viewType;
    int _fromType;
    NSArray *_tableData;
    UITableView *_tableView;
    QRPayCheckPasswordView *_checkView;
    QRPayNoCardView *_noCardView;
}

@property(nonatomic) _Bool isTouchOwnBankCard; // @synthesize isTouchOwnBankCard=_isTouchOwnBankCard;
@property(retain, nonatomic) QRPayNoCardView *noCardView; // @synthesize noCardView=_noCardView;
@property(retain, nonatomic) QRPayCheckPasswordView *checkView; // @synthesize checkView=_checkView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) int fromType; // @synthesize fromType=_fromType;
@property(nonatomic) int viewType; // @synthesize viewType=_viewType;
@property(retain, nonatomic) NSArray *tableData; // @synthesize tableData=_tableData;
- (void).cxx_destruct;
- (void)backclick;
- (void)jumpToViewController;
- (id)getOnlyOwnBankCardListWith:(id)arg1;
- (id)getCardListAfterFilterCreditCardWith:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)refreshTableData;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)loadUI;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

