//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "RefreshButtonDelegate-Protocol.h"

@class NSString, SBRefreshButton, UILabel;

@interface SBNavRefreshTitle : UIView <RefreshButtonDelegate>
{
    SBRefreshButton *_refreshButton;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    id _target;
    SEL _action;
}

@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) id target; // @synthesize target=_target;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) SBRefreshButton *refreshButton; // @synthesize refreshButton=_refreshButton;
- (void).cxx_destruct;
- (_Bool)isRefreshing;
- (void)disableRefreshButton;
- (void)enableRefreshButton;
- (void)stopAnimatingRefreshButton;
- (void)startAnimatingRefreshButton;
- (void)refreshBtnClicked;
@property(copy, nonatomic) NSString *subTitle; // @dynamic subTitle;
@property(copy, nonatomic) NSString *title; // @dynamic title;
- (void)changeFrameAccordingToTitle;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithTitle:(id)arg1 subTitle:(id)arg2 target:(id)arg3 action:(SEL)arg4;
- (id)initWithTitle:(id)arg1 subTitle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

