//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CCBBaseRequestModel.h"

@class NSString;

@interface CCB_I_FUND10 : CCBBaseRequestModel
{
    NSString *_fundcode;
    NSString *_marketcode;
    NSString *_sys_tx_code;
    NSString *_scr_eps_dfrn_mode_cd;
}

@property(retain, nonatomic) NSString *scr_eps_dfrn_mode_cd; // @synthesize scr_eps_dfrn_mode_cd=_scr_eps_dfrn_mode_cd;
@property(retain, nonatomic) NSString *sys_tx_code; // @synthesize sys_tx_code=_sys_tx_code;
@property(retain, nonatomic) NSString *marketcode; // @synthesize marketcode=_marketcode;
@property(retain, nonatomic) NSString *fundcode; // @synthesize fundcode=_fundcode;
- (void).cxx_destruct;

@end

