//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CCBFormViewController.h"

#import "CCBCalendarDelegate-Protocol.h"
#import "CCBSelectionActionSheetDelegate-Protocol.h"

@class CCBSelectionActionSheet, CCB_7_VM_PaperForeignExchangeSimulatePendCloseTrade, NSString;

@interface CCB_7_VC_PaperForeignExchangeSimulatePendCloseTrade : CCBFormViewController <CCBSelectionActionSheetDelegate, CCBCalendarDelegate>
{
    CCB_7_VM_PaperForeignExchangeSimulatePendCloseTrade *_viewModel;
    CCBSelectionActionSheet *_selectionSheet;
}

@property(retain, nonatomic) CCBSelectionActionSheet *selectionSheet; // @synthesize selectionSheet=_selectionSheet;
@property(retain, nonatomic) CCB_7_VM_PaperForeignExchangeSimulatePendCloseTrade *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)formViewCellDidClickRightButton:(id)arg1;
- (void)selectionActionSheetDidCancel:(id)arg1;
- (void)calendarViewDidCancel:(id)arg1;
- (void)calendarView:(id)arg1 didSelectDate:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)formViewCell:(id)arg1 didClickButtonAtIndex:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)requestMaketWithResponseBlock:(CDUnknownBlockType)arg1;
- (void)viewDidLoad;
- (id)initWithDataInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

