//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CCBBaseModel.h"

@class NSArray, NSString;

@interface CCB_O_NFOC02 : CCBBaseModel
{
    NSString *_total_rec;
    NSArray *_productList;
}

+ (id)mj_objectClassInArray;
@property(retain, nonatomic) NSArray *productList; // @synthesize productList=_productList;
@property(retain, nonatomic) NSString *total_rec; // @synthesize total_rec=_total_rec;
- (void).cxx_destruct;
- (void)dealloc;

@end

