//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CCBFormViewController.h"

#import "CCBCalendarDelegate-Protocol.h"
#import "CCBDropDownMenuBarDataSource-Protocol.h"
#import "CCBDropDownMenuBarDelegate-Protocol.h"
#import "CCBSelectionActionSheetDelegate-Protocol.h"
#import "CCB_VC_BSNUCalendarSelectionDelegate-Protocol.h"

@class CCBDropDownMenuBar, CCBUNSelectionActionSheet, CCB_3_VM_WealthCenter_Persion_CheckInvestInfoDetail, NSString;

@interface CCB_3_VC_WealthCenter_Persion_CheckInvestInfoDetail : CCBFormViewController <CCBCalendarDelegate, CCBSelectionActionSheetDelegate, CCBDropDownMenuBarDataSource, CCBDropDownMenuBarDelegate, CCB_VC_BSNUCalendarSelectionDelegate>
{
    CCB_3_VM_WealthCenter_Persion_CheckInvestInfoDetail *_transferModel;
    CCBUNSelectionActionSheet *_calenderSelection;
    CCBDropDownMenuBar *_dropDownMenuBar;
}

@property(retain, nonatomic) CCBDropDownMenuBar *dropDownMenuBar; // @synthesize dropDownMenuBar=_dropDownMenuBar;
@property(retain, nonatomic) CCBUNSelectionActionSheet *calenderSelection; // @synthesize calenderSelection=_calenderSelection;
@property(retain, nonatomic) CCB_3_VM_WealthCenter_Persion_CheckInvestInfoDetail *transferModel; // @synthesize transferModel=_transferModel;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)calendarSelection:(id)arg1 didSelectMonthWithTag:(long long)arg2 andIndexPath:(id)arg3 year:(id)arg4 month:(id)arg5;
- (void)cancelBtnDidClickOnCalendarSelection:(id)arg1;
- (_Bool)dropDownMenuBar:(id)arg1 didSelectRowInMainTable:(unsigned long long)arg2 menuBtnIndex:(long long)arg3;
- (long long)dropDownMenuBar:(id)arg1 selectedRowInMainTable:(long long)arg2;
- (id)dropDownMenuBar:(id)arg1 titleForRowInMainTable:(unsigned long long)arg2 menuBtnIndex:(long long)arg3;
- (long long)dropDownMenuBar:(id)arg1 numberOfRowsInMainTable:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)addObserve;
- (void)setUI;
- (void)didTriggerRefresh;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

