//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CCBBaseFormViewModel.h"

@class CCBBaseError, FUND06_fundlist, NSArray;

@interface CCB_7_VM_FundsToolsCompareAsset : CCBBaseFormViewModel
{
    CCBBaseError *_error;
    FUND06_fundlist *_fund1;
    FUND06_fundlist *_fund2;
    NSArray *_assetList1;
    NSArray *_assetList2;
}

@property(retain, nonatomic) NSArray *assetList2; // @synthesize assetList2=_assetList2;
@property(retain, nonatomic) NSArray *assetList1; // @synthesize assetList1=_assetList1;
@property(retain, nonatomic) FUND06_fundlist *fund2; // @synthesize fund2=_fund2;
@property(retain, nonatomic) FUND06_fundlist *fund1; // @synthesize fund1=_fund1;
@property(retain, nonatomic) CCBBaseError *error; // @synthesize error=_error;
- (void).cxx_destruct;
- (void)requestFinished:(id)arg1 output:(id)arg2 error:(id)arg3;
- (void)requestForFUND19WithFundCode:(id)arg1;
- (void)requestForFundsCompareAsset;
- (id)valueListWithType:(id)arg1 fundIndex:(long long)arg2;
- (void)setFormItem;
- (id)initWithFund1:(id)arg1 fund2:(id)arg2;

@end

