//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CCB_O_SJH020, CCB_O_SJH021, NSArray, NSString;

@interface CCB_7_PSESJH026Parameters : NSObject
{
    NSString *_FrCltFxTnDstlDepCcyCd;
    NSString *_Use_ShrtNm;
    NSString *_Mnplt_Dt_Tm;
    NSArray *_exchangeInfos;
    CCB_O_SJH020 *_SJH020;
    CCB_O_SJH021 *_SJH021;
}

@property(retain, nonatomic) CCB_O_SJH021 *SJH021; // @synthesize SJH021=_SJH021;
@property(retain, nonatomic) CCB_O_SJH020 *SJH020; // @synthesize SJH020=_SJH020;
@property(copy, nonatomic) NSArray *exchangeInfos; // @synthesize exchangeInfos=_exchangeInfos;
@property(copy, nonatomic) NSString *Mnplt_Dt_Tm; // @synthesize Mnplt_Dt_Tm=_Mnplt_Dt_Tm;
@property(copy, nonatomic) NSString *Use_ShrtNm; // @synthesize Use_ShrtNm=_Use_ShrtNm;
@property(copy, nonatomic) NSString *FrCltFxTnDstlDepCcyCd; // @synthesize FrCltFxTnDstlDepCcyCd=_FrCltFxTnDstlDepCcyCd;
- (void).cxx_destruct;

@end

