//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CCBFormItem.h"

@class NSString;

@interface CCB_4_BuyAndRemittanceItem : CCBFormItem
{
    _Bool _showLine;
    NSString *_Use_ShrtNm;
    NSString *_FrCltFxTnDstlStr;
    NSString *_TxnAmt;
    NSString *_Txn_Dt_Tm;
}

@property(nonatomic) _Bool showLine; // @synthesize showLine=_showLine;
@property(retain, nonatomic) NSString *Txn_Dt_Tm; // @synthesize Txn_Dt_Tm=_Txn_Dt_Tm;
@property(retain, nonatomic) NSString *TxnAmt; // @synthesize TxnAmt=_TxnAmt;
@property(retain, nonatomic) NSString *FrCltFxTnDstlStr; // @synthesize FrCltFxTnDstlStr=_FrCltFxTnDstlStr;
@property(retain, nonatomic) NSString *Use_ShrtNm; // @synthesize Use_ShrtNm=_Use_ShrtNm;
- (void).cxx_destruct;
- (id)init;

@end

