//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CCBBaseModel.h"

@class NSString;

@interface SJJJ37_ReqProdGRP : CCBBaseModel
{
    NSString *_Cst_ID;
    NSString *_Idv_Lgl_Nm;
    NSString *_PD_Rqm_ID;
    NSString *_CST_Ivs_Rqm_TpCd;
    NSString *_LCS_Cd;
    NSString *_Glx_Fnd_Lvl1_CL_ECD;
    NSString *_Glx_Fnd_Lvl1_CL_Nm;
    NSString *_PdAr_Dsc;
    NSString *_Frcst_Ivs_Ddln_TpCd;
    NSString *_Frcst_Ivs_Amt_TpCd;
    NSString *_Fnd_Ivs_Topc_TpDs;
    NSString *_Fnd_IvsmStl_TpCd;
    NSString *_Fnd_Mgr_Nm;
    NSString *_AR_Dsc;
    NSString *_Int_Dsc;
    NSString *_Cost_Dsc;
    NSString *_Expc_YldRto_Scop_Cd;
    NSString *_Rsk_Grd_Cd;
    NSString *_Ivs_Amt_CcyCd;
    NSString *_Crt_Dt;
    NSString *_MblPh_No;
    NSString *_CSDC_Fnd_Rsk_Grd_Cd;
    NSString *_Flt_Ind;
    NSString *_Seg_Ind;
    NSString *_PD_Attr_Enqr_Max_Val;
    NSString *_PD_Attr_Enqr_Min_Val;
}

@property(retain, nonatomic) NSString *PD_Attr_Enqr_Min_Val; // @synthesize PD_Attr_Enqr_Min_Val=_PD_Attr_Enqr_Min_Val;
@property(retain, nonatomic) NSString *PD_Attr_Enqr_Max_Val; // @synthesize PD_Attr_Enqr_Max_Val=_PD_Attr_Enqr_Max_Val;
@property(retain, nonatomic) NSString *Seg_Ind; // @synthesize Seg_Ind=_Seg_Ind;
@property(retain, nonatomic) NSString *Flt_Ind; // @synthesize Flt_Ind=_Flt_Ind;
@property(retain, nonatomic) NSString *CSDC_Fnd_Rsk_Grd_Cd; // @synthesize CSDC_Fnd_Rsk_Grd_Cd=_CSDC_Fnd_Rsk_Grd_Cd;
@property(retain, nonatomic) NSString *MblPh_No; // @synthesize MblPh_No=_MblPh_No;
@property(retain, nonatomic) NSString *Crt_Dt; // @synthesize Crt_Dt=_Crt_Dt;
@property(retain, nonatomic) NSString *Ivs_Amt_CcyCd; // @synthesize Ivs_Amt_CcyCd=_Ivs_Amt_CcyCd;
@property(retain, nonatomic) NSString *Rsk_Grd_Cd; // @synthesize Rsk_Grd_Cd=_Rsk_Grd_Cd;
@property(retain, nonatomic) NSString *Expc_YldRto_Scop_Cd; // @synthesize Expc_YldRto_Scop_Cd=_Expc_YldRto_Scop_Cd;
@property(retain, nonatomic) NSString *Cost_Dsc; // @synthesize Cost_Dsc=_Cost_Dsc;
@property(retain, nonatomic) NSString *Int_Dsc; // @synthesize Int_Dsc=_Int_Dsc;
@property(retain, nonatomic) NSString *AR_Dsc; // @synthesize AR_Dsc=_AR_Dsc;
@property(retain, nonatomic) NSString *Fnd_Mgr_Nm; // @synthesize Fnd_Mgr_Nm=_Fnd_Mgr_Nm;
@property(retain, nonatomic) NSString *Fnd_IvsmStl_TpCd; // @synthesize Fnd_IvsmStl_TpCd=_Fnd_IvsmStl_TpCd;
@property(retain, nonatomic) NSString *Fnd_Ivs_Topc_TpDs; // @synthesize Fnd_Ivs_Topc_TpDs=_Fnd_Ivs_Topc_TpDs;
@property(retain, nonatomic) NSString *Frcst_Ivs_Amt_TpCd; // @synthesize Frcst_Ivs_Amt_TpCd=_Frcst_Ivs_Amt_TpCd;
@property(retain, nonatomic) NSString *Frcst_Ivs_Ddln_TpCd; // @synthesize Frcst_Ivs_Ddln_TpCd=_Frcst_Ivs_Ddln_TpCd;
@property(retain, nonatomic) NSString *PdAr_Dsc; // @synthesize PdAr_Dsc=_PdAr_Dsc;
@property(retain, nonatomic) NSString *Glx_Fnd_Lvl1_CL_Nm; // @synthesize Glx_Fnd_Lvl1_CL_Nm=_Glx_Fnd_Lvl1_CL_Nm;
@property(retain, nonatomic) NSString *Glx_Fnd_Lvl1_CL_ECD; // @synthesize Glx_Fnd_Lvl1_CL_ECD=_Glx_Fnd_Lvl1_CL_ECD;
@property(retain, nonatomic) NSString *LCS_Cd; // @synthesize LCS_Cd=_LCS_Cd;
@property(retain, nonatomic) NSString *CST_Ivs_Rqm_TpCd; // @synthesize CST_Ivs_Rqm_TpCd=_CST_Ivs_Rqm_TpCd;
@property(retain, nonatomic) NSString *PD_Rqm_ID; // @synthesize PD_Rqm_ID=_PD_Rqm_ID;
@property(retain, nonatomic) NSString *Idv_Lgl_Nm; // @synthesize Idv_Lgl_Nm=_Idv_Lgl_Nm;
@property(retain, nonatomic) NSString *Cst_ID; // @synthesize Cst_ID=_Cst_ID;
- (void).cxx_destruct;

@end

