//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UIButton, UILabel, UITapGestureRecognizer;
@protocol ALACertificationCardViewDelegate;

@interface ALACertificationCardView : UIView <UIGestureRecognizerDelegate>
{
    _Bool _isRealName;
    _Bool _isTapCardView;
    id <ALACertificationCardViewDelegate> _delegate;
    unsigned long long _authType;
    UIView *_cardView;
    UILabel *_titleLabel;
    UILabel *_describeLabel;
    UILabel *_realNameLabel;
    UIButton *_certificationButton;
    UIButton *_closeButton;
    UITapGestureRecognizer *_gestureRecognizer;
}

@property(nonatomic) _Bool isTapCardView; // @synthesize isTapCardView=_isTapCardView;
@property(retain, nonatomic) UITapGestureRecognizer *gestureRecognizer; // @synthesize gestureRecognizer=_gestureRecognizer;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIButton *certificationButton; // @synthesize certificationButton=_certificationButton;
@property(retain, nonatomic) UILabel *realNameLabel; // @synthesize realNameLabel=_realNameLabel;
@property(retain, nonatomic) UILabel *describeLabel; // @synthesize describeLabel=_describeLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *cardView; // @synthesize cardView=_cardView;
@property(nonatomic) unsigned long long authType; // @synthesize authType=_authType;
@property(nonatomic) _Bool isRealName; // @synthesize isRealName=_isRealName;
@property(nonatomic) __weak id <ALACertificationCardViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)changeString:(id)arg1 withColor:(id)arg2 withLineSpace:(double)arg3;
- (void)updateCertificationCardViewWithUserInfo:(id)arg1;
- (void)gestureRecognizerDidTap:(id)arg1;
- (void)buttonDidClick:(id)arg1;
- (void)setupUI;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

