//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIWindow.h>

@class UIControl, UIImageView, UILabel, UIView;
@protocol TBCComicFirstBrowserViewDelegate;

@interface TBCComicFirstBrowserView : UIWindow
{
    id <TBCComicFirstBrowserViewDelegate> _delegate;
    UIControl *_controlView;
    UIView *_contentView;
    UIImageView *_imageView;
    UILabel *_titleLabel;
}

@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIControl *controlView; // @synthesize controlView=_controlView;
@property(nonatomic) __weak id <TBCComicFirstBrowserViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onDismiss;
- (void)setupSubviews;
- (void)setupConfig;
- (id)init;
- (void)dealloc;

@end

