//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBCBaseConcernCell.h"

#import "TBCResManagerDelegate-Protocol.h"

@class NSString, UILabel;

@interface TBCConcernPostCell : TBCBaseConcernCell <TBCResManagerDelegate>
{
    UILabel *_postLabel;
}

+ (double)getTopAgreeViewHeight:(id)arg1;
@property(retain, nonatomic) UILabel *postLabel; // @synthesize postLabel=_postLabel;
- (void).cxx_destruct;
- (void)resoureManagerDelegate;
- (_Bool)isShouldShowVideoLiveButton:(id)arg1;
- (void)setObject:(id)arg1;
- (void)layoutSubviews;
- (void)setupUI;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

