//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBCIMBaseMessageItem.h"

@class NSString;

@interface TBCFrsGoodClassifyItem : TBCIMBaseMessageItem
{
    NSString *_index;
    NSString *_classId;
    NSString *_className;
}

@property(copy, nonatomic) NSString *className; // @synthesize className=_className;
@property(copy, nonatomic) NSString *classId; // @synthesize classId=_classId;
@property(copy, nonatomic) NSString *index; // @synthesize index=_index;
- (id)init;
- (void)dealloc;

@end

