//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class TBCImageView, UIImage, UIImageView, UILabel;

@interface TBCGroupUserListMainColView : UIView
{
    _Bool _isChecked;
    int _oriX;
    int _offX_withCheckBox;
    TBCImageView *_imgPortrait;
    UILabel *_labelName;
    UIImageView *_imgSex;
    UILabel *_labelPosition;
    UIImageView *_imgCheckBox;
    UIImage *_noCheckImg;
    UIImage *_checkedImg;
    UIView *_bottomLine;
}

@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(nonatomic) int offX_withCheckBox; // @synthesize offX_withCheckBox=_offX_withCheckBox;
@property(nonatomic) int oriX; // @synthesize oriX=_oriX;
@property(retain, nonatomic) UIImage *checkedImg; // @synthesize checkedImg=_checkedImg;
@property(retain, nonatomic) UIImage *noCheckImg; // @synthesize noCheckImg=_noCheckImg;
@property(nonatomic) _Bool isChecked; // @synthesize isChecked=_isChecked;
@property(retain, nonatomic) UIImageView *imgCheckBox; // @synthesize imgCheckBox=_imgCheckBox;
@property(retain, nonatomic) UILabel *labelPosition; // @synthesize labelPosition=_labelPosition;
@property(retain, nonatomic) UIImageView *imgSex; // @synthesize imgSex=_imgSex;
@property(retain, nonatomic) UILabel *labelName; // @synthesize labelName=_labelName;
@property(retain, nonatomic) TBCImageView *imgPortrait; // @synthesize imgPortrait=_imgPortrait;
- (void)resetCheckedState;
- (void)initPosition;
- (void)initSex;
- (void)initName;
- (void)initPortrait;
- (void)initCheckBox;
- (void)initBg;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

