//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBCVitalityPBCellDelegate-Protocol.h"

@class NSString, TBCOriginThreadInfo;

@protocol TBCVitalityPBTopViewDelegate <TBCVitalityPBCellDelegate>

@optional
- (void)onGiftListViewSendGift;
- (void)onClickOriginThreadInfo:(TBCOriginThreadInfo *)arg1;
- (void)onSubscribeChannel:(id)arg1;
- (void)onFollowWithItem:(id)arg1 fromType:(NSString *)arg2;
- (void)onLikeGodWithItem:(id)arg1;
@end

