//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"
#import "P_QNBObserverConfig-Protocol.h"

@class NSString, QNBCastDeviceInfo, QNBCastVideoInfo;

@protocol P_QNBPlayerCastConfig <NSObject, P_QNBObserverConfig>
- (void)setVolume:(double)arg1;
- (void)seekTime:(double)arg1;
- (void)close;
- (void)stop;
- (void)pause;
- (void)play;
- (void)startCastWithDeviceInfo:(QNBCastDeviceInfo *)arg1 videoInfo:(QNBCastVideoInfo *)arg2;
- (double)currentPlayTime;
- (double)duration;
- (unsigned long long)castState;
- (QNBCastDeviceInfo *)defaultDevice;
- (_Bool)isSupportHls:(QNBCastDeviceInfo *)arg1;

@optional
- (void)setBarrageState:(_Bool)arg1;
- (double)getDelayTimeToSeekAfterReceiveStartPlayState:(QNBCastDeviceInfo *)arg1;
- (void)setClarity:(NSString *)arg1 level:(NSString *)arg2;
@end

