//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QLCommentStarView;

@interface QLCommentStartSelectionView : UIView
{
    long long _starValue;
    CDUnknownBlockType _onValueChanged;
    QLCommentStarView *_starMarkView;
}

@property(retain, nonatomic) QLCommentStarView *starMarkView; // @synthesize starMarkView=_starMarkView;
@property(copy, nonatomic) CDUnknownBlockType onValueChanged; // @synthesize onValueChanged=_onValueChanged;
@property(nonatomic) long long starValue; // @synthesize starValue=_starValue;
- (void).cxx_destruct;
- (void)onStarMarkValueChanged:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithConfig:(id)arg1 valueChanged:(CDUnknownBlockType)arg2;

@end

