//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, TADNonClickPicAd, UIImage;

@interface TADPicAd : NSObject
{
    long long _adType;
    UIImage *_image;
    NSString *_text;
    TADNonClickPicAd *_nonClickPicAd;
}

@property(retain, nonatomic) TADNonClickPicAd *nonClickPicAd; // @synthesize nonClickPicAd=_nonClickPicAd;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) long long adType; // @synthesize adType=_adType;
- (void).cxx_destruct;
- (id)initWithNonClickPicAd:(id)arg1;

@end

