//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JUSDKTBMTopResult.h"

@class JUSDKTradeOrderQuery, NSArray;

@interface JUSDKTBJuTradeResult : JUSDKTBMTopResult
{
    NSArray *_trades;
    JUSDKTradeOrderQuery *_query;
}

+ (Class)classForName:(id)arg1;
@property(retain, nonatomic) JUSDKTradeOrderQuery *query; // @synthesize query=_query;
@property(retain, nonatomic) NSArray *trades; // @synthesize trades=_trades;
- (void).cxx_destruct;

@end

