//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QYCommonViewController.h"

@class UISegmentedControl, UISwitch, UITextView;

@interface QYRNTestController : QYCommonViewController
{
    UISwitch *_uiSwitch1;
    UISegmentedControl *_segCtl;
    UITextView *_textView;
}

@property(nonatomic) __weak UITextView *textView; // @synthesize textView=_textView;
@property(nonatomic) __weak UISegmentedControl *segCtl; // @synthesize segCtl=_segCtl;
@property(nonatomic) __weak UISwitch *uiSwitch1; // @synthesize uiSwitch1=_uiSwitch1;
- (void).cxx_destruct;
- (void)clickFeedBackLogButton:(id)arg1;
- (void)segmentedChange:(id)arg1;
- (void)clickClearDataButton:(id)arg1;
- (void)clickClearButton:(id)arg1;
- (void)clickCallJSButton:(id)arg1;
- (void)switchChangeed:(id)arg1;
- (void)clickRNButton:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)showLog;
- (void)log:(id)arg1;
- (id)JSONStr:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;

@end

