//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class IQYHttpRequestBase, NSString;
@protocol QYSkinTaskDelegate;

@interface QYSkinTask : NSObject
{
    _Bool _used;
    _Bool _isFree;
    int _type;
    int _status;
    id <QYSkinTaskDelegate> _delegate;
    NSString *_skinid;
    NSString *_name;
    double _downProgress;
    unsigned long long _downloadedSize;
    NSString *_zipPath;
    NSString *_path;
    NSString *_url;
    NSString *_upTime;
    NSString *_startTime;
    NSString *_endTime;
    NSString *_createVersion;
    IQYHttpRequestBase *_request;
}

@property(retain, nonatomic) IQYHttpRequestBase *request; // @synthesize request=_request;
@property(nonatomic) _Bool isFree; // @synthesize isFree=_isFree;
@property(copy, nonatomic) NSString *createVersion; // @synthesize createVersion=_createVersion;
@property(copy, nonatomic) NSString *endTime; // @synthesize endTime=_endTime;
@property(copy, nonatomic) NSString *startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *upTime; // @synthesize upTime=_upTime;
@property(nonatomic) _Bool used; // @synthesize used=_used;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *zipPath; // @synthesize zipPath=_zipPath;
@property(nonatomic) unsigned long long downloadedSize; // @synthesize downloadedSize=_downloadedSize;
@property(nonatomic) double downProgress; // @synthesize downProgress=_downProgress;
@property(nonatomic) int status; // @synthesize status=_status;
@property(nonatomic) int type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *skinid; // @synthesize skinid=_skinid;
@property(nonatomic) __weak id <QYSkinTaskDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)checkTaskStatus;
- (void)unZipTask:(id)arg1;
- (void)requstTask:(id)arg1;
- (void)doDownLoad;
- (void)rmSrcFiles;
- (void)notifyStatusChange;
- (void)setStatusAndNotification:(int)arg1;
- (_Bool)enabled;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)initWithUrl:(id)arg1 type:(int)arg2;
- (id)init;
- (void)dealloc;

@end

