//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (SCPureLayout)
- (id)sc_copyViewsOnly;
- (_Bool)sc_containsMinimumNumberOfViews:(unsigned long long)arg1;
- (id)sc_commonSuperviewOfViews;
- (id)sc_autoDistributeViewsAlongAxis:(long long)arg1 alignedTo:(long long)arg2 withFixedSize:(double)arg3 insetSpacing:(_Bool)arg4;
- (id)sc_autoDistributeViewsAlongAxis:(long long)arg1 alignedTo:(long long)arg2 withFixedSize:(double)arg3;
- (id)sc_autoDistributeViewsAlongAxis:(long long)arg1 alignedTo:(long long)arg2 withFixedSpacing:(double)arg3 insetSpacing:(_Bool)arg4 matchedSizes:(_Bool)arg5;
- (id)sc_autoDistributeViewsAlongAxis:(long long)arg1 alignedTo:(long long)arg2 withFixedSpacing:(double)arg3 insetSpacing:(_Bool)arg4;
- (id)sc_autoDistributeViewsAlongAxis:(long long)arg1 alignedTo:(long long)arg2 withFixedSpacing:(double)arg3;
- (id)sc_autoSetViewsDimensionsToSize:(struct CGSize)arg1;
- (id)sc_autoSetViewsDimension:(long long)arg1 toSize:(double)arg2;
- (id)sc_autoMatchViewsDimension:(long long)arg1;
- (id)sc_autoAlignViewsToAxis:(long long)arg1;
- (id)sc_autoAlignViewsToEdge:(long long)arg1;
- (id)sc_autoIdentifyConstraints:(id)arg1;
- (void)sc_autoRemoveConstraints;
- (void)sc_autoInstallConstraints;
@end

