//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SOHUCollectionViewDataSource-Protocol.h"

@class NSMutableArray, NSString, SOHUBaseCollectionReusableView;

@interface SOHUCollectionViewDataSource : NSObject <SOHUCollectionViewDataSource>
{
    NSMutableArray *_sections;
    SOHUBaseCollectionReusableView *_baseCollectionReusableView;
}

@property(retain, nonatomic) SOHUBaseCollectionReusableView *baseCollectionReusableView; // @synthesize baseCollectionReusableView=_baseCollectionReusableView;
@property(retain, nonatomic) NSMutableArray *sections; // @synthesize sections=_sections;
- (void).cxx_destruct;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)appendItem:(id)arg1;
- (void)clearAllItems;
- (Class)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 reusableViewClassForObject:(id)arg3;
- (Class)collectionView:(id)arg1 cellClassForObject:(id)arg2;
- (id)collectionView:(id)arg1 objectForSection:(long long)arg2;
- (id)collectionView:(id)arg1 objectForRowAtIndexPath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

