//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface PDMineWealthView : UIView
{
    UIView *_wealthValueView;
    UILabel *_wealthValueLabel;
    UILabel *_wealthUnitLabel;
    UILabel *_wealthNameLabel;
    UILabel *_bottomLabel;
}

@property(retain, nonatomic) UILabel *bottomLabel; // @synthesize bottomLabel=_bottomLabel;
@property(retain, nonatomic) UILabel *wealthNameLabel; // @synthesize wealthNameLabel=_wealthNameLabel;
@property(retain, nonatomic) UILabel *wealthUnitLabel; // @synthesize wealthUnitLabel=_wealthUnitLabel;
@property(retain, nonatomic) UILabel *wealthValueLabel; // @synthesize wealthValueLabel=_wealthValueLabel;
@property(retain, nonatomic) UIView *wealthValueView; // @synthesize wealthValueView=_wealthValueView;
- (void).cxx_destruct;
- (void)setMineWealthBottomViewShow:(_Bool)arg1;
- (void)setMineWealthValueUnit:(id)arg1;
- (void)setMineWealthValue:(id)arg1;
- (void)setMineWealthName:(id)arg1;
- (void)initAutoLayout;
- (id)init;

@end

