//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary;

@protocol IWXContactNtfHandlerService <NSObject>
- (void)handleFriendAcceptRefuseOnOtherPlatform:(NSDictionary *)arg1 offline:(_Bool)arg2;
- (void)handleFriendAcceptOKOnOtherPlatform:(NSDictionary *)arg1 offline:(_Bool)arg2;
- (void)handleFriendBeRemoved:(NSDictionary *)arg1 offline:(_Bool)arg2;
- (void)handleFriendDenyAdd:(NSDictionary *)arg1 offline:(_Bool)arg2;
- (void)handleFriendAddSuccess:(NSDictionary *)arg1 offline:(_Bool)arg2;
- (void)handleFriendNotifyServerAdd:(NSDictionary *)arg1 offline:(_Bool)arg2;
- (_Bool)handleFriendRecommenOperationTip:(NSArray *)arg1 bOffline:(_Bool)arg2;
- (void)handleFriendAcceptVerifyRequest:(NSDictionary *)arg1 offline:(_Bool)arg2;
- (void)handleFriendVerifyAddRquest:(NSDictionary *)arg1 offline:(_Bool)arg2;
@end

