//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary;
@protocol NMT_IDictationResult;

@protocol NMT_IDictationResult <NSObject>
@property(readonly, retain) NSDictionary *extraInformation;
@property(readonly, retain) NSArray *sentences;
- (_Bool)append:(id <NMT_IDictationResult>)arg1;
- (_Bool)merge:(id <NMT_IDictationResult>)arg1 startTime:(long long)arg2 endTime:(long long)arg3;
- (NSArray *)getAlternatives:(long long)arg1 endTime:(long long)arg2;
@end

