//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class JDYHealthCheckerEngine, UILabel;
@protocol JDYHeatherCheckerDelegate;

@interface JDYHealthCheckerCell : UITableViewCell
{
    id <JDYHeatherCheckerDelegate> _delegate;
    UILabel *_reason;
    UILabel *_advice;
    UILabel *_methodLabel;
    JDYHealthCheckerEngine *_checkerEngine;
}

+ (double)makeHeightForString:(id)arg1 leftMargin:(double)arg2 rightMargin:(double)arg3 fontSize:(double)arg4;
+ (struct CGSize)methodLabelSize:(id)arg1 leftMargin:(double)arg2 rightMargin:(double)arg3 fontSize:(double)arg4;
+ (double)heightForEngine:(id)arg1;
+ (id)heightCache;
@property(retain, nonatomic) JDYHealthCheckerEngine *checkerEngine; // @synthesize checkerEngine=_checkerEngine;
@property(retain, nonatomic) UILabel *methodLabel; // @synthesize methodLabel=_methodLabel;
@property(retain, nonatomic) UILabel *advice; // @synthesize advice=_advice;
@property(retain, nonatomic) UILabel *reason; // @synthesize reason=_reason;
@property(nonatomic) __weak id <JDYHeatherCheckerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)methodClick:(id)arg1;
- (void)configCellWithEngine:(id)arg1;
- (void)initSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

