//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WVWebView.h"

#import "QAPWebViewProtocol-Protocol.h"

@class NSString, UIViewController;
@protocol QAPPageViewControllerProtocol, QAPWebSchemeHandler, QAPWebViewDelegate;

@interface QAPWebView : WVWebView <QAPWebViewProtocol>
{
    UIViewController<QAPPageViewControllerProtocol> *_belongedViewController;
    id <QAPWebSchemeHandler> _schemeHandler;
}

@property(nonatomic) __weak id <QAPWebSchemeHandler> schemeHandler; // @synthesize schemeHandler=_schemeHandler;
@property(nonatomic) __weak UIViewController<QAPPageViewControllerProtocol> *belongedViewController; // @synthesize belongedViewController=_belongedViewController;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) __weak id <QAPWebViewDelegate> qapWebViewDelegate;
@property(readonly) Class superclass;

@end

