//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "ScreenLockDelegate-Protocol.h"

@class NSString, QNOALoginUICoordinator, QNUnifiedLoginUICoordinator;

@interface QNLoginCoordinator : NSObject <ScreenLockDelegate>
{
    CDUnknownBlockType _unlockSucceeded;
    CDUnknownBlockType _unlockFailed;
    QNUnifiedLoginUICoordinator *_unifiedLoginUICoordinator;
    QNOALoginUICoordinator *_oaLoginUICoordinator;
}

@property(retain, nonatomic) QNOALoginUICoordinator *oaLoginUICoordinator; // @synthesize oaLoginUICoordinator=_oaLoginUICoordinator;
@property(retain, nonatomic) QNUnifiedLoginUICoordinator *unifiedLoginUICoordinator; // @synthesize unifiedLoginUICoordinator=_unifiedLoginUICoordinator;
@property(copy, nonatomic) CDUnknownBlockType unlockFailed; // @synthesize unlockFailed=_unlockFailed;
@property(copy, nonatomic) CDUnknownBlockType unlockSucceeded; // @synthesize unlockSucceeded=_unlockSucceeded;
- (void).cxx_destruct;
- (void)presentDeviceScreenLockViewWithSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)openWorktable2SetupWithCompletionBlock:(CDUnknownBlockType)arg1 withUserID:(id)arg2 loginType:(long long)arg3;
- (void)openUnifiedLoginPageTransitionAnimated:(_Bool)arg1 pageAnimated:(_Bool)arg2;
- (void)openHistoryLoginPickerWithTransitionAnimated:(_Bool)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)openDeviceScreenLockViewWithTransitionAnimated:(_Bool)arg1 delegate:(id)arg2;
- (void)didTryToCancelScreenLockForModel:(long long)arg1;
- (void)didForgetPasscodeForMode:(long long)arg1;
- (void)didFailToUnlockForMode:(long long)arg1;
- (void)didUnlockSuccessfullyForMode:(long long)arg1;
- (void)didSetPasscode:(id)arg1 forMode:(long long)arg2;
- (_Bool)isPasscodeValid:(id)arg1 forMode:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

