//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class MHBillTraceModel, UIImageView, UILabel;

@interface MHBillCell : UITableViewCell
{
    MHBillTraceModel *_model;
    UILabel *_desLabel;
    UILabel *_timeLbl;
    UILabel *_stateLbl;
    UILabel *_amountLbl;
    UIImageView *_detailImgView;
}

@property(retain, nonatomic) UIImageView *detailImgView; // @synthesize detailImgView=_detailImgView;
@property(retain, nonatomic) UILabel *amountLbl; // @synthesize amountLbl=_amountLbl;
@property(retain, nonatomic) UILabel *stateLbl; // @synthesize stateLbl=_stateLbl;
@property(retain, nonatomic) UILabel *timeLbl; // @synthesize timeLbl=_timeLbl;
@property(retain, nonatomic) UILabel *desLabel; // @synthesize desLabel=_desLabel;
@property(retain, nonatomic) MHBillTraceModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)initSubviews;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

