//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FlightNavibarVC.h"

#import "FTabBarPtc-Protocol.h"
#import "StatisticsUELogProtocol-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class FTabBar, NSArray, NSMutableArray, NSNumber, NSString, UITableView;
@protocol FOrderDiscountInsurancePrt, FTTSXProductsDetailVCDelegate;

@interface FTTSXProductsDetailVC : FlightNavibarVC <UITableViewDelegate, UITableViewDataSource, FTabBarPtc, StatisticsUELogProtocol>
{
    id <FTTSXProductsDetailVCDelegate> _delegateInsurance;
    id <FOrderDiscountInsurancePrt> _delegate;
    NSString *_vcTitle;
    NSString *_abtest;
    long long _bookType;
    NSString *_fySelected;
    NSNumber *_limitCount;
    unsigned long long _selectedIndex;
    NSMutableArray *_auxProductsArray;
    UITableView *_tableView;
    FTabBar *_fTabBar;
    FTabBar *_noteTabBar;
    NSMutableArray *_productsArray;
    NSArray *_selectProductClassArray;
    unsigned long long _selectNoteIndex;
}

@property(nonatomic) unsigned long long selectNoteIndex; // @synthesize selectNoteIndex=_selectNoteIndex;
@property(retain, nonatomic) NSArray *selectProductClassArray; // @synthesize selectProductClassArray=_selectProductClassArray;
@property(retain, nonatomic) NSMutableArray *productsArray; // @synthesize productsArray=_productsArray;
@property(retain, nonatomic) FTabBar *noteTabBar; // @synthesize noteTabBar=_noteTabBar;
@property(retain, nonatomic) FTabBar *fTabBar; // @synthesize fTabBar=_fTabBar;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *auxProductsArray; // @synthesize auxProductsArray=_auxProductsArray;
@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(retain, nonatomic) NSNumber *limitCount; // @synthesize limitCount=_limitCount;
@property(retain, nonatomic) NSString *fySelected; // @synthesize fySelected=_fySelected;
@property(nonatomic) long long bookType; // @synthesize bookType=_bookType;
@property(retain, nonatomic) NSString *abtest; // @synthesize abtest=_abtest;
@property(retain, nonatomic) NSString *vcTitle; // @synthesize vcTitle=_vcTitle;
@property(nonatomic) __weak id <FOrderDiscountInsurancePrt> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <FTTSXProductsDetailVCDelegate> delegateInsurance; // @synthesize delegateInsurance=_delegateInsurance;
- (void).cxx_destruct;
- (id)getSelectedInsurancesForPsg:(id)arg1 insuranceList:(id)arg2;
- (long long)getAdultNoBuyCount:(id)arg1;
- (id)customValueWithSender:(id)arg1;
- (void)ftabBar:(id)arg1 didSelectItem:(id)arg2;
- (_Bool)canAllSelectedWithData:(id)arg1;
- (_Bool)canSelectedWithData:(id)arg1;
- (void)showTipAlertView;
- (long long)getSelectedCount:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)updateInsuranceSelectState;
- (void)vcWillPop;
- (void)cancelAction:(id)arg1;
- (void)confirmAction:(id)arg1;
- (_Bool)didSelectedALL:(id)arg1;
- (void)onClickAll:(id)arg1;
- (void)setupNoteTabBarTitles;
- (id)getSectionHeaderViewWithInsuranceListData:(id)arg1;
- (id)getPassengerViewAtIndex:(id)arg1;
- (void)reloadFoodView;
- (void)reloadHeaderView;
- (void)refreshTableViewSubs;
- (void)setupSegTitles;
- (void)setconfirmButtonEnable;
- (void)setupViewRootSubs:(id)arg1;
- (void)refreshAllSelectProductClassArraySelectedStatus;
- (void)refreshSelectProductClassArraySelectedStatus;
- (void)updateCurrentSelectProductClassData;
- (void)copyAuxProductsArray;
- (void)initProductModel;
- (void)viewDidLoad;
- (void)setupAuxProductsData:(id)arg1 selectedIndex:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

