//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class GCity;

@interface GCityService : NSObject
{
    GCity *_savedLocationCity;
    GCity *_userCity;
    GCity *_locationCity;
}

+ (id)sharedService;
@property(readonly, nonatomic) GCity *locationCity; // @synthesize locationCity=_locationCity;
@property(retain, nonatomic) GCity *userCity; // @synthesize userCity=_userCity;
- (void).cxx_destruct;
- (void)promptChangeCity:(id)arg1;
- (void)updateCityWithLandmark:(id)arg1;
- (void)updateLocation:(id)arg1 code:(id)arg2;
- (void)changeToCity:(id)arg1 code:(id)arg2;
- (void)changeToCity:(id)arg1;
- (void)load;
- (id)init;

@end

