//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HOrderFillRoomPreferRootSectionHelper.h"

@class NSArray;

@interface HOrderFillRoomPreferSelectListSectionHelper : HOrderFillRoomPreferRootSectionHelper
{
    NSArray *_listArray;
}

@property(retain, nonatomic) NSArray *listArray; // @synthesize listArray=_listArray;
- (void).cxx_destruct;
- (void)initHOrderFillFooterHelper;
- (void)initHOrderFillCellHelper;
- (void)initHOrderFillHeaderHelper;
- (void)initHOrderFillSectionHelper;
- (id)initSectionHelperWithDataModel:(id)arg1 identifier:(id)arg2 listArray:(id)arg3 andSectionTitle:(id)arg4;

@end

