//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCarCodingObject.h"

@class NSNumber, NSString, RYXTLAction, RYXTLCarRes;

@interface RYXTLHotLine : RCarCodingObject
{
    NSString *_name;
    NSString *_nameExtra;
    NSNumber *_type;
    NSNumber *_longitude;
    NSNumber *_latitude;
    NSNumber *_radius;
    NSString *_tips;
    NSString *_direction;
    NSString *_pic;
    RYXTLCarRes *_carRes;
    RYXTLAction *_action;
}

@property(retain, nonatomic) RYXTLAction *action; // @synthesize action=_action;
@property(retain, nonatomic) RYXTLCarRes *carRes; // @synthesize carRes=_carRes;
@property(retain, nonatomic) NSString *pic; // @synthesize pic=_pic;
@property(retain, nonatomic) NSString *direction; // @synthesize direction=_direction;
@property(retain, nonatomic) NSString *tips; // @synthesize tips=_tips;
@property(retain, nonatomic) NSNumber *radius; // @synthesize radius=_radius;
@property(retain, nonatomic) NSNumber *latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSNumber *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSNumber *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *nameExtra; // @synthesize nameExtra=_nameExtra;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;

@end

