//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface BUCommentSheetController : UIViewController
{
    _Bool _isReply;
    CDUnknownBlockType _dismissBlock;
}

@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(nonatomic) _Bool isReply; // @synthesize isReply=_isReply;
- (void).cxx_destruct;
- (void)clickButton:(id)arg1;
- (void)setupUI;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

