//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PPDataController.h"

@class NSDictionary, NSString, SKPaymentTransaction;
@protocol BUProductObject;

@interface BUVerifyDataController : PPDataController
{
    _Bool _isBusying;
    id <BUProductObject> _productObject;
    NSString *_responseString;
    NSDictionary *_userInfo;
    SKPaymentTransaction *_paymentTransaction;
}

@property(retain, nonatomic) SKPaymentTransaction *paymentTransaction; // @synthesize paymentTransaction=_paymentTransaction;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) NSString *responseString; // @synthesize responseString=_responseString;
@property(retain, nonatomic) id <BUProductObject> productObject; // @synthesize productObject=_productObject;
@property(nonatomic) _Bool isBusying; // @synthesize isBusying=_isBusying;
- (void).cxx_destruct;
- (void)requestWithReceipt:(id)arg1 userName:(id)arg2 token:(id)arg3 fromChannel:(id)arg4;
- (void)willStartRequest:(id)arg1;
- (id)requestMethod;

@end

