//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PHNormalViewController.h"

#import "NAModalSheetDelegate-Protocol.h"
#import "PCReactViewDelegate-Protocol.h"

@class NSString, PCReactView, PHChatViewController, UIButton, UIView, UIViewController;

@interface PHDetailSportsLiveContentController : PHNormalViewController <NAModalSheetDelegate, PCReactViewDelegate>
{
    _Bool _isChatViewShowing;
    NSString *_liveVideo;
    CDUnknownBlockType _backActionBlock;
    CDUnknownBlockType _changeCommentatorBlock;
    CDUnknownBlockType _startPlayBlock;
    CDUnknownBlockType _dismissPlayerBlock;
    NSString *_csid;
    NSString *_sectionID;
    PCReactView *_reactView;
    UIButton *_backButton;
    PHChatViewController *_chatViewController;
    UIViewController *_chatViewPackageController;
    UIView *_loadingView;
}

@property(nonatomic) _Bool isChatViewShowing; // @synthesize isChatViewShowing=_isChatViewShowing;
@property(retain, nonatomic) UIView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIViewController *chatViewPackageController; // @synthesize chatViewPackageController=_chatViewPackageController;
@property(retain, nonatomic) PHChatViewController *chatViewController; // @synthesize chatViewController=_chatViewController;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) PCReactView *reactView; // @synthesize reactView=_reactView;
@property(retain, nonatomic) NSString *sectionID; // @synthesize sectionID=_sectionID;
@property(retain, nonatomic) NSString *csid; // @synthesize csid=_csid;
@property(copy, nonatomic) CDUnknownBlockType dismissPlayerBlock; // @synthesize dismissPlayerBlock=_dismissPlayerBlock;
@property(copy, nonatomic) CDUnknownBlockType startPlayBlock; // @synthesize startPlayBlock=_startPlayBlock;
@property(copy, nonatomic) CDUnknownBlockType changeCommentatorBlock; // @synthesize changeCommentatorBlock=_changeCommentatorBlock;
@property(copy, nonatomic) CDUnknownBlockType backActionBlock; // @synthesize backActionBlock=_backActionBlock;
@property(retain, nonatomic) NSString *liveVideo; // @synthesize liveVideo=_liveVideo;
- (void).cxx_destruct;
- (void)hiddenLoadingView;
- (void)showLoadingView;
- (void)chatHeaderCloseAction:(id)arg1;
- (void)showChatView;
- (void)closePopup;
- (void)backAction:(id)arg1;
- (void)resetCsid:(id)arg1 sectionID:(id)arg2;
- (void)notifyReactView:(unsigned long long)arg1;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

