//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MPIPageViewController.h"

#import "MPIPageTabBarDataSource-Protocol.h"
#import "MPIPageViewControllerDataSource-Protocol.h"
#import "NSFetchedResultsControllerDelegate-Protocol.h"

@class MPIHomeTitleView, NSFetchedResultsController, NSNumber, NSString;

@interface MPILiveChannelPageViewController : MPIPageViewController <NSFetchedResultsControllerDelegate, MPIPageViewControllerDataSource, MPIPageTabBarDataSource>
{
    NSFetchedResultsController *_fetchedResultController;
    MPIHomeTitleView *_titleView;
    NSNumber *_initialSelectedChannelID;
}

+ (id)viewControllerWithChannelID:(id)arg1;
@property(retain, nonatomic) NSNumber *initialSelectedChannelID; // @synthesize initialSelectedChannelID=_initialSelectedChannelID;
@property(retain, nonatomic) MPIHomeTitleView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) NSFetchedResultsController *fetchedResultController; // @synthesize fetchedResultController=_fetchedResultController;
- (void).cxx_destruct;
- (id)cellForPageTabBarAtIndex:(long long)arg1 withRatioSignal:(id)arg2;
- (struct CGSize)sizeForPageTabBarCellAtIndex:(long long)arg1;
- (long long)numberOfPageTabs;
- (id)keyForViewControllerAtIndex:(long long)arg1;
- (id)viewControllerForIndex:(long long)arg1;
- (long long)numberOfViewControllers;
- (void)controllerDidChangeContent:(id)arg1;
- (void)setupTitleView;
- (void)requestChannelsIfNeeded;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

