//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSDictionary, NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface BJFollowsPostsNumModel : MTLModel <MTLJSONSerializing>
{
    NSNumber *_whichID;
    NSNumber *_postsNum;
    NSNumber *_followsNum;
    long long _type;
}

+ (id)typeJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSNumber *followsNum; // @synthesize followsNum=_followsNum;
@property(copy, nonatomic) NSNumber *postsNum; // @synthesize postsNum=_postsNum;
@property(copy, nonatomic) NSNumber *whichID; // @synthesize whichID=_whichID;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) NSDictionary *dictionaryValue;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

