//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CustomViewController.h"

#import "ForumUserInfoViewControllerDelegate-Protocol.h"
#import "ForumUserSelectViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class ASIHTTPRequest, ForumUserSelectView, NSString, UIButton, UIImageView, UILabel, UITableView, UIView;

__attribute__((visibility("hidden")))
@interface MyForumViewController : CustomViewController <UITableViewDataSource, UITableViewDelegate, ForumUserInfoViewControllerDelegate, ForumUserSelectViewDelegate>
{
    UIView *headerView;
    UIImageView *bgView;
    UIView *grayBgView;
    UIButton *headBtn;
    UIView *userIdentityIconView;
    int favCount;
    UIImageView *fansRedPoint;
    UIImageView *userHead;
    UILabel *userName;
    UILabel *topicNum;
    UILabel *commentNum;
    UILabel *guanzhuNum;
    UILabel *fansNum;
    UILabel *signatureLabel;
    UILabel *signature;
    UITableView *mainTable;
    ForumUserSelectView *sectionView;
    _Bool _isAutoConsultant;
    ASIHTTPRequest *_request;
    UIButton *_backBtn;
    UIImageView *_bgImageView;
}

@property(nonatomic) _Bool isAutoConsultant; // @synthesize isAutoConsultant=_isAutoConsultant;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) UIButton *backBtn; // @synthesize backBtn=_backBtn;
@property(retain, nonatomic) ASIHTTPRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (id)convertInteger:(long long)arg1;
- (void)resultGetTopicCountWithData:(id)arg1 error:(id)arg2 caller:(id)arg3;
- (void)logoutForumCallBack;
- (void)tableView:(id)arg1 configCellLineWithCell:(id)arg2 indexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)configCellForMyMessageSection:(id)arg1 forIndexPath:(id)arg2;
- (void)configCellForFavDraftSection:(id)arg1 forIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)clickSelectViewAtIndex:(long long)arg1;
- (void)clickOtherItem:(id)arg1;
- (void)clickDraft;
- (void)clickFav;
- (void)clickAutoConsultant;
- (void)clickFans;
- (void)clickGuanzhu;
- (void)clickComment;
- (void)clickTopic;
- (void)clickEdit;
- (void)clickHeader;
- (void)topicStatusNotification:(id)arg1;
- (void)refreshMessageNotify:(id)arg1;
- (void)refreshUIWithNotify:(id)arg1;
- (void)refreshRedPoint;
- (void)refreshUI;
- (void)fillProfileData;
- (void)initHeader;
- (void)initUI;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

