//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TWTRAuthenticationProvider.h"

@class TWTRAuthConfig, TWTRScribeSink, TwitterUserAPIClient, UIViewController;
@protocol TWTRAPIServiceConfig;

@interface TWTRWebAuthenticationProvider : TWTRAuthenticationProvider
{
    TwitterUserAPIClient *_twitterClient;
    TWTRAuthConfig *_authConfig;
    UIViewController *_viewController;
    TWTRScribeSink *_scribeSink;
    id <TWTRAPIServiceConfig> _apiServiceConfig;
}

@property(readonly, nonatomic) id <TWTRAPIServiceConfig> apiServiceConfig; // @synthesize apiServiceConfig=_apiServiceConfig;
@property(readonly, nonatomic) TWTRScribeSink *scribeSink; // @synthesize scribeSink=_scribeSink;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;
@property(readonly, nonatomic) TWTRAuthConfig *authConfig; // @synthesize authConfig=_authConfig;
@property(retain, nonatomic) TwitterUserAPIClient *twitterClient; // @synthesize twitterClient=_twitterClient;
- (void).cxx_destruct;
- (void)showWebView:(id)arg1 withViewController:(id)arg2;
- (void)requestAccessTokenWithAuthResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)obtainUserAuthorizationWithTempToken:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestTokenWithCompletion:(CDUnknownBlockType)arg1;
- (void)authenticateWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithAuthConfig:(id)arg1 apiServiceConfig:(id)arg2 viewController:(id)arg3 scribeSink:(id)arg4;

@end

