//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WebEngine.h"

@interface WebEngine (HMCOrder)
- (void)getHMCUserPhoneForceReload:(_Bool)arg1 responseBlock:(CDUnknownBlockType)arg2;
- (void)submitHMCOrderWithLoginType:(long long)arg1 token:(id)arg2 phoneno:(id)arg3 phonevcode:(id)arg4 serialid:(id)arg5 carid:(id)arg6 colorid:(id)arg7 colorname:(id)arg8 selltype:(id)arg9 getcardcityid:(id)arg10 cityid:(id)arg11 dealerids:(id)arg12 username:(id)arg13 pid:(id)arg14 haslicense:(id)arg15 lptype:(id)arg16 selltime:(id)arg17 remark:(id)arg18 responseBlock:(CDUnknownBlockType)arg19;
@end

