//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer, UIToolbar;

@interface QZEVRecordSpeedMenu : UIView
{
    CDUnknownBlockType _onRecordSpeedSelected;
    UIToolbar *_bgView;
    CAShapeLayer *_angleLayer;
}

+ (id)titles;
+ (id)values;
+ (id)titleForSpeed:(double)arg1;
@property(retain, nonatomic) CAShapeLayer *angleLayer; // @synthesize angleLayer=_angleLayer;
@property(retain, nonatomic) UIToolbar *bgView; // @synthesize bgView=_bgView;
@property(copy, nonatomic) CDUnknownBlockType onRecordSpeedSelected; // @synthesize onRecordSpeedSelected=_onRecordSpeedSelected;
- (void).cxx_destruct;
- (void)onMenuBtnTap:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 currentSpeed:(double)arg2;

@end

