//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QzoneBaseTableViewCell.h"

#import "UIScrollViewDelegate-Protocol.h"

@class MedalStatus, NSMutableArray, NSString, QZVisitMedalDayModel, QZVisitMedalStatusModel, UIImageView, UILabel, UIScrollView, UIView;

@interface QzoneVisitBannerCell : QzoneBaseTableViewCell <UIScrollViewDelegate>
{
    MedalStatus *_model;
    UIView *_bg;
    UILabel *_label;
    UIScrollView *_scrollView;
    UIImageView *_progressBar;
    UIImageView *_lineBar;
    UIImageView *_dotView;
    UIImageView *_dotHalfView;
    UIView *_textView;
    UILabel *_tipsView;
    QZVisitMedalStatusModel *_medalStatus;
    QZVisitMedalDayModel *_levelModel1;
    QZVisitMedalDayModel *_levelModel2;
    QZVisitMedalDayModel *_levelModel3;
    QZVisitMedalDayModel *_levelModel4;
    QZVisitMedalDayModel *_currentLevelModel;
    QZVisitMedalDayModel *_nextLevelModel;
    long long _lastPage;
    NSMutableArray *_dotArray;
    NSMutableArray *_dotHalfArray;
    UIView *_parent1;
    UIView *_parent2;
    UIView *_parent3;
    UIView *_parent4;
    NSString *_isPlaying1;
    NSString *_isPlaying2;
    NSString *_isPlaying3;
    NSString *_isPlaying4;
    UIView *_numParent;
}

@property(retain, nonatomic) UIView *numParent; // @synthesize numParent=_numParent;
@property(retain, nonatomic) NSString *isPlaying4; // @synthesize isPlaying4=_isPlaying4;
@property(retain, nonatomic) NSString *isPlaying3; // @synthesize isPlaying3=_isPlaying3;
@property(retain, nonatomic) NSString *isPlaying2; // @synthesize isPlaying2=_isPlaying2;
@property(retain, nonatomic) NSString *isPlaying1; // @synthesize isPlaying1=_isPlaying1;
@property(retain, nonatomic) UIView *parent4; // @synthesize parent4=_parent4;
@property(retain, nonatomic) UIView *parent3; // @synthesize parent3=_parent3;
@property(retain, nonatomic) UIView *parent2; // @synthesize parent2=_parent2;
@property(retain, nonatomic) UIView *parent1; // @synthesize parent1=_parent1;
@property(retain, nonatomic) NSMutableArray *dotHalfArray; // @synthesize dotHalfArray=_dotHalfArray;
@property(retain, nonatomic) NSMutableArray *dotArray; // @synthesize dotArray=_dotArray;
@property(nonatomic) long long lastPage; // @synthesize lastPage=_lastPage;
@property(retain, nonatomic) QZVisitMedalDayModel *nextLevelModel; // @synthesize nextLevelModel=_nextLevelModel;
@property(retain, nonatomic) QZVisitMedalDayModel *currentLevelModel; // @synthesize currentLevelModel=_currentLevelModel;
@property(retain, nonatomic) QZVisitMedalDayModel *levelModel4; // @synthesize levelModel4=_levelModel4;
@property(retain, nonatomic) QZVisitMedalDayModel *levelModel3; // @synthesize levelModel3=_levelModel3;
@property(retain, nonatomic) QZVisitMedalDayModel *levelModel2; // @synthesize levelModel2=_levelModel2;
@property(retain, nonatomic) QZVisitMedalDayModel *levelModel1; // @synthesize levelModel1=_levelModel1;
@property(retain, nonatomic) QZVisitMedalStatusModel *medalStatus; // @synthesize medalStatus=_medalStatus;
@property(retain, nonatomic) UILabel *tipsView; // @synthesize tipsView=_tipsView;
@property(retain, nonatomic) UIView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIImageView *dotHalfView; // @synthesize dotHalfView=_dotHalfView;
@property(retain, nonatomic) UIImageView *dotView; // @synthesize dotView=_dotView;
@property(retain, nonatomic) UIImageView *lineBar; // @synthesize lineBar=_lineBar;
@property(retain, nonatomic) UIImageView *progressBar; // @synthesize progressBar=_progressBar;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIView *bg; // @synthesize bg=_bg;
@property(retain, nonatomic) MedalStatus *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)addBgImage;
- (void)addTextAnimationFade;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)animationEnd:(long long)arg1;
- (void)popDownBubble:(id)arg1 part:(long long)arg2;
- (void)popUpBubble:(id)arg1 part:(long long)arg2;
- (void)addPopAnimation:(long long)arg1;
- (void)addLevelAnimation;
- (void)setIsPlayingEnd:(long long)arg1;
- (void)setIsPlaying:(long long)arg1;
- (id)getIsPlaying:(long long)arg1;
- (id)getParent:(long long)arg1;
- (void)addNumAnimation;
- (void)startProgressBarAnimation;
- (id)getNextLevel:(long long)arg1;
- (id)getLevel:(long long)arg1;
- (void)addStaticImage;
- (void)singleTap:(id)arg1;
- (void)show;
- (void)dealloc;
- (void)updateModel;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

