//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QzoneBaseBannerView.h"

#import "IQZUrlDownloaderDelegate-Protocol.h"

@class NSDictionary, NSString, UIImageView;

@interface QZoneBannerDecoView : QzoneBaseBannerView <IQZUrlDownloaderDelegate>
{
    UIImageView *_imageView;
    NSDictionary *_bannerInfo;
    long long _bannerType;
}

@property(nonatomic) long long bannerType; // @synthesize bannerType=_bannerType;
@property(retain, nonatomic) NSDictionary *bannerInfo; // @synthesize bannerInfo=_bannerInfo;
- (void).cxx_destruct;
- (void)requestFinished:(id)arg1;
- (void)reportBannerDecoExposure;
- (void)reportExpose;
- (void)clickBannerView;
- (void)createBannerView;
- (id)initWithFrame:(struct CGRect)arg1 bannerInfo:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

