//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, QMUIEasyTouchButton, UIImageView, UILabel;
@protocol FMSpamBannerViewDelegate;

@interface FMSpamBannerView : UIView
{
    NSString *_message;
    id <FMSpamBannerViewDelegate> _delegate;
    UILabel *_bannerLabel;
    UIImageView *_bannerImageView;
    QMUIEasyTouchButton *_bannerButton;
    UIView *_backgroundView;
}

@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) QMUIEasyTouchButton *bannerButton; // @synthesize bannerButton=_bannerButton;
@property(retain, nonatomic) UIImageView *bannerImageView; // @synthesize bannerImageView=_bannerImageView;
@property(retain, nonatomic) UILabel *bannerLabel; // @synthesize bannerLabel=_bannerLabel;
@property(nonatomic) __weak id <FMSpamBannerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (void)cancelButtonAction:(id)arg1;
- (void)layoutSubviews;
- (void)initSubView;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

