//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CDRunGroundMedalEntity, NSString;

@interface CDRunGroundOccupationEntity : NSObject
{
    long long _showType;
    NSString *_areaId;
    NSString *_areaName;
    NSString *_timeRange;
    long long _rangeId;
    NSString *_groupName;
    NSString *_imageUrl;
    CDRunGroundMedalEntity *_medal;
}

+ (id)modelContainerPropertyGenericClass;
+ (id)modelCustomPropertyMapper;
@property(retain, nonatomic) CDRunGroundMedalEntity *medal; // @synthesize medal=_medal;
@property(copy, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(copy, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(nonatomic) long long rangeId; // @synthesize rangeId=_rangeId;
@property(copy, nonatomic) NSString *timeRange; // @synthesize timeRange=_timeRange;
@property(copy, nonatomic) NSString *areaName; // @synthesize areaName=_areaName;
@property(copy, nonatomic) NSString *areaId; // @synthesize areaId=_areaId;
@property(nonatomic) long long showType; // @synthesize showType=_showType;
- (void).cxx_destruct;

@end

