//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSArray, NSString;

@interface CDVAvatarModel : NSObject <NSCopying, NSCoding>
{
    NSString *_portraitLargeURL;
    NSString *_portraitMiddleURL;
    NSString *_portraitTinyURL;
    NSString *_vLargeURL;
    NSString *_vMiddleURL;
    NSString *_vTinyURL;
    NSArray *_extensions;
}

+ (id)modelObjectWithDictionary:(id)arg1;
@property(retain, nonatomic) NSArray *extensions; // @synthesize extensions=_extensions;
@property(retain, nonatomic) NSString *vTinyURL; // @synthesize vTinyURL=_vTinyURL;
@property(retain, nonatomic) NSString *vMiddleURL; // @synthesize vMiddleURL=_vMiddleURL;
@property(retain, nonatomic) NSString *vLargeURL; // @synthesize vLargeURL=_vLargeURL;
@property(retain, nonatomic) NSString *portraitTinyURL; // @synthesize portraitTinyURL=_portraitTinyURL;
@property(retain, nonatomic) NSString *portraitMiddleURL; // @synthesize portraitMiddleURL=_portraitMiddleURL;
@property(retain, nonatomic) NSString *portraitLargeURL; // @synthesize portraitLargeURL=_portraitLargeURL;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;

@end

