//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GJLog : NSObject
{
    NSString *_GJLogFileName;
    NSString *_GJLogFilePath;
}

+ (void)startLogger;
+ (id)sharedInstance;
@property(retain, nonatomic) NSString *GJLogFilePath; // @synthesize GJLogFilePath=_GJLogFilePath;
@property(retain, nonatomic) NSString *GJLogFileName; // @synthesize GJLogFileName=_GJLogFileName;
- (void).cxx_destruct;
- (id)getGJLogFilePath;
- (id)getGJLogFileName;

@end

