//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CommonTradeAssetCell, HoldingStockItem, NSString;

@protocol WTAssertViewDelegate <NSObject>
- (void)addOrRemoveSelfSelStock:(HoldingStockItem *)arg1;
- (void)modifyCostPrice:(HoldingStockItem *)arg1;
- (void)selectActionWithCode:(NSString *)arg1 AndType:(long long)arg2 cellView:(CommonTradeAssetCell *)arg3;
@end

