//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSTimer, UIButton, UIColor, UIScrollView;

@interface ENNotificationBannerView : UIView
{
    NSTimer *_timer;
    long long _bannerIndex;
    NSArray *_titles;
    NSArray *_pathKeys;
    UIColor *_textColor;
    CDUnknownBlockType _bannerViewSelectIndex;
    CDUnknownBlockType _dimissBlock;
    UIScrollView *_scrollView;
    UIButton *_closeBtn;
    UIButton *_actionBtn;
}

+ (id)bannerViewOnSuperView:(id)arg1 height:(double)arg2;
@property(retain, nonatomic) UIButton *actionBtn; // @synthesize actionBtn=_actionBtn;
@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(copy, nonatomic) CDUnknownBlockType dimissBlock; // @synthesize dimissBlock=_dimissBlock;
@property(copy, nonatomic) CDUnknownBlockType bannerViewSelectIndex; // @synthesize bannerViewSelectIndex=_bannerViewSelectIndex;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
- (void).cxx_destruct;
- (void)_runBannerCricle;
- (void)_starTimer;
- (void)_selectBanner:(id)arg1;
- (void)_reloadSubViews;
- (void)_interface;
- (void)setCloseImage:(id)arg1;
- (void)stop;
- (void)start;
- (void)dismissWithAnimation:(CDUnknownBlockType)arg1;
- (void)dismiss;
- (void)showWithAnimation:(CDUnknownBlockType)arg1;
- (void)show;
- (void)bannerWithTitles:(id)arg1 pathKeys:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

