//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RPBBaseViewController.h"

@class NSDictionary, NSLayoutConstraint, NSString, UIButton, UITableView, UIView;

@interface RPWeekMonthRiseResultViewController : RPBBaseViewController
{
    NSDictionary *_resultInfo;
    NSString *_expectInterest;
    long long _rpplanType;
    UITableView *_mainScrollView;
    UIView *_backView;
    UIView *_progressView;
    NSLayoutConstraint *_progressViewHeight;
    UIButton *_completionButton;
}

@property(nonatomic) __weak UIButton *completionButton; // @synthesize completionButton=_completionButton;
@property(nonatomic) __weak NSLayoutConstraint *progressViewHeight; // @synthesize progressViewHeight=_progressViewHeight;
@property(nonatomic) __weak UIView *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) __weak UIView *backView; // @synthesize backView=_backView;
@property(nonatomic) __weak UITableView *mainScrollView; // @synthesize mainScrollView=_mainScrollView;
@property(nonatomic) long long rpplanType; // @synthesize rpplanType=_rpplanType;
@property(retain, nonatomic) NSString *expectInterest; // @synthesize expectInterest=_expectInterest;
@property(retain, nonatomic) NSDictionary *resultInfo; // @synthesize resultInfo=_resultInfo;
- (void).cxx_destruct;
- (void)myRegularViewController:(id)arg1;
- (void)popViewController;
- (void)_updataUI;
- (void)_interfaceUpdate;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

