//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AHBusinessFramework/AHRefreshTableViewController.h>

#import "ACAttentionBaseDelegate-Protocol.h"
#import "ACAttentionQuietPlayViewHandlerDelegate-Protocol.h"
#import "AHBottomMoreViewDelegate-Protocol.h"
#import "AHVideoPlayerStateDelegate-Protocol.h"

@class ACAttentionBaseModel, ACAttentionBubbleView, ACAttentionHomeHeaderView, ACAttentionQuietPlayViewHandler, NSMutableArray, NSString;
@protocol ACAttentionHomeVMDelegate;

@interface ACAttentionHomeVM : AHRefreshTableViewController <ACAttentionBaseDelegate, AHBottomMoreViewDelegate, AHVideoPlayerStateDelegate, ACAttentionQuietPlayViewHandlerDelegate>
{
    _Bool _isPullUpdate;
    _Bool _timerSwitch;
    _Bool _isCancelClick;
    _Bool _isClickBottom;
    _Bool _initFail;
    id <ACAttentionHomeVMDelegate> _delegate;
    ACAttentionHomeHeaderView *_headerView;
    NSMutableArray *_dataArray;
    long long _requstType;
    ACAttentionQuietPlayViewHandler *_quietPlayHandler;
    ACAttentionBaseModel *_tempData;
    long long _userid;
    ACAttentionBubbleView *_bubbleView;
    long long _isFirstRef;
}

@property(nonatomic) _Bool initFail; // @synthesize initFail=_initFail;
@property(nonatomic) _Bool isClickBottom; // @synthesize isClickBottom=_isClickBottom;
@property(nonatomic) _Bool isCancelClick; // @synthesize isCancelClick=_isCancelClick;
@property(nonatomic) long long isFirstRef; // @synthesize isFirstRef=_isFirstRef;
@property(retain, nonatomic) ACAttentionBubbleView *bubbleView; // @synthesize bubbleView=_bubbleView;
@property(nonatomic) long long userid; // @synthesize userid=_userid;
@property(retain, nonatomic) ACAttentionBaseModel *tempData; // @synthesize tempData=_tempData;
@property(retain, nonatomic) ACAttentionQuietPlayViewHandler *quietPlayHandler; // @synthesize quietPlayHandler=_quietPlayHandler;
@property(nonatomic) long long requstType; // @synthesize requstType=_requstType;
@property(nonatomic) _Bool timerSwitch; // @synthesize timerSwitch=_timerSwitch;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) ACAttentionHomeHeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) _Bool isPullUpdate; // @synthesize isPullUpdate=_isPullUpdate;
@property(nonatomic) __weak id <ACAttentionHomeVMDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (id)getDataByIndex:(long long)arg1;
- (long long)getPVTypeByMediaType:(long long)arg1;
- (void)stopFocus;
- (void)startFocus;
- (void)CJHVideoDetailPush:(id)arg1;
- (void)articleVideoDetailPush:(id)arg1;
- (void)didStartQuietPlay:(id)arg1;
- (void)autoQuietPlay;
- (void)stopPlayer;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrolllBeginDragging:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (long long)getPersonIDBy:(id)arg1 index:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)interestedHeaderViewDidSelected:(long long)arg1 model:(id)arg2;
- (void)updateInterstedData:(id)arg1 replaceModel:(id)arg2 uid:(long long)arg3 attentionState:(long long)arg4 selectIndex:(long long)arg5;
- (void)activityViewDidSelected:(long long)arg1 data:(id)arg2;
- (void)focusViewDidSelected:(long long)arg1 data:(id)arg2;
- (void)footerViewDidReply:(id)arg1;
- (void)footerViewLikeAction:(long long)arg1 data:(id)arg2;
- (void)centerViewDidVideo:(id)arg1 baseView:(id)arg2;
- (void)centerViewMultiplePicCardImgAnchor:(long long)arg1 selecetData:(id)arg2;
- (id)getMoreButtonDataArrayWithData:(id)arg1;
- (void)cancelPVBy:(id)arg1 andLassid:(long long)arg2 type2:(long long)arg3;
- (void)didSelectAtIndexPath:(id)arg1 MoreView:(id)arg2;
- (void)updateListAttentionStateBy:(long long)arg1 success:(_Bool)arg2;
- (void)userCenterAttention:(long long)arg1 followType:(id)arg2;
- (void)cjhAttention:(long long)arg1 followType:(id)arg2;
- (void)headerViewDidMoreView:(long long)arg1 data:(id)arg2;
- (void)headerViewDidHeadPortrait:(id)arg1;
- (void)cancelTimer;
- (void)startTimer;
- (void)requestBubble;
- (void)attentionVideoBack:(_Bool)arg1;
- (void)refWriteInit;
- (void)attentionListRequestSuccess:(_Bool)arg1 isCache:(_Bool)arg2;
- (void)pullUpdateTriggering:(id)arg1 type:(long long)arg2;
- (void)headerViewDidSelected:(long long)arg1;
- (void)initTableView;
- (void)listPvPost;
- (void)loginSuccess:(id)arg1;
- (void)upDateAttention:(id)arg1;
- (void)articleEdtorAttention:(id)arg1;
- (void)CJHAttention:(id)arg1;
- (void)handleFriend:(id)arg1;
- (void)initNotify;
- (void)AHScrollNavigationViewControllerContentEdgeInsetsDidChange:(struct UIEdgeInsets)arg1;
- (void)onTabbarButtonClick;
- (void)viewDidLoad;
- (void)transverseScrollViewWillDisapper;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

