//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class ACRecommendCarModel, UIButton, UIImageView, UILabel;
@protocol ACCarCellDelegate;

@interface ACCarCell : UICollectionViewCell
{
    long long _index;
    ACRecommendCarModel *_carModel;
    id <ACCarCellDelegate> _delegate;
    UIImageView *_imageView;
    UILabel *_title;
    UILabel *_price;
    UIButton *_leftBtn;
    UIButton *_rightBtn;
}

@property(retain, nonatomic) UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(retain, nonatomic) UIButton *leftBtn; // @synthesize leftBtn=_leftBtn;
@property(retain, nonatomic) UILabel *price; // @synthesize price=_price;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) __weak id <ACCarCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ACRecommendCarModel *carModel; // @synthesize carModel=_carModel;
@property(nonatomic) long long index; // @synthesize index=_index;
- (void).cxx_destruct;
- (void)callBackBy:(long long)arg1;
- (void)rightAction:(id)arg1;
- (void)leftAction:(id)arg1;
- (void)setMyFrame;
- (void)setMyData;
- (id)initWithFrame:(struct CGRect)arg1;

@end

