//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ACBaseModel, ACMFocusImg, ACTopicModel, ACVideoModel, AHIJKVideoPlayerController, AHNavigationController, NSArray, NSIndexPath, NSString;

@protocol ACNewEnergyViewManagerDelegate <NSObject>
- (void)postClickPVEventWithNewsData:(ACBaseModel *)arg1 index:(long long)arg2;
- (void)postPKTopicWithVoteID:(long long)arg1 type:(long long)arg2;
- (void)postRefreshClickPV;
- (void)postVideoPlayWithModel:(ACVideoModel *)arg1 PlayerController:(AHIJKVideoPlayerController *)arg2;
- (void)AHVideoPlayerController:(AHIJKVideoPlayerController *)arg1 videoPlayerState:(unsigned long long)arg2 videoModel:(ACVideoModel *)arg3;
- (void)pushToTopicDetailWithModel:(ACTopicModel *)arg1;
- (void)pushToVideoVCWithModel:(ACVideoModel *)arg1 playerVC:(AHIJKVideoPlayerController *)arg2;
- (void)jumpToH5WithScheme:(NSString *)arg1 index:(long long)arg2 model:(ACBaseModel *)arg3;
- (AHNavigationController *)getNaviVC;
- (NSArray *)vm_getVideoSourceArray;
- (_Bool)vm_getIsShowMore;
- (NSArray *)vm_getFocusArray;
- (NSArray *)vm_getListArray;
- (double)getScrollTitleBarHeight;
- (_Bool)getIsSubVC;
- (void)getVideoInfoWithVID:(NSString *)arg1;
- (void)getDataLoadLocalData:(_Bool)arg1 type:(long long)arg2;
- (void)didSelectCellAtIndex:(NSIndexPath *)arg1 model:(ACBaseModel *)arg2;
- (void)didSelectBannerAtIndex:(long long)arg1 model:(ACMFocusImg *)arg2;
- (void)pullRefresh;
- (void)postEventBegin;
@end

