//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AHNetworkingFramework/AHBaseService.h>

@class AHServerTimeStampManager, NSString;

@interface LiveShowNewReportService : AHBaseService
{
    AHServerTimeStampManager *_timeStampManager;
    _Bool _hasNewReport;
    NSString *_lastUpdateTime;
}

@property(retain, nonatomic) NSString *lastUpdateTime; // @synthesize lastUpdateTime=_lastUpdateTime;
@property(nonatomic) _Bool hasNewReport; // @synthesize hasNewReport=_hasNewReport;
- (void).cxx_destruct;
- (_Bool)parseJSON:(id)arg1;
- (void)requestDoesHasNewReportWithLastTime:(id)arg1;
- (id)init;

@end

