//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XCFTableViewCell.h"

@class XCFStarDisplayView;

@interface XCFStarDisplayCell : XCFTableViewCell
{
    float _rate;
    XCFStarDisplayView *_starView;
}

+ (double)height;
@property(nonatomic) float rate; // @synthesize rate=_rate;
@property(retain, nonatomic) XCFStarDisplayView *starView; // @synthesize starView=_starView;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

