//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SNSPostItem : NSObject
{
    NSString *_thumbnailURL;
    NSString *_originalURL;
    NSString *_content;
    NSString *_authorName;
    NSString *_avatarURL;
    NSString *_bigAvatarURL;
    NSString *_profileURL;
    long long _favoured;
    NSString *_createTime;
    long long _commented;
    NSString *_gender;
    NSString *_snsType;
    NSString *_pid;
    double _adaptedHeight;
}

+ (id)postItemWithDictionary:(id)arg1;
@property(nonatomic) double adaptedHeight; // @synthesize adaptedHeight=_adaptedHeight;
@property(retain, nonatomic) NSString *pid; // @synthesize pid=_pid;
@property(retain, nonatomic) NSString *snsType; // @synthesize snsType=_snsType;
@property(retain, nonatomic) NSString *gender; // @synthesize gender=_gender;
@property(nonatomic) long long commented; // @synthesize commented=_commented;
@property(retain, nonatomic) NSString *createTime; // @synthesize createTime=_createTime;
@property(nonatomic) long long favoured; // @synthesize favoured=_favoured;
@property(retain, nonatomic) NSString *profileURL; // @synthesize profileURL=_profileURL;
@property(retain, nonatomic) NSString *bigAvatarURL; // @synthesize bigAvatarURL=_bigAvatarURL;
@property(retain, nonatomic) NSString *avatarURL; // @synthesize avatarURL=_avatarURL;
@property(retain, nonatomic) NSString *authorName; // @synthesize authorName=_authorName;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *originalURL; // @synthesize originalURL=_originalURL;
@property(retain, nonatomic) NSString *thumbnailURL; // @synthesize thumbnailURL=_thumbnailURL;
- (void).cxx_destruct;

@end

