//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NIMutableTableViewModel.h"

@class AdvInterfaceDataHandler, LVPersonalInfomationCellObject, LVPictureCommentsModel, LVPictureDetailModel, LVPicturePraiseListCellObject, LVPictureTopImageCellObject, NSString;

@interface LVPictureDetailViewModel : NIMutableTableViewModel
{
    _Bool _commentDeleting;
    _Bool _hasMore;
    LVPictureDetailModel *_pictureDetailModel;
    LVPictureCommentsModel *_commentsModel;
    LVPictureTopImageCellObject *_topImgObject;
    LVPersonalInfomationCellObject *_personInfoObject;
    LVPicturePraiseListCellObject *_praiseListCellObject;
    long long _commentsTotalCount;
    NSString *_pageCursor;
    AdvInterfaceDataHandler *_advInterface;
}

@property(retain, nonatomic) AdvInterfaceDataHandler *advInterface; // @synthesize advInterface=_advInterface;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(copy, nonatomic) NSString *pageCursor; // @synthesize pageCursor=_pageCursor;
@property(nonatomic) _Bool commentDeleting; // @synthesize commentDeleting=_commentDeleting;
@property(nonatomic) long long commentsTotalCount; // @synthesize commentsTotalCount=_commentsTotalCount;
@property(retain, nonatomic) LVPicturePraiseListCellObject *praiseListCellObject; // @synthesize praiseListCellObject=_praiseListCellObject;
@property(retain, nonatomic) LVPersonalInfomationCellObject *personInfoObject; // @synthesize personInfoObject=_personInfoObject;
@property(retain, nonatomic) LVPictureTopImageCellObject *topImgObject; // @synthesize topImgObject=_topImgObject;
@property(retain, nonatomic) LVPictureCommentsModel *commentsModel; // @synthesize commentsModel=_commentsModel;
@property(retain, nonatomic) LVPictureDetailModel *pictureDetailModel; // @synthesize pictureDetailModel=_pictureDetailModel;
- (void).cxx_destruct;
- (void)cancelFavoritePictureWithPictureID:(id)arg1 respose:(CDUnknownBlockType)arg2;
- (void)favoritePictureWithPictureID:(id)arg1 respose:(CDUnknownBlockType)arg2;
- (void)postUnFollowSnsID:(id)arg1 completed:(CDUnknownBlockType)arg2;
- (void)postFollowSnsID:(id)arg1 completed:(CDUnknownBlockType)arg2;
- (void)postPictureCommentPraiseWithPictureID:(id)arg1 commnetID:(id)arg2 completed:(CDUnknownBlockType)arg3;
- (void)postPicturePraiseWithPictureID:(id)arg1 completed:(CDUnknownBlockType)arg2;
- (id)p_replyCommentCellObjectWithModel:(id)arg1;
- (id)p_commentCellObjectWithModel:(id)arg1;
- (void)postDeletePictureWithPictureID:(id)arg1 response:(CDUnknownBlockType)arg2;
- (void)postDeleteCommentWithPictureID:(id)arg1 commnetID:(id)arg2 replyID:(id)arg3 completed:(CDUnknownBlockType)arg4;
- (void)postReplyComment:(id)arg1 pictureID:(id)arg2 commentID:(id)arg3 replyID:(id)arg4 commentObject:(id)arg5 cityID:(id)arg6 cityName:(id)arg7 response:(CDUnknownBlockType)arg8;
- (void)requestPictureCommentWithPictureID:(id)arg1 pageAction:(unsigned long long)arg2 response:(CDUnknownBlockType)arg3;
- (void)requestPictureDetailWithPictureID:(id)arg1 isRefresh:(_Bool)arg2 response:(CDUnknownBlockType)arg3;
- (void)requestPictureDetailWithPictureID:(id)arg1 response:(CDUnknownBlockType)arg2;
- (id)initWithDelegate:(id)arg1;

@end

