//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NTESNBNotifierView;

@interface NTESNBNotifier : NSObject
{
    NTESNBNotifierView *_popUp;
}

+ (id)sharedNotifier;
- (void).cxx_destruct;
- (void)showUpNotifyLayer:(id)arg1;
- (void)tryToShowRemoteNotifier:(id)arg1;
- (_Bool)shouldStopPopup:(id)arg1;
- (_Bool)isBetween:(id)arg1 and:(id)arg2;
- (_Bool)isVersionShowed:(long long)arg1;
- (_Bool)isApprovedNotify:(id)arg1;

@end

