//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSLayoutConstraint, NTESNBALAvatarView, NTESNBALLiveMessageView, NTESNBChatRoomLog, NTESNBLiveRoomLog, UIImageView, UIView;

@interface NTESNBALLiveTableViewCell : UITableViewCell
{
    double otherHeadLeading;
    double myHeadTrailing;
    double replyBottom;
    double quoteViewHeight;
    double myheadWidth;
    double otherHeadWidth;
    double otherHeadTrailing;
    double myHeadLeading;
    double realyLeading;
    double realyTrailing;
    double replyLeading;
    double replyTrailing;
    double bgImgBottom;
    _Bool isStampImgHidden;
    UIImageView *_bgImgView;
    UIView *_otherHeadViewContainer;
    UIView *_myHeadViewContainer;
    UIView *_replyContentViewContainer;
    UIView *_realyContentViewContainer;
    NTESNBALAvatarView *_otherHeadView;
    NTESNBALAvatarView *_myHeadView;
    NTESNBALLiveMessageView *_realyContentView;
    NTESNBALLiveMessageView *_replyContentView;
    NTESNBLiveRoomLog *_roomLog;
    NTESNBChatRoomLog *_chatLog;
    NSLayoutConstraint *_myHeadLeadingConstraint;
    NSLayoutConstraint *_otherHeadTrailingConstraint;
    NSLayoutConstraint *_replyHeightConstraint;
    NSLayoutConstraint *_otherHeadWidthConstraint;
    NSLayoutConstraint *_myHeadWidthConstraint;
    NSLayoutConstraint *_otherHeadleadingConstraint;
    NSLayoutConstraint *_realyLeadingConstraint;
    NSLayoutConstraint *_realyTrailingConstraint;
    NSLayoutConstraint *_replyBottomConstraint;
    NSLayoutConstraint *_replyTopConstraint;
    NSLayoutConstraint *_replyTrailingConstraint;
    NSLayoutConstraint *_replyLeadingConstraint;
    NSLayoutConstraint *_myHeadTrailingConstraint;
    NSLayoutConstraint *_bgImgViewBottomConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *bgImgViewBottomConstraint; // @synthesize bgImgViewBottomConstraint=_bgImgViewBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *myHeadTrailingConstraint; // @synthesize myHeadTrailingConstraint=_myHeadTrailingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *replyLeadingConstraint; // @synthesize replyLeadingConstraint=_replyLeadingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *replyTrailingConstraint; // @synthesize replyTrailingConstraint=_replyTrailingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *replyTopConstraint; // @synthesize replyTopConstraint=_replyTopConstraint;
@property(nonatomic) __weak NSLayoutConstraint *replyBottomConstraint; // @synthesize replyBottomConstraint=_replyBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *realyTrailingConstraint; // @synthesize realyTrailingConstraint=_realyTrailingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *realyLeadingConstraint; // @synthesize realyLeadingConstraint=_realyLeadingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *otherHeadleadingConstraint; // @synthesize otherHeadleadingConstraint=_otherHeadleadingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *myHeadWidthConstraint; // @synthesize myHeadWidthConstraint=_myHeadWidthConstraint;
@property(nonatomic) __weak NSLayoutConstraint *otherHeadWidthConstraint; // @synthesize otherHeadWidthConstraint=_otherHeadWidthConstraint;
@property(nonatomic) __weak NSLayoutConstraint *replyHeightConstraint; // @synthesize replyHeightConstraint=_replyHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *otherHeadTrailingConstraint; // @synthesize otherHeadTrailingConstraint=_otherHeadTrailingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *myHeadLeadingConstraint; // @synthesize myHeadLeadingConstraint=_myHeadLeadingConstraint;
@property(retain, nonatomic) NTESNBChatRoomLog *chatLog; // @synthesize chatLog=_chatLog;
@property(retain, nonatomic) NTESNBLiveRoomLog *roomLog; // @synthesize roomLog=_roomLog;
@property(retain, nonatomic) NTESNBALLiveMessageView *replyContentView; // @synthesize replyContentView=_replyContentView;
@property(retain, nonatomic) NTESNBALLiveMessageView *realyContentView; // @synthesize realyContentView=_realyContentView;
@property(retain, nonatomic) NTESNBALAvatarView *myHeadView; // @synthesize myHeadView=_myHeadView;
@property(retain, nonatomic) NTESNBALAvatarView *otherHeadView; // @synthesize otherHeadView=_otherHeadView;
@property(nonatomic) __weak UIView *realyContentViewContainer; // @synthesize realyContentViewContainer=_realyContentViewContainer;
@property(nonatomic) __weak UIView *replyContentViewContainer; // @synthesize replyContentViewContainer=_replyContentViewContainer;
@property(nonatomic) __weak UIView *myHeadViewContainer; // @synthesize myHeadViewContainer=_myHeadViewContainer;
@property(nonatomic) __weak UIView *otherHeadViewContainer; // @synthesize otherHeadViewContainer=_otherHeadViewContainer;
@property(nonatomic) __weak UIImageView *bgImgView; // @synthesize bgImgView=_bgImgView;
- (void).cxx_destruct;
- (id)quoteData;
- (void)markMe:(_Bool)arg1;
- (void)layoutSubviews;
- (void)refreshViweWithChatModel:(id)arg1;
- (void)markNew:(_Bool)arg1;
- (id)messageBgImgName:(id)arg1 capInsets:(struct UIEdgeInsets)arg2;
- (void)setSectionLast;
- (void)setAutoLayout;
- (void)resetAutoLayoutWithChatModel:(id)arg1;
- (void)resetAutoLayoutWithModel:(id)arg1;
- (void)resetAutoLayoutValue;
- (double)getReplyContentWidth;
- (double)getRealyContentWidth;
- (void)refreshViweWithRoomLogModel:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

