//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC15AirbnbItinerary18ItineraryFormatter : SwiftObject
{
    // Error parsing type: , name: separator
    // Error parsing type: , name: dateIntervalFormatter.storage
    // Error parsing type: , name: sectionHeaderFormatter.storage
    // Error parsing type: , name: timeFormatter.storage
    // Error parsing type: , name: weekdayFormatter.storage
}

@end

