//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DARecycledScrollView, DARecycledTileView;

@protocol DARecycledScrollViewDataSource <NSObject>
- (double)widthForTileAtIndex:(long long)arg1 scrollView:(DARecycledScrollView *)arg2;
- (DARecycledTileView *)tileViewForRecycledScrollView:(DARecycledScrollView *)arg1;
- (void)recycledScrollView:(DARecycledScrollView *)arg1 configureTileView:(DARecycledTileView *)arg2 forIndex:(unsigned long long)arg3;
- (DARecycledTileView *)recycledScrollView:(DARecycledScrollView *)arg1 reuseTileView:(DARecycledTileView *)arg2 forIndex:(unsigned long long)arg3;
- (long long)numberOfTilesInScrollView:(DARecycledScrollView *)arg1;
@end

