//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UIView;

@interface EnstyleFilterCell : UITableViewCell
{
    UIImageView *_filterImageView;
    UIImageView *_flagImageView;
    UIView *_selectview;
    UILabel *_filterNameLab;
}

@property(retain, nonatomic) UILabel *filterNameLab; // @synthesize filterNameLab=_filterNameLab;
@property(retain, nonatomic) UIView *selectview; // @synthesize selectview=_selectview;
@property(retain, nonatomic) UIImageView *flagImageView; // @synthesize flagImageView=_flagImageView;
@property(retain, nonatomic) UIImageView *filterImageView; // @synthesize filterImageView=_filterImageView;
- (void)awakeFromNib;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setAppPayGroup:(id)arg1 backgroundColor:(id)arg2 selectedColor:(id)arg3;
- (void)initWiew:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

