//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UILabel, UISlider, ZMLImagePlayer;

@interface PreviewImageViewController : UIViewController
{
    _Bool _isPlayerPlaying;
    ZMLImagePlayer *_player;
    UISlider *_timeSlider;
    UILabel *_currentTimeLabel;
}

@property(retain, nonatomic) UILabel *currentTimeLabel; // @synthesize currentTimeLabel=_currentTimeLabel;
@property(retain, nonatomic) UISlider *timeSlider; // @synthesize timeSlider=_timeSlider;
@property(retain, nonatomic) ZMLImagePlayer *player; // @synthesize player=_player;
@property(nonatomic) _Bool isPlayerPlaying; // @synthesize isPlayerPlaying=_isPlayerPlaying;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)timeValueChanged:(id)arg1;
- (void)playButtonClick:(id)arg1;
- (void)layoutPlayer;
- (void)viewDidLoad;

@end

