//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class LMGroupCellModel, NSMutableArray;
@protocol LMGroupCellDelegate;

@interface LMGroupCell : UITableViewCell
{
    LMGroupCellModel *_model;
    NSMutableArray *_itemViews;
    id <LMGroupCellDelegate> _delegate;
    long long _columnNum;
    unsigned long long _numberOfItemForRow;
}

@property(nonatomic) unsigned long long numberOfItemForRow; // @synthesize numberOfItemForRow=_numberOfItemForRow;
@property(nonatomic) long long columnNum; // @synthesize columnNum=_columnNum;
@property(nonatomic) __weak id <LMGroupCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSMutableArray *itemViews; // @synthesize itemViews=_itemViews;
@property(retain, nonatomic) LMGroupCellModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (struct CGSize)caculteItemViewSize:(id)arg1;
- (void)createItemViews;
- (void)updateItemViews;
- (void)onTouchItemView:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (_Bool)isAccessibilityElement;

@end

