//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LMBaseRequest.h"

@interface LMListenBookPriceApi : LMBaseRequest
{
    long long _entityType;
    long long _entityId;
}

@property(nonatomic) long long entityId; // @synthesize entityId=_entityId;
@property(nonatomic) long long entityType; // @synthesize entityType=_entityType;
- (id)requestParams;
- (id)requestUrl;
- (id)initWithParserClass:(Class)arg1;
- (id)init;

@end

