//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface LMNewPageControl : UIView
{
    long long _numberOfPages;
    long long _currentPage;
    UIView *_contentView;
    UIView *_rectView;
    UILabel *_pageNumLabel;
}

@property(retain, nonatomic) UILabel *pageNumLabel; // @synthesize pageNumLabel=_pageNumLabel;
@property(retain, nonatomic) UIView *rectView; // @synthesize rectView=_rectView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) long long numberOfPages; // @synthesize numberOfPages=_numberOfPages;
- (void).cxx_destruct;
- (double)caculateCenterXOffset;
- (void)updateContentViewCenterX;
- (void)setupPageNumLabel;
- (void)setupRectView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

