//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSString;

@interface AliDetailArchitecturePage : TBJSONModel
{
    NSString *_items;
    NSString *_lastPage;
    NSString *_page;
}

@property(retain, nonatomic) NSString *page; // @synthesize page=_page;
@property(retain, nonatomic) NSString *lastPage; // @synthesize lastPage=_lastPage;
@property(retain, nonatomic) NSString *items; // @synthesize items=_items;
- (void).cxx_destruct;

@end

