//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class AliDetailModel, AliDetailRequest, NSDictionary, NSLock, NSString;

@interface AliTradeSkuEngine : NSObject
{
    _Bool _isDetailCalled;
    AliDetailModel *_detailModel;
    AliDetailRequest *_beforeCartApiRequest;
    AliDetailRequest *_beforeBuyApiRequest;
    NSDictionary *_extraBuildOrderParams;
    NSDictionary *_extraBuyParams;
    NSString *_proxyParams;
    NSLock *_buyLock;
    NSLock *_cartLock;
    long long _quantity;
    CDUnknownBlockType _buyParamsCompleteHandler;
    CDUnknownBlockType _addCartParamsCompleteHandler;
}

+ (void)addCart:(long long)arg1 detailModel:(id)arg2;
+ (id)createCartParams:(long long)arg1 detailModel:(id)arg2 successHandler:(CDUnknownBlockType)arg3 failureHandler:(CDUnknownBlockType)arg4;
+ (id)buildOrderUrl:(long long)arg1 detailModel:(id)arg2 successHandler:(CDUnknownBlockType)arg3 failureHandler:(CDUnknownBlockType)arg4;
+ (id)buildOrderUrl:(id)arg1;
+ (id)createBuyParams:(long long)arg1 detailModel:(id)arg2 successHandler:(CDUnknownBlockType)arg3 failureHandler:(CDUnknownBlockType)arg4;
@property(copy, nonatomic) CDUnknownBlockType addCartParamsCompleteHandler; // @synthesize addCartParamsCompleteHandler=_addCartParamsCompleteHandler;
@property(copy, nonatomic) CDUnknownBlockType buyParamsCompleteHandler; // @synthesize buyParamsCompleteHandler=_buyParamsCompleteHandler;
@property(nonatomic) long long quantity; // @synthesize quantity=_quantity;
@property(retain, nonatomic) NSLock *cartLock; // @synthesize cartLock=_cartLock;
@property(retain, nonatomic) NSLock *buyLock; // @synthesize buyLock=_buyLock;
@property(retain, nonatomic) NSString *proxyParams; // @synthesize proxyParams=_proxyParams;
@property(retain, nonatomic) NSDictionary *extraBuyParams; // @synthesize extraBuyParams=_extraBuyParams;
@property(retain, nonatomic) NSDictionary *extraBuildOrderParams; // @synthesize extraBuildOrderParams=_extraBuildOrderParams;
@property(nonatomic) _Bool isDetailCalled; // @synthesize isDetailCalled=_isDetailCalled;
@property(retain, nonatomic) AliDetailRequest *beforeBuyApiRequest; // @synthesize beforeBuyApiRequest=_beforeBuyApiRequest;
@property(retain, nonatomic) AliDetailRequest *beforeCartApiRequest; // @synthesize beforeCartApiRequest=_beforeCartApiRequest;
@property(retain, nonatomic) AliDetailModel *detailModel; // @synthesize detailModel=_detailModel;
- (void).cxx_destruct;
- (_Bool)checkContractAddToCart;
- (void)showAlert:(int)arg1;
- (void)addCommonParamsToExtraParams:(id)arg1;
- (void)setContractPhoneSelectInfo:(id)arg1;
- (void)setInstallmentInfo:(id)arg1;
- (id)createFullAddCartParams;
- (void)executeCreateAddCartParams;
- (id)createFullBuyParams;
- (void)executeCreateOrderParams;
- (void)addOrderExtraParams:(id)arg1;
- (void)setSkuComponentValue:(id)arg1 components:(id)arg2;
- (id)createBasicBuyParams;
- (id)createISVCustomRequestParams:(id)arg1;
- (void)executeAddCart:(long long)arg1 step:(long long)arg2 extraParams:(id)arg3;
- (void)createFullAddCartParams:(long long)arg1 step:(long long)arg2 completeHandler:(CDUnknownBlockType)arg3;
- (id)createFullAddCartParams:(long long)arg1 step:(long long)arg2 extraParams:(id)arg3;
- (id)createAddCartExtraParams;
- (void)createAddCartExtraParamsWithcompleteHandler:(CDUnknownBlockType)arg1;
- (id)buildOrderUrl:(id)arg1;
- (id)createBuyParams:(long long)arg1;
- (void)createBuyParams:(long long)arg1 completeHandler:(CDUnknownBlockType)arg2;
- (void)dealloc;

@end

