//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TMRateBaseCell.h"

@class NSMutableArray;

@interface TMAppendRatedPhotoCell : TMRateBaseCell
{
    NSMutableArray *_photos;
}

@property(retain, nonatomic) NSMutableArray *photos; // @synthesize photos=_photos;
- (void).cxx_destruct;
- (void)imageDownloadFinished:(id)arg1 info:(id)arg2;
- (void)setThumbnails:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

