//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBMTOPBaseRequest.h"

@class NSString;

@interface TMArbitraryDoorRequest : TBMTOPBaseRequest
{
    NSString *_pageCode;
    NSString *_clazzName;
    NSString *_extraParam;
}

@property(copy, nonatomic) NSString *extraParam; // @synthesize extraParam=_extraParam;
@property(copy, nonatomic) NSString *clazzName; // @synthesize clazzName=_clazzName;
@property(copy, nonatomic) NSString *pageCode; // @synthesize pageCode=_pageCode;
- (void).cxx_destruct;
- (id)init;

@end

