//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, TBMPBPlayerOptions, TBMPBPlayerView, UIImageView, VideoOperater;

@interface TMMediaContainer : UIView
{
    _Bool _isRefreshUrl;
    NSString *_videoUrl;
    NSString *_coverUrl;
    unsigned long long _contentType;
    VideoOperater *_videoOperater;
    TBMPBPlayerView *_playerView;
    TBMPBPlayerOptions *_options;
    UIImageView *_imageView;
}

+ (id)shareInstance;
@property(nonatomic) _Bool isRefreshUrl; // @synthesize isRefreshUrl=_isRefreshUrl;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) TBMPBPlayerOptions *options; // @synthesize options=_options;
@property(retain, nonatomic) TBMPBPlayerView *playerView; // @synthesize playerView=_playerView;
@property(retain, nonatomic) VideoOperater *videoOperater; // @synthesize videoOperater=_videoOperater;
@property(nonatomic) unsigned long long contentType; // @synthesize contentType=_contentType;
@property(retain, nonatomic) NSString *coverUrl; // @synthesize coverUrl=_coverUrl;
@property(retain, nonatomic) NSString *videoUrl; // @synthesize videoUrl=_videoUrl;
- (void).cxx_destruct;
- (id)md5:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)playEnd;
- (void)playTriggered;
- (id)init;

@end

