//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface TMPlayerAdvanceView : UIView
{
    UILabel *_rightLbl;
    UILabel *_titleLbl;
    UILabel *_advanceTimeLbl;
    UIImageView *_bannerImageView;
}

@property(retain, nonatomic) UIImageView *bannerImageView; // @synthesize bannerImageView=_bannerImageView;
@property(retain, nonatomic) UILabel *advanceTimeLbl; // @synthesize advanceTimeLbl=_advanceTimeLbl;
@property(retain, nonatomic) UILabel *titleLbl; // @synthesize titleLbl=_titleLbl;
@property(retain, nonatomic) UILabel *rightLbl; // @synthesize rightLbl=_rightLbl;
- (void).cxx_destruct;
- (void)applyTMLiveSkinStyle:(id)arg1;
- (void)setup;
- (void)setChannelModel:(id)arg1;
- (void)layoutSubviews;
- (id)init;

@end

