//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "TBSDKServerDelegate-Protocol.h"
#import "WXModuleProtocol-Protocol.h"

@class NSString, WXSDKInstance;

@interface TMSWeexCacheMtopEvent : NSObject <TBSDKServerDelegate, WXModuleProtocol>
{
    WXSDKInstance *weexInstance;
    CDUnknownBlockType _success;
    CDUnknownBlockType _failed;
    NSString *_cacheKey;
}

+ (void)cleanCurrentCache;
+ (id)cache;
+ (void)doWhenServicesInited:(id)arg1;
+ (id)wx_export_method_26;
@property(copy, nonatomic) NSString *cacheKey; // @synthesize cacheKey=_cacheKey;
@property(copy, nonatomic) CDUnknownBlockType failed; // @synthesize failed=_failed;
@property(copy, nonatomic) CDUnknownBlockType success; // @synthesize success=_success;
@property(nonatomic) __weak WXSDKInstance *weexInstance; // @synthesize weexInstance;
- (void).cxx_destruct;
- (void)requestFailed:(id)arg1;
- (void)requestSuccess:(id)arg1;
- (void)request:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)pasreFromJSONString:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

