//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UILabel;

@interface BOOKGrouponBookingInfoCell : UITableViewCell
{
    UILabel *_countLabel;
    UIButton *_countButton;
    UILabel *_timeLabel;
    UIButton *_timeButton;
    UILabel *_dateLabel;
    UIButton *_dateButton;
}

@property(nonatomic) UIButton *dateButton; // @synthesize dateButton=_dateButton;
@property(nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(nonatomic) UIButton *timeButton; // @synthesize timeButton=_timeButton;
@property(nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) UIButton *countButton; // @synthesize countButton=_countButton;
@property(nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

