//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NVBaseModule.h"

@class NSDate, NVModelBaseMovieTicketOrder, TGBaseCell, UIImageView, UILabel;

@interface MOVIEPayOrderHintModule : NVBaseModule
{
    TGBaseCell *_cellForCountDown;
    UILabel *_labelForCountDown;
    UIImageView *_timeImageView;
    NVModelBaseMovieTicketOrder *_movieTicketOrder;
    NSDate *_resignDate;
    long long _resignSeconds;
}

@property(nonatomic) long long resignSeconds; // @synthesize resignSeconds=_resignSeconds;
@property(retain, nonatomic) NSDate *resignDate; // @synthesize resignDate=_resignDate;
@property(nonatomic) __weak NVModelBaseMovieTicketOrder *movieTicketOrder; // @synthesize movieTicketOrder=_movieTicketOrder;
@property(retain, nonatomic) UIImageView *timeImageView; // @synthesize timeImageView=_timeImageView;
@property(retain, nonatomic) UILabel *labelForCountDown; // @synthesize labelForCountDown=_labelForCountDown;
@property(retain, nonatomic) TGBaseCell *cellForCountDown; // @synthesize cellForCountDown=_cellForCountDown;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)payTimeout;
- (void)updateCountDown;
- (id)getCountDownText:(long long)arg1;
- (id)timeOutSignal;
- (void)updateCells;
- (void)makeupCells;
- (_Bool)shouldShow;
- (void)setupModule;

@end

