//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NVBaseModule.h"

#import "NVTextViewDelegate-Protocol.h"

@class MOVIEAddCommentWriteCommentCell, NSString;

@interface MOVIEAddCommentWriteCommentModule : NVBaseModule <NVTextViewDelegate>
{
    MOVIEAddCommentWriteCommentCell *_commentCell;
    NSString *_commentPlaceHolder;
    long long _reviewBodyMinCount;
    long long _reviewBodyMaxCount;
    long long _currentPhotoCount;
    NSString *_textMessage;
    NSString *_lastTextMessage;
}

@property(copy, nonatomic) NSString *lastTextMessage; // @synthesize lastTextMessage=_lastTextMessage;
@property(copy, nonatomic) NSString *textMessage; // @synthesize textMessage=_textMessage;
@property(nonatomic) long long currentPhotoCount; // @synthesize currentPhotoCount=_currentPhotoCount;
@property(nonatomic) long long reviewBodyMaxCount; // @synthesize reviewBodyMaxCount=_reviewBodyMaxCount;
@property(nonatomic) long long reviewBodyMinCount; // @synthesize reviewBodyMinCount=_reviewBodyMinCount;
@property(copy, nonatomic) NSString *commentPlaceHolder; // @synthesize commentPlaceHolder=_commentPlaceHolder;
@property(retain, nonatomic) MOVIEAddCommentWriteCommentCell *commentCell; // @synthesize commentCell=_commentCell;
- (void).cxx_destruct;
- (id)validReviewInput:(id)arg1;
- (long long)validNum:(id)arg1;
- (void)defaultUpdateHintLabel;
- (void)updateHintLabel;
- (void)textViewKeyboardWillShow:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)setupModule;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

