//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MPCQQWallet : NSObject
{
}

+ (_Bool)handleResultWithURL:(id)arg1;
+ (_Bool)isSupportQQWallet;
+ (_Bool)isFromQQWalletPayWithURL:(id)arg1;
+ (id)currentAppQQWalletScheme;
+ (void)registQQWalletSDKWithAppId:(id)arg1;

@end

