//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NVModelBaseResultList.h"

@class NSArray, NSString;

@interface NVModelBaseSceneryTicketList : NVModelBaseResultList
{
    NSArray *_list;
    NSArray *_notices;
    long long _aheadDays;
    NSString *_aheadTime;
}

+ (id)metaInfo;
@property(copy, nonatomic) NSString *aheadTime; // @synthesize aheadTime=_aheadTime;
@property(nonatomic) long long aheadDays; // @synthesize aheadDays=_aheadDays;
@property(retain, nonatomic) NSArray *notices; // @synthesize notices=_notices;
@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
- (void).cxx_destruct;

@end

