//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NVBaseModel.h"

@class NSString;

@interface NVModelBaseHomeMarketEvent : NVBaseModel
{
    long long _eventID;
    long long _visit;
    NSString *_eventTime;
    NSString *_eventInfo;
    NSString *_eventName;
    NSString *_eventLogo;
}

+ (id)metaInfo;
@property(copy, nonatomic) NSString *eventLogo; // @synthesize eventLogo=_eventLogo;
@property(copy, nonatomic) NSString *eventName; // @synthesize eventName=_eventName;
@property(copy, nonatomic) NSString *eventInfo; // @synthesize eventInfo=_eventInfo;
@property(copy, nonatomic) NSString *eventTime; // @synthesize eventTime=_eventTime;
@property(nonatomic) long long visit; // @synthesize visit=_visit;
@property(nonatomic) long long eventID; // @synthesize eventID=_eventID;
- (void).cxx_destruct;

@end

