//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NVBaseModel.h"

@class NSString;

@interface NVModelBaseHuiReviewInfo : NVBaseModel
{
    NSString *_commentLabel;
    NSString *_tip;
    NSString *_title;
    long long _status;
}

+ (id)metaInfo;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *tip; // @synthesize tip=_tip;
@property(copy, nonatomic) NSString *commentLabel; // @synthesize commentLabel=_commentLabel;
- (void).cxx_destruct;

@end

