//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NVModelBaseResultList.h"

@class NSString;

@interface NVModelBaseJoyOrderList : NVModelBaseResultList
{
    _Bool _hasPayment;
    long long _commentStatus;
    long long _productType;
    NSString *_themeName;
    NSString *_pageType;
    NSString *_orderStatusDesc;
    NSString *_orderID;
    NSString *_headPicURL;
    NSString *_bookDate;
    NSString *_totalPrice;
    NSString *_shopTitle;
    long long _orderStatus;
}

+ (id)metaInfo;
@property(nonatomic) long long orderStatus; // @synthesize orderStatus=_orderStatus;
@property(copy, nonatomic) NSString *shopTitle; // @synthesize shopTitle=_shopTitle;
@property(copy, nonatomic) NSString *totalPrice; // @synthesize totalPrice=_totalPrice;
@property(copy, nonatomic) NSString *bookDate; // @synthesize bookDate=_bookDate;
@property(copy, nonatomic) NSString *headPicURL; // @synthesize headPicURL=_headPicURL;
@property(copy, nonatomic) NSString *orderID; // @synthesize orderID=_orderID;
@property(copy, nonatomic) NSString *orderStatusDesc; // @synthesize orderStatusDesc=_orderStatusDesc;
@property(nonatomic) _Bool hasPayment; // @synthesize hasPayment=_hasPayment;
@property(copy, nonatomic) NSString *pageType; // @synthesize pageType=_pageType;
@property(copy, nonatomic) NSString *themeName; // @synthesize themeName=_themeName;
@property(nonatomic) long long productType; // @synthesize productType=_productType;
@property(nonatomic) long long commentStatus; // @synthesize commentStatus=_commentStatus;
- (void).cxx_destruct;

@end

