//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, TGNaviNode, TGNaviView, UIButton, UIView;

@protocol TGNaviViewDelegate <NSObject>

@optional
- (void)mutableSelectTagsView:(TGNaviView *)arg1 selectedTagNodes:(NSArray *)arg2;
- (void)naviView:(TGNaviView *)arg1 selectedNaviTagNode:(TGNaviNode *)arg2;
- (UIView *)filterContentViewForNaviView:(TGNaviView *)arg1;
- (double)filterContentViewHeightForNaviView:(TGNaviView *)arg1;
- (UIView *)naviView:(TGNaviView *)arg1 extraContentViewForNaviNode:(TGNaviNode *)arg2 naviIndex:(long long)arg3;
- (double)naviView:(TGNaviView *)arg1 naviContentViewHeightForNaviNode:(TGNaviNode *)arg2 naviIndex:(long long)arg3;
- (void)naviView:(TGNaviView *)arg1 selectedFilterTags:(NSDictionary *)arg2;
- (void)naviView:(TGNaviView *)arg1 didSelectNode:(TGNaviNode *)arg2 naviIndex:(long long)arg3;
- (void)naviView:(TGNaviView *)arg1 clickedFilterButton:(UIButton *)arg2;
@end

