//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, TGPMSubOrderListViewController;

@interface TGPMSubOrderListInfo : NSObject
{
    NSString *_tabName;
    NSString *_title;
    long long _filter;
    TGPMSubOrderListViewController *_subOrderListViewController;
}

@property(retain, nonatomic) TGPMSubOrderListViewController *subOrderListViewController; // @synthesize subOrderListViewController=_subOrderListViewController;
@property(nonatomic) long long filter; // @synthesize filter=_filter;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *tabName; // @synthesize tabName=_tabName;
- (void).cxx_destruct;

@end

