//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "QalBindCallbackProtocol-Protocol.h"

@class NSString;

@interface TIMInnerQALBindProtocol : NSObject <QalBindCallbackProtocol>
{
    CDUnknownBlockType succ;
    CDUnknownBlockType fail;
}

@property(copy, nonatomic) CDUnknownBlockType fail; // @synthesize fail;
@property(copy, nonatomic) CDUnknownBlockType succ; // @synthesize succ;
- (void).cxx_destruct;
- (void)onFail:(int)arg1;
- (void)onSucc;
- (id)QAL2IMCoreErrcode:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

