//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class HTLLinearAutoLayoutView, SAKCell, TTKTrainInstruanceDetailViewModel, UIImageView, UILabel;

@interface TTKTrainAddressViewController : UIViewController
{
    TTKTrainInstruanceDetailViewModel *_viewModel;
    UILabel *_titleLabel;
    UIImageView *_checkImageView;
    UILabel *_subTitleLabel;
    SAKCell *_addressCell;
    SAKCell *_titleCell;
    HTLLinearAutoLayoutView *_contentView;
}

@property(retain, nonatomic) HTLLinearAutoLayoutView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) SAKCell *titleCell; // @synthesize titleCell=_titleCell;
@property(retain, nonatomic) SAKCell *addressCell; // @synthesize addressCell=_addressCell;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UIImageView *checkImageView; // @synthesize checkImageView=_checkImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak TTKTrainInstruanceDetailViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)loadAddress;
- (void)setupUI;
- (void)bindData;
- (void)refreshCheckButton:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initViewModel:(id)arg1;

@end

