//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NVShopInfoModuleController.h"

#import "VCShopInfoBookModuleCellDelegate-Protocol.h"

@class NSString, NVModelBaseBookInfo, VCShopInfoBookModuleCell;

@interface VCShopInfoBookModule : NVShopInfoModuleController <VCShopInfoBookModuleCellDelegate>
{
    _Bool _hasQueried;
    NVModelBaseBookInfo *_bookInfo;
    VCShopInfoBookModuleCell *_cell;
}

@property(retain, nonatomic) VCShopInfoBookModuleCell *cell; // @synthesize cell=_cell;
@property(nonatomic) _Bool hasQueried; // @synthesize hasQueried=_hasQueried;
@property(retain, nonatomic) NVModelBaseBookInfo *bookInfo; // @synthesize bookInfo=_bookInfo;
- (void).cxx_destruct;
- (void)didSelectOnIndexPath:(id)arg1;
- (void)shopDidUpdate:(id)arg1;
- (double)viewHeight;
- (_Bool)shouldShow;
- (id)ga_userinfo;
- (id)ga_label;
- (void)bookingButtonClicked;
- (void)updateCell;
- (void)loadBookStatus;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

