//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AMAOSBaseData.h"

@class NSMutableDictionary, NSString;

@interface AMAOSMarkPointsData : AMAOSBaseData
{
    NSString *_category;
    NSMutableDictionary *_blocks;
}

@property(retain, nonatomic) NSMutableDictionary *blocks; // @synthesize blocks=_blocks;
@property(copy, nonatomic) NSString *cateogory; // @synthesize cateogory=_category;
- (void).cxx_destruct;
- (id)init;

@end

