//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LTMMergeJSONBaseRequest.h"

@class LTMAOSRGeoRequest, LTMPathAlongWayRequest, LTMWeatherInfoRequest;
@protocol RequestIgnore;

@interface LTMPublictransitMergeRequest : LTMMergeJSONBaseRequest
{
    LTMAOSRGeoRequest<RequestIgnore> *_reversecode_start;
    LTMAOSRGeoRequest<RequestIgnore> *_reversecode_end;
    LTMPathAlongWayRequest<RequestIgnore> *_poi_linearound;
    LTMWeatherInfoRequest<RequestIgnore> *_weather;
}

@property(retain, nonatomic) LTMWeatherInfoRequest<RequestIgnore> *weather; // @synthesize weather=_weather;
@property(retain, nonatomic) LTMPathAlongWayRequest<RequestIgnore> *poi_linearound; // @synthesize poi_linearound=_poi_linearound;
@property(retain, nonatomic) LTMAOSRGeoRequest<RequestIgnore> *reversecode_end; // @synthesize reversecode_end=_reversecode_end;
@property(retain, nonatomic) LTMAOSRGeoRequest<RequestIgnore> *reversecode_start; // @synthesize reversecode_start=_reversecode_start;
- (void).cxx_destruct;
- (id)init;

@end

