//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NMCommonManagerSqlLite : NSObject
{
}

+ (id)getCountSqlForTable:(id)arg1;
+ (id)getQuerySqlForTable:(id)arg1;
+ (id)getUpdateSqlForTable:(id)arg1;
+ (id)getDeleteSqlForTable:(id)arg1;
+ (id)getInsertSqlForTable:(id)arg1;
+ (id)getCreateSqlForTable:(id)arg1;
+ (id)getDropSqlForTable:(id)arg1;
+ (_Bool)clearAllDataForTablename:(id)arg1;
+ (id)queryJsonDataForKey:(id)arg1 tableName:(id)arg2;
+ (_Bool)saveJsonData:(id)arg1 forKey:(id)arg2 tableName:(id)arg3;
+ (_Bool)clearAllDataForManager:(id)arg1;
+ (id)queryJsonDataForKey:(id)arg1 manager:(id)arg2;
+ (long long)getCountForKey:(id)arg1 intTable:(id)arg2;
+ (_Bool)saveJsonData:(id)arg1 forKey:(id)arg2 manager:(id)arg3;
+ (void)checkTableForName:(id)arg1;

@end

