//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NMDownloaderTask, NSArray, NSDictionary, NSError;

@protocol NMDownloaderDelegate <NSObject>
- (void)didDownloadTaskFinished:(NMDownloaderTask *)arg1;
- (void)didDownloadTaskStatusChanged:(NMDownloaderTask *)arg1;

@optional
- (void)didDownloadTaskStart:(NMDownloaderTask *)arg1 responseStatusCode:(long long)arg2 responseHeaders:(NSDictionary *)arg3;
- (void)didDownloadBackgroundtaskEnded:(NMDownloaderTask *)arg1;
- (void)didDownloadTaskProgressChanged:(NMDownloaderTask *)arg1;
- (void)didDownloadTaskFailed:(NMDownloaderTask *)arg1 error:(NSError *)arg2;
- (void)didDownloadTaskStoped:(NMDownloaderTask *)arg1 withErrorType:(long long)arg2;
- (void)didDownloadbackgroundTaskCanceled:(NMDownloaderTask *)arg1;
- (void)didDownloadTasksStatusChanged:(NSArray *)arg1;
@end

