//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JceObjectV2.h"

@class ComicCircleUserAccount, NSArray, NSString;

@interface ComicCircleHandleCircleResourceReq : JceObjectV2
{
    ComicCircleUserAccount *jcev2_p_0_r_stUser;
    NSString *jcev2_p_1_r_sCircleId;
    NSArray *jcev2_p_2_r_vModifyResourceInfo__b0x9i_VOComicCircleModifyResourceInfo;
    long long jcev2_p_3_o_eRole;
}

+ (id)jceType;
+ (void)initialize;
@property(nonatomic, getter=jce_eRole, setter=setJce_eRole:) long long jcev2_p_3_o_eRole; // @synthesize jcev2_p_3_o_eRole;
@property(retain, nonatomic, getter=jce_vModifyResourceInfo, setter=setJce_vModifyResourceInfo:) NSArray *jcev2_p_2_r_vModifyResourceInfo__b0x9i_VOComicCircleModifyResourceInfo; // @synthesize jcev2_p_2_r_vModifyResourceInfo__b0x9i_VOComicCircleModifyResourceInfo;
@property(retain, nonatomic, getter=jce_sCircleId, setter=setJce_sCircleId:) NSString *jcev2_p_1_r_sCircleId; // @synthesize jcev2_p_1_r_sCircleId;
@property(retain, nonatomic, getter=jce_stUser, setter=setJce_stUser:) ComicCircleUserAccount *jcev2_p_0_r_stUser; // @synthesize jcev2_p_0_r_stUser;
- (void).cxx_destruct;
- (id)init;

@end

