//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MttMainMenuBaseViewController.h"

@class MttMainMenuViewController;

@interface MttToolBoxMenuController : MttMainMenuBaseViewController
{
    MttMainMenuViewController *_parentMenuController;
}

@property(nonatomic) __weak MttMainMenuViewController *parentMenuController; // @synthesize parentMenuController=_parentMenuController;
- (void).cxx_destruct;
- (void)mainMenuButtonClick:(id)arg1;
- (id)mainMenuButtonWithTag:(long long)arg1;
- (void)checkMenuButtonStatus;
- (void)createMenuButtons;
- (id)menuButtonTags;
- (_Bool)isMenuButtonShouldShow:(long long)arg1;
- (void)viewDidLoad;

@end

