//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VSAfterSaleSectionModel.h"

@class UIView, VSASGoodListSectionFootView, VSASSectionHeadView;

@interface VSASGoodListSectionModel : VSAfterSaleSectionModel
{
    _Bool _expand;
    VSASSectionHeadView *_headView;
    VSASGoodListSectionFootView *_footView;
    UIView *_expendFootView;
}

@property(retain, nonatomic) UIView *expendFootView; // @synthesize expendFootView=_expendFootView;
@property(nonatomic) _Bool expand; // @synthesize expand=_expand;
@property(retain, nonatomic) VSASGoodListSectionFootView *footView; // @synthesize footView=_footView;
@property(retain, nonatomic) VSASSectionHeadView *headView; // @synthesize headView=_headView;
- (void).cxx_destruct;
- (void)configureSectionData;
- (unsigned long long)numberOfRows;
- (id)viewForFooter;
- (long long)heightForFootView;
- (id)viewForHeader;
- (long long)heightForHeader;
- (id)initWithCellModelArray:(id)arg1 orderSn:(id)arg2;

@end

