//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VSCatGoodListViewController.h"

#import "VSCatBrandStoreInfoCellDelegate-Protocol.h"
#import "VSCatSearchBrandHeadViewDelegate-Protocol.h"

@class NSObject, NSString, UIView, VSCatSearchGoodListViewModel, VSCatSearchHotKeyWordsView, VSCatSearchNoDataView, VSCatSearchTopbarView;
@protocol VSUnifiedComponentsManagerProtocol, VSUnifiedComponentsViewProtocol;

@interface VSCatSearchGoodListViewController : VSCatGoodListViewController <VSCatSearchBrandHeadViewDelegate, VSCatBrandStoreInfoCellDelegate>
{
    _Bool _exposeStatis;
    NSString *_defaultKeywords;
    NSString *_showKeyword;
    NSString *_originalKeywordForProtocol;
    unsigned long long _searchTargetDefaultType;
    VSCatSearchGoodListViewModel *_viewModel;
    VSCatSearchHotKeyWordsView *_searchHotKeywordView;
    VSCatSearchNoDataView *_searchNoDataView;
    VSCatSearchTopbarView *_searchTopbarView;
    CDUnknownBlockType _keywordCallback;
    NSString *_keywordText;
    NSObject<VSUnifiedComponentsManagerProtocol> *_youMayAlsoLikeUnifiedComponentsManager;
    UIView<VSUnifiedComponentsViewProtocol> *_youMayAlsoLikeView;
    long long _couponAdViewStatus;
}

@property(nonatomic) long long couponAdViewStatus; // @synthesize couponAdViewStatus=_couponAdViewStatus;
@property(retain, nonatomic) UIView<VSUnifiedComponentsViewProtocol> *youMayAlsoLikeView; // @synthesize youMayAlsoLikeView=_youMayAlsoLikeView;
@property(nonatomic) _Bool exposeStatis; // @synthesize exposeStatis=_exposeStatis;
@property(retain, nonatomic) NSObject<VSUnifiedComponentsManagerProtocol> *youMayAlsoLikeUnifiedComponentsManager; // @synthesize youMayAlsoLikeUnifiedComponentsManager=_youMayAlsoLikeUnifiedComponentsManager;
@property(copy, nonatomic) NSString *keywordText; // @synthesize keywordText=_keywordText;
@property(copy, nonatomic) CDUnknownBlockType keywordCallback; // @synthesize keywordCallback=_keywordCallback;
@property(retain, nonatomic) VSCatSearchTopbarView *searchTopbarView; // @synthesize searchTopbarView=_searchTopbarView;
@property(retain, nonatomic) VSCatSearchNoDataView *searchNoDataView; // @synthesize searchNoDataView=_searchNoDataView;
@property(retain, nonatomic) VSCatSearchHotKeyWordsView *searchHotKeywordView; // @synthesize searchHotKeywordView=_searchHotKeywordView;
@property(retain, nonatomic) VSCatSearchGoodListViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) unsigned long long searchTargetDefaultType; // @synthesize searchTargetDefaultType=_searchTargetDefaultType;
@property(copy, nonatomic) NSString *originalKeywordForProtocol; // @synthesize originalKeywordForProtocol=_originalKeywordForProtocol;
@property(retain, nonatomic) NSString *showKeyword; // @synthesize showKeyword=_showKeyword;
@property(retain, nonatomic) NSString *defaultKeywords; // @synthesize defaultKeywords=_defaultKeywords;
- (void).cxx_destruct;
- (void)emptyFavouriteBtnClicked:(id)arg1;
- (void)checkFavouriteStatus;
- (void)enterBrandStoreBtnClicked:(id)arg1;
- (void)favouriteBtnClicked:(id)arg1;
- (void)reloadBrandStoreInfoCell;
- (void)resetFilterConditionsViewStyle;
- (void)scrollViewContentOffsetDidChanged;
- (void)handleBrandStoreInfo:(id)arg1;
- (void)fetchUnifiedComponentsManagerWithCallback:(CDUnknownBlockType)arg1;
- (void)hideNavBottomLine:(_Bool)arg1;
- (long long)fetchRealIndex:(long long)arg1 withChannelSearchResultipsView:(_Bool)arg2;
- (void)sendResourceExpose;
- (void)sendContentOperationClickStatistics:(id)arg1;
- (void)sendAutoOperationClickStatistics:(id)arg1;
- (void)sendPageStatistics;
- (void)changeLayout;
- (long long)maxRowForTopRateWithRow:(long long)arg1;
- (void)changeLayoutWithType:(unsigned long long)arg1;
- (void)scrollToTopFilter;
- (void)scrollToTopForClick:(_Bool)arg1;
- (void)showNoFilterDataView;
- (void)hideNoDataView;
- (void)showNoDataView;
- (void)onCollect:(id)arg1;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (id)addTopSpace:(id)arg1 height:(double)arg2 spaceColor:(int)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)setUpSearchManager;
- (void)modifyKeywords:(id)arg1 isReset:(_Bool)arg2;
- (void)modifyKeywords:(id)arg1;
- (void)updateSearchParams:(id)arg1;
- (id)createSearchHotKeywordView;
- (void)dealloc;
- (void)reloadCollectionView;
- (void)navigateBack;
- (void)addRecommendGoods;
- (void)addRecommendKeyWordsCell;
- (void)bindSearchViewModel;
- (void)handleFilterConditionsViewPopListViewAction:(_Bool)arg1;
- (void)enterBackground;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupCollectionView;
- (void)viewDidLoad;
- (id)initWithViewModel:(id)arg1 withSearchWordUpdateBlock:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

