//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface VSCollectionAgent : NSObject
{
}

+ (id)favouriteBrandsCancelPlacedTopWithRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)favouriteBrandsPlacedTopWithRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)favouriteBrandsListRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)cancelFavouriteHistoryGoods:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)cancelFavouriteGoodsRemind:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)favouriteGoodsListRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)newfavouriteGoodsListRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)fetchCollectedProductRealTimeSizeWithCollectedProductsRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)fetchSimpleCollectedProductListInfoRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)fetchCollectedProductListWithCollectedProductsRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)fetchMultiBrandCouponStatusWithBrandIds:(id)arg1 Success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)fetchCollectedCategoryTagListPagesize:(long long)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)fetchCollectedBrandListSuccess:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;

@end

