//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;
@protocol Optional;

@interface VSDeliveryAddress : JSONModel
{
    _Bool _isCommon;
    _Bool _canCOD;
    _Bool _currentSelect;
    _Bool _canEdit;
    _Bool _idNumberValidatedPass;
    NSString<Optional> *_addressID;
    NSString<Optional> *_consignee;
    NSString<Optional> *_areaID;
    NSString<Optional> *_address;
    NSString<Optional> *_postcode;
    NSString<Optional> *_mobile;
    NSString<Optional> *_telephone;
    NSString<Optional> *_warehouse;
    NSString<Optional> *_provinceCode;
    NSString<Optional> *_cityCode;
    NSString<Optional> *_regionCode;
    NSString<Optional> *_provinceName;
    NSString<Optional> *_cityName;
    NSString<Optional> *_regionName;
    NSString<Optional> *_townName;
    long long _transportDay;
    NSString<Optional> *_fullName;
    long long _countryId;
    long long _addrType;
    NSString<Optional> *_idNumber;
}

+ (_Bool)propertyIsIgnored:(id)arg1;
+ (_Bool)propertyIsOptional:(id)arg1;
+ (id)modelCustomPropertyMapper;
+ (id)keyMapper;
@property(nonatomic) _Bool idNumberValidatedPass; // @synthesize idNumberValidatedPass=_idNumberValidatedPass;
@property(copy, nonatomic) NSString<Optional> *idNumber; // @synthesize idNumber=_idNumber;
@property(nonatomic) long long addrType; // @synthesize addrType=_addrType;
@property(nonatomic) _Bool canEdit; // @synthesize canEdit=_canEdit;
@property(nonatomic) _Bool currentSelect; // @synthesize currentSelect=_currentSelect;
@property(nonatomic) _Bool canCOD; // @synthesize canCOD=_canCOD;
@property(nonatomic) long long countryId; // @synthesize countryId=_countryId;
@property(copy, nonatomic) NSString<Optional> *fullName; // @synthesize fullName=_fullName;
@property(nonatomic) _Bool isCommon; // @synthesize isCommon=_isCommon;
@property(nonatomic) long long transportDay; // @synthesize transportDay=_transportDay;
@property(copy, nonatomic) NSString<Optional> *townName; // @synthesize townName=_townName;
@property(copy, nonatomic) NSString<Optional> *regionName; // @synthesize regionName=_regionName;
@property(copy, nonatomic) NSString<Optional> *cityName; // @synthesize cityName=_cityName;
@property(copy, nonatomic) NSString<Optional> *provinceName; // @synthesize provinceName=_provinceName;
@property(copy, nonatomic) NSString<Optional> *regionCode; // @synthesize regionCode=_regionCode;
@property(copy, nonatomic) NSString<Optional> *cityCode; // @synthesize cityCode=_cityCode;
@property(copy, nonatomic) NSString<Optional> *provinceCode; // @synthesize provinceCode=_provinceCode;
@property(copy, nonatomic) NSString<Optional> *warehouse; // @synthesize warehouse=_warehouse;
@property(copy, nonatomic) NSString<Optional> *telephone; // @synthesize telephone=_telephone;
@property(copy, nonatomic) NSString<Optional> *mobile; // @synthesize mobile=_mobile;
@property(copy, nonatomic) NSString<Optional> *postcode; // @synthesize postcode=_postcode;
@property(copy, nonatomic) NSString<Optional> *address; // @synthesize address=_address;
@property(copy, nonatomic) NSString<Optional> *areaID; // @synthesize areaID=_areaID;
@property(copy, nonatomic) NSString<Optional> *consignee; // @synthesize consignee=_consignee;
@property(copy, nonatomic) NSString<Optional> *addressID; // @synthesize addressID=_addressID;
- (void).cxx_destruct;
- (id)init;
- (id)locationName;
- (id)fdcAreaid;
- (id)addressTypeString;
- (id)detailAddressString;
- (id)idCardNumberString;
- (id)formatTransportDay;

@end

