//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, VSUserGuideModel;

@interface VSUserGuideManager : NSObject
{
    _Bool _isShowing;
    VSUserGuideModel *_searchUserGuideMode;
    NSString *_hotWord;
}

+ (void)saveModel:(id)arg1;
+ (id)sharedInstance;
@property(nonatomic) _Bool isShowing; // @synthesize isShowing=_isShowing;
@property(copy, nonatomic) NSString *hotWord; // @synthesize hotWord=_hotWord;
@property(retain, nonatomic) VSUserGuideModel *searchUserGuideMode; // @synthesize searchUserGuideMode=_searchUserGuideMode;
- (void).cxx_destruct;
- (void)usedSearch;
- (void)userGuideViewClick;
- (void)showSearchUserGuide:(id)arg1 menuCode:(id)arg2 channelName:(id)arg3;
- (_Bool)showSearchUserGuideWithTargetView:(id)arg1 menuCode:(id)arg2 channelName:(id)arg3;
- (long long)targetBrandIndex;
- (void)countAppLaunch;
- (id)init;

@end

