//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, VSVideoShoppingMerchandiseModel;

@interface VSVideoShoppingSizeHeaderViewModel : NSObject
{
    _Bool _isReconmmend;
    NSString *_iconUrl;
    NSString *_prepayMsg;
    VSVideoShoppingMerchandiseModel *_model;
    CDUnknownBlockType _closeAction;
}

@property(copy, nonatomic) CDUnknownBlockType closeAction; // @synthesize closeAction=_closeAction;
@property(retain, nonatomic) VSVideoShoppingMerchandiseModel *model; // @synthesize model=_model;
@property(copy, nonatomic) NSString *prepayMsg; // @synthesize prepayMsg=_prepayMsg;
@property(nonatomic) _Bool isReconmmend; // @synthesize isReconmmend=_isReconmmend;
@property(copy, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
- (void).cxx_destruct;
- (void)bindModel;
- (id)initWithModel:(id)arg1;

@end

