//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8RGLogger13RGOOMDetector : NSObject
{
    // Error parsing type: , name: detectorDirectory
    // Error parsing type: , name: terminationEventFilePath
    // Error parsing type: , name: lastTerminationReason
    // Error parsing type: , name: backgroundStateFilePath
    // Error parsing type: , name: appWasBackgroundedOnExit
}

- (CDUnknownBlockType).cxx_destruct;
- (void)handleTerminateNotification;
- (void)handleForegroundNotification;
- (void)handleBackgroundNotification;
- (id)init;

@end

