//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseUIViewController.h"

#import "FspHtmlParserDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class FspAggregateNativeViewController, FspHtmlParser, FspPlayPageStatusView, NSString, UIWebView;

@interface FspAggregatePlayViewController : BaseUIViewController <UIWebViewDelegate, FspHtmlParserDelegate>
{
    NSString *_eid;
    NSString *_sid;
    NSString *_site;
    NSString *_name;
    UIWebView *_webView;
    FspHtmlParser *_parser;
    int _type;
    FspPlayPageStatusView *_statusView;
    NSString *_url;
    NSString *_videoUrl;
    FspAggregateNativeViewController *_playViewController;
    _Bool _isFirstPlay;
    _Bool _isMovie;
    int _requestCount;
}

- (void).cxx_destruct;
- (void)onGetPlayConfigCompleted:(int)arg1 js:(id)arg2;
- (void)queryPlayInfo;
- (void)getPlayConfig;
- (void)retry;
- (void)loadFailed;
- (void)onFetchPlayInfoCompleted:(id)arg1;
- (void)requestPlayInfo;
- (void)skipToHTMLPlay;
- (void)parseCompleted:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (_Bool)shouldRequestWithUrl:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)quitAggregatePlay;
- (void)quitPlay;
- (void)onPlayFinished;
- (void)onRetryPlay;
- (void)videoDuration:(id)arg1;
- (void)createPlayUI;
- (void)loadWebAtUrl:(id)arg1;
- (void)createWebView;
- (void)createView;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithId:(id)arg1 sid:(id)arg2 site:(id)arg3 name:(id)arg4 type:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

