//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FspAdReportCenter : NSObject
{
}

+ (void)directReport:(id)arg1 params:(id)arg2;
+ (void)generalClickReport:(id)arg1;
+ (void)funshionClickReport:(id)arg1;
+ (void)generalViewReport:(id)arg1;
+ (_Bool)isGeneralURL:(id)arg1;
+ (void)funshionViewReport:(id)arg1 time:(double)arg2;
+ (_Bool)isFunshionURL:(id)arg1;
+ (void)admasterClickReport:(id)arg1;
+ (void)admasterViewReport:(id)arg1;
+ (_Bool)isAdmasterURL:(id)arg1;
+ (void)mzMonitorClickReport:(id)arg1;
+ (void)mzMonitorViewReport:(id)arg1;
+ (_Bool)isMZMonitorURL:(id)arg1;
+ (void)clickReport:(id)arg1 url:(id)arg2;
+ (void)viewReport:(id)arg1 url:(id)arg2 time:(double)arg3;
+ (void)initReportDispatchQueueIfNeed;

@end

