//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BCECrashHandlerDelegate-Protocol.h"

@class BCEPlayerCacheCounter, BCEStatisticsFingerComposer, BCEStatisticsPlayerRequest, BCEStatisticsSender, CyberPlayerController, NSDate, NSString;
@protocol OS_dispatch_queue;

@interface BCEPlayerStatistics : NSObject <BCECrashHandlerDelegate>
{
    CyberPlayerController *_player;
    BCEStatisticsPlayerRequest *_requestBuilder;
    BCEStatisticsFingerComposer *_finger;
    NSObject<OS_dispatch_queue> *_queue;
    BCEStatisticsSender *_sender;
    BCEPlayerCacheCounter *_cacheCounter;
    NSDate *_startTimestamp;
    NSDate *_pauseTimestamp;
    double _totalPauseTime;
    NSDate *_sessionTime;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSDate *sessionTime; // @synthesize sessionTime=_sessionTime;
@property(nonatomic) double totalPauseTime; // @synthesize totalPauseTime=_totalPauseTime;
@property(retain, nonatomic) NSDate *pauseTimestamp; // @synthesize pauseTimestamp=_pauseTimestamp;
@property(retain, nonatomic) NSDate *startTimestamp; // @synthesize startTimestamp=_startTimestamp;
@property(retain, nonatomic) BCEPlayerCacheCounter *cacheCounter; // @synthesize cacheCounter=_cacheCounter;
@property(retain, nonatomic) BCEStatisticsSender *sender; // @synthesize sender=_sender;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) BCEStatisticsFingerComposer *finger; // @synthesize finger=_finger;
@property(retain, nonatomic) BCEStatisticsPlayerRequest *requestBuilder; // @synthesize requestBuilder=_requestBuilder;
@property(nonatomic) __weak CyberPlayerController *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (id)errorInfo:(id)arg1;
- (void)updateTimestamp:(id)arg1;
- (id)buildCommonInfo;
- (void)onCrash:(id)arg1;
- (void)onError:(id)arg1;
- (void)onFinish;
- (void)onPrepared;
- (void)onNotification:(id)arg1;
- (void)registerNotifications;
- (void)seekTo:(double)arg1;
- (void)stop;
- (void)pause;
- (void)play;
- (void)start;
- (void)prepare;
- (void)setAK:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

