//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BNJSSchemeProvider, NSMutableArray, NSMutableDictionary, NSString;

@interface BNJSSchemeManager : NSObject
{
    NSString *_schemePrefix;
    BNJSSchemeProvider *_schemeProvider;
    NSMutableArray *_supportedScheme;
    NSMutableDictionary *_handlerSchemeDitionary;
    NSMutableDictionary *_remappingSchemeDitionary;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSMutableDictionary *remappingSchemeDitionary; // @synthesize remappingSchemeDitionary=_remappingSchemeDitionary;
@property(retain, nonatomic) NSMutableDictionary *handlerSchemeDitionary; // @synthesize handlerSchemeDitionary=_handlerSchemeDitionary;
@property(retain, nonatomic) NSMutableArray *supportedScheme; // @synthesize supportedScheme=_supportedScheme;
@property(retain, nonatomic) BNJSSchemeProvider *schemeProvider; // @synthesize schemeProvider=_schemeProvider;
@property(retain, nonatomic) NSString *schemePrefix; // @synthesize schemePrefix=_schemePrefix;
- (void).cxx_destruct;
- (void)registerScheme:(id)arg1;
- (void)resetSchemePrefix:(id)arg1;
- (_Bool)openPageUrl:(id)arg1;
- (id)ultimateUrl:(id)arg1;
- (_Bool)isNeedLoginWithUrl:(id)arg1;
- (_Bool)openURL:(id)arg1;
- (void)openURLInternal:(id)arg1;
- (_Bool)isWifiNet;
- (_Bool)canOpenURL:(id)arg1;
- (_Bool)isThritPartConfigScheme:(id)arg1;
- (_Bool)isNuomiCompScheme:(id)arg1;
- (_Bool)registeredHandlerScheme:(id)arg1;
- (void)handlerScheme:(id)arg1 withHandler:(CDUnknownBlockType)arg2;
- (void)reMappingScheme:(id)arg1 newScheme:(id)arg2;
- (id)fetchRealScheme:(id)arg1;
- (_Bool)isOpenPageScheme:(id)arg1;
- (_Bool)hasConfigScheme:(id)arg1;
- (void)pushViewController:(id)arg1 withParams:(id)arg2 withScheme:(id)arg3;
- (_Bool)compNeedsLogin:(id)arg1 params:(id)arg2;
- (_Bool)openNewComponentPage:(id)arg1 withScheme:(id)arg2;
- (_Bool)handlerComponentAction:(id)arg1 params:(id)arg2;
- (id)getAppSchemas;
- (id)init;

@end

