//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UITableViewDataSource-Protocol.h"

@class HUAccountTableViewCell, HUModuleTabbarCell, HUPositionValueCell, NSMutableArray, NSString, UIImageView;

@interface HUHomeVCDataSource : NSObject <UITableViewDataSource>
{
    _Bool _isHUMNCGNewEntrance;
    HUAccountTableViewCell *_accountCell;
    HUPositionValueCell *_positionValueCell;
    HUModuleTabbarCell *_moduleTabbarCell;
    NSMutableArray *_dataSourceArr;
    UIImageView *_imgViewRedPoint;
}

@property(retain, nonatomic) UIImageView *imgViewRedPoint; // @synthesize imgViewRedPoint=_imgViewRedPoint;
@property(nonatomic) _Bool isHUMNCGNewEntrance; // @synthesize isHUMNCGNewEntrance=_isHUMNCGNewEntrance;
@property(retain, nonatomic) NSMutableArray *dataSourceArr; // @synthesize dataSourceArr=_dataSourceArr;
@property(retain, nonatomic) HUModuleTabbarCell *moduleTabbarCell; // @synthesize moduleTabbarCell=_moduleTabbarCell;
@property(retain, nonatomic) HUPositionValueCell *positionValueCell; // @synthesize positionValueCell=_positionValueCell;
@property(retain, nonatomic) HUAccountTableViewCell *accountCell; // @synthesize accountCell=_accountCell;
- (void).cxx_destruct;
- (id)getSectionStockTradeHelp;
- (id)getSectionSuggestion;
- (id)getSectionChangePWD;
- (id)getSectionFunds;
- (id)getSectionPosition;
- (id)getSectionMain;
- (id)getRefreshCookie;
- (id)getSuggestionURL;
- (id)getChangePWDDicWithPageID:(id)arg1 refreshCookie:(id)arg2;
- (id)getChangePWDPageID;
- (void)mncgBrokerConfiguration;
- (void)normalBrokerConfiguration;
- (void)removeOperationRedPoint;
- (void)showScoreOperationRedPointWithCell:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)removeSectionFromDataSource:(long long)arg1;
- (void)addSectionToDataSource:(id)arg1 rowAtIndex:(long long)arg2;
- (void)replaceSectionOfDataSource:(id)arg1 rowAtIndex:(long long)arg2;
- (id)getRowDataSource:(id)arg1 indexPath:(id)arg2;
- (unsigned long long)getBrokerId;
- (long long)getYybType;
- (id)accountInfo;
- (void)initComponents;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

