//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface HXVBackTestEveryDayIncome : NSObject
{
    double _hsRate;
    double _queryRate;
    NSString *_dateTime;
}

+ (id)modelCustomPropertyMapper;
@property(retain, nonatomic) NSString *dateTime; // @synthesize dateTime=_dateTime;
@property(nonatomic) double queryRate; // @synthesize queryRate=_queryRate;
@property(nonatomic) double hsRate; // @synthesize hsRate=_hsRate;
- (void).cxx_destruct;

@end

