//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HXBaseViewController.h"

@class NSTimer, UIButton, UIImageView, UILabel, UIView;
@protocol RRProfitAgreeAnalyseViewControllerDelegate;

@interface RRProfitAgreeAnalyseViewController : HXBaseViewController
{
    id <RRProfitAgreeAnalyseViewControllerDelegate> _delegate;
    UIView *_backView;
    UIView *_imageBackView;
    UIImageView *_analyseImageView;
    UILabel *_analyseTitleLabel;
    UILabel *_detailLabel;
    UIButton *_agreeBtn;
    UILabel *_analyseLabel;
    UIButton *_analyseBtn;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UIButton *analyseBtn; // @synthesize analyseBtn=_analyseBtn;
@property(retain, nonatomic) UILabel *analyseLabel; // @synthesize analyseLabel=_analyseLabel;
@property(retain, nonatomic) UIButton *agreeBtn; // @synthesize agreeBtn=_agreeBtn;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *analyseTitleLabel; // @synthesize analyseTitleLabel=_analyseTitleLabel;
@property(retain, nonatomic) UIImageView *analyseImageView; // @synthesize analyseImageView=_analyseImageView;
@property(retain, nonatomic) UIView *imageBackView; // @synthesize imageBackView=_imageBackView;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(nonatomic) __weak id <RRProfitAgreeAnalyseViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)endTimer;
- (void)startTimer;
- (void)goToProtocalView:(id)arg1;
- (void)doAgreeAnalyse:(id)arg1;
- (void)agreeAnalyseError:(id)arg1;
- (void)agreeAnalyseSucceed;
- (void)dealloc;
- (void)addMasonryConstraints;
- (void)viewDidLoad;

@end

