//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JMAiOSClientService : NSObject
{
}

+ (id)reportUserTrackVCArray;
+ (void)reportUserTrack:(id)arg1 eventParam:(id)arg2;
+ (void)reportGIS:(id)arg1;
+ (void)reportJMA:(id)arg1;
+ (id)getClientCPAInfo;
+ (void)reportFireEye:(id)arg1;
+ (void)registerJMA:(id)arg1 unionId:(id)arg2 subunionId:(id)arg3 partner:(id)arg4 uid:(id)arg5;

@end

