//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface TTTRushWaresStockUnit : UIView
{
    UIImageView *_icon;
    UILabel *_textLabel;
    UIView *_progressBackView;
    UIView *_progressFrontView;
}

@property(retain, nonatomic) UIView *progressFrontView; // @synthesize progressFrontView=_progressFrontView;
@property(retain, nonatomic) UIView *progressBackView; // @synthesize progressBackView=_progressBackView;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
- (void).cxx_destruct;
- (void)setStockGoodRateState:(id)arg1;
- (void)setStockNumState:(id)arg1;
- (void)setStockPercentageState:(id)arg1 animation:(_Bool)arg2;
- (void)showAll;
- (void)hideAll;
- (void)configProgressColorWithStyle:(long long)arg1 model:(id)arg2;
- (void)setStockWithStyle:(long long)arg1 wareModel:(id)arg2 animation:(_Bool)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

