//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CTMapAnnotationV2.h"

@class DistrictPoiSearchForMapItemModel;

@interface CTDestMapAnnotationV2 : CTMapAnnotationV2
{
    DistrictPoiSearchForMapItemModel *_model;
}

@property(retain, nonatomic) DistrictPoiSearchForMapItemModel *model; // @synthesize model=_model;
- (void).cxx_destruct;

@end

