//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, UIButton, UIControl;

@interface CTMyCtripPersonInfoCardCell : UITableViewCell
{
    UIButton *_titleBtn;
    UIButton *_closeBtn;
    UIControl *_mainView;
    NSArray *_expiredDocuments;
    CDUnknownBlockType _clickTitleBlock;
    CDUnknownBlockType _clickCloseBlock;
}

@property(copy, nonatomic) CDUnknownBlockType clickCloseBlock; // @synthesize clickCloseBlock=_clickCloseBlock;
@property(copy, nonatomic) CDUnknownBlockType clickTitleBlock; // @synthesize clickTitleBlock=_clickTitleBlock;
@property(retain, nonatomic) NSArray *expiredDocuments; // @synthesize expiredDocuments=_expiredDocuments;
- (void).cxx_destruct;
- (id)getTypeStrFromType:(id)arg1;
- (void)clickCloseBtn;
- (void)clickToPersonInfoListVC;
- (id)setUpItemView:(id)arg1;
- (void)initView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

