//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CTTourBaseModel.h"

@class NSString;

@interface CTTourAroundIcon : CTTourBaseModel
{
    NSString *_IconID;
    NSString *_Title;
    NSString *_Url;
    NSString *_Keyword;
    NSString *_Tag;
    NSString *_BgColor;
    NSString *_IconUrl;
    NSString *_Desc;
}

@property(retain) NSString *Desc; // @synthesize Desc=_Desc;
@property(retain) NSString *IconUrl; // @synthesize IconUrl=_IconUrl;
@property(retain) NSString *BgColor; // @synthesize BgColor=_BgColor;
@property(retain) NSString *Tag; // @synthesize Tag=_Tag;
@property(retain) NSString *Keyword; // @synthesize Keyword=_Keyword;
@property(retain) NSString *Url; // @synthesize Url=_Url;
@property(retain) NSString *Title; // @synthesize Title=_Title;
@property(retain) NSString *IconID; // @synthesize IconID=_IconID;
- (void).cxx_destruct;

@end

