//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CTTourBaseModel.h"

@class NSArray, NSString;

@interface CTTourDetailSegment : CTTourBaseModel
{
    _Bool _IsIncludeRadioResource;
    _Bool _IsFlight;
    _Bool _IsIncludeHotel;
    _Bool _IsIncludeSystemFlight;
    NSString *_SegmentID;
    NSString *_SegmentNumber;
    NSString *_DepartureCityID;
    NSString *_DepartureCityName;
    NSString *_DestinationCityID;
    NSString *_DestinationCityName;
    NSString *_DepartureAdjustDays;
    NSString *_CheckOutAdjustDays;
    NSString *_MaxStayDays;
    NSString *_MinLodgingDays;
    NSString *_MinStayDays;
    NSString *_Schedule;
    NSArray *_CloseDays;
}

+ (id)modelContainerPropertyGenericClass;
@property(retain) NSArray *CloseDays; // @synthesize CloseDays=_CloseDays;
@property _Bool IsIncludeSystemFlight; // @synthesize IsIncludeSystemFlight=_IsIncludeSystemFlight;
@property _Bool IsIncludeHotel; // @synthesize IsIncludeHotel=_IsIncludeHotel;
@property _Bool IsFlight; // @synthesize IsFlight=_IsFlight;
@property _Bool IsIncludeRadioResource; // @synthesize IsIncludeRadioResource=_IsIncludeRadioResource;
@property(retain) NSString *Schedule; // @synthesize Schedule=_Schedule;
@property(retain) NSString *MinStayDays; // @synthesize MinStayDays=_MinStayDays;
@property(retain) NSString *MinLodgingDays; // @synthesize MinLodgingDays=_MinLodgingDays;
@property(retain) NSString *MaxStayDays; // @synthesize MaxStayDays=_MaxStayDays;
@property(retain) NSString *CheckOutAdjustDays; // @synthesize CheckOutAdjustDays=_CheckOutAdjustDays;
@property(retain) NSString *DepartureAdjustDays; // @synthesize DepartureAdjustDays=_DepartureAdjustDays;
@property(retain) NSString *DestinationCityName; // @synthesize DestinationCityName=_DestinationCityName;
@property(retain) NSString *DestinationCityID; // @synthesize DestinationCityID=_DestinationCityID;
@property(retain) NSString *DepartureCityName; // @synthesize DepartureCityName=_DepartureCityName;
@property(retain) NSString *DepartureCityID; // @synthesize DepartureCityID=_DepartureCityID;
@property(retain) NSString *SegmentNumber; // @synthesize SegmentNumber=_SegmentNumber;
@property(retain) NSString *SegmentID; // @synthesize SegmentID=_SegmentID;
- (void).cxx_destruct;

@end

