//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UIImageView, UILabel, UIView;

@interface SNSearchWebHistoryCell : UITableViewCell
{
    UILabel *_keywordLabel;
    UIImageView *_arrowIcon;
    UIButton *_arrowButton;
    UIView *_bottomView;
    UIView *_arrowBgView;
    UIButton *_leftKeyWord;
    UIButton *_rightKeyWord;
}

@property(retain, nonatomic) UIButton *rightKeyWord; // @synthesize rightKeyWord=_rightKeyWord;
@property(retain, nonatomic) UIButton *leftKeyWord; // @synthesize leftKeyWord=_leftKeyWord;
@property(retain, nonatomic) UIView *arrowBgView; // @synthesize arrowBgView=_arrowBgView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIButton *arrowButton; // @synthesize arrowButton=_arrowButton;
@property(retain, nonatomic) UIImageView *arrowIcon; // @synthesize arrowIcon=_arrowIcon;
@property(retain, nonatomic) UILabel *keywordLabel; // @synthesize keywordLabel=_keywordLabel;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setLeftKeyWord:(id)arg1 RightKeyWord:(id)arg2;
- (void)updateKeyWordLabelTextColorWithKeyWord:(id)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (void)awakeFromNib;
- (id)init;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

