//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SNSBaseEntity.h"

@class NSString;

@interface SNSExArea : SNSBaseEntity
{
    NSString *_areaId;
    NSString *_areaName;
    NSString *_areaLevel;
    NSString *_parentAreaName;
    NSString *_parentAreaId;
}

@property(retain, nonatomic) NSString *parentAreaId; // @synthesize parentAreaId=_parentAreaId;
@property(retain, nonatomic) NSString *parentAreaName; // @synthesize parentAreaName=_parentAreaName;
@property(retain, nonatomic) NSString *areaLevel; // @synthesize areaLevel=_areaLevel;
@property(retain, nonatomic) NSString *areaName; // @synthesize areaName=_areaName;
@property(retain, nonatomic) NSString *areaId; // @synthesize areaId=_areaId;
- (void).cxx_destruct;
- (id)fullName;
- (void)loadWithDic:(id)arg1;

@end

