//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SNTitleActionMenuContent.h"

@class NSData, NSMutableDictionary, NSString;

@interface SNWXActionMenuContent : SNTitleActionMenuContent
{
    NSString *_imageUrl;
    NSData *_imageData;
    NSString *_webUrl;
    NSString *_mediaUrl;
    NSMutableDictionary *_shareInfoDic;
}

@property(retain, nonatomic) NSMutableDictionary *shareInfoDic; // @synthesize shareInfoDic=_shareInfoDic;
@property(retain, nonatomic) NSString *mediaUrl; // @synthesize mediaUrl=_mediaUrl;
@property(retain, nonatomic) NSString *webUrl; // @synthesize webUrl=_webUrl;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
- (void).cxx_destruct;
- (void)shareToThirdPartSuccess:(id)arg1;
- (id)shareWeixin;
- (void)share;
- (_Bool)isOnlyImage;
- (_Bool)isVideo;
- (void)interpretContext:(id)arg1;

// Remaining properties
@property(retain, nonatomic) NSString *newsLink;

@end

