//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MttMhtExtractorFile, NSMutableArray, NSString;

@interface MttMhtUnArchive : NSObject
{
    NSString *originalURISpec;
    NSString *boundary;
    NSMutableArray *boundaryStack;
    NSString *subject;
    NSString *start;
    MttMhtExtractorFile *rootFile;
    _Bool alternative;
    NSMutableArray *files;
    NSString *retcode;
    NSString *retcode2;
    int mode;
}

- (void).cxx_destruct;
- (id)unArchive:(id)arg1 toFilePath:(id)arg2;
- (int)extractMHT:(id)arg1 originalURISpec:(id)arg2;
- (int)replaceLocation;
- (id)replaceHTMLLocation:(id)arg1 file:(id)arg2;
- (id)checkFile:(id)arg1 path:(id)arg2 referred:(_Bool)arg3;
- (id)jointPath:(id)arg1 sub:(id)arg2;
- (int)decodeContent;
- (int)setCID;
- (int)deleteEmptyFile;
- (int)parseMHT:(id)arg1;
- (id)parseHeader:(id)arg1;
- (int)splitLocation:(id)arg1;
- (id)parseValue:(id)arg1 mimeType:(_Bool)arg2;
- (id)decodeRFC2231:(id)arg1;
- (id)splitHeader:(id)arg1;
- (id)decodeEW:(id)arg1;
- (id)unescape:(id)arg1;
- (id)decodeQuotedPrintable:(id)arg1;
- (id)init;

@end

