//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface MttNovelThumbImageManager : NSObject
{
    NSMutableArray *arrayTasks;
    NSObject *_lockObject;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)downloadImage:(id)arg1 saveName:(id)arg2 complete:(CDUnknownBlockType)arg3;
- (id)getImageFilePath:(id)arg1;
- (void)removeImage:(id)arg1;
- (id)getImage:(id)arg1;
- (Class)novelThumbImageDownloadClass;
- (id)init;

@end

