//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIFont;

@interface CTDestSelectView : UIView
{
    _Bool _showBorder;
    UIButton *_tabTitleBt;
    double _titleWidth;
    UIFont *_selFont;
    UIFont *_unSelFont;
}

@property(nonatomic) _Bool showBorder; // @synthesize showBorder=_showBorder;
@property(retain, nonatomic) UIFont *unSelFont; // @synthesize unSelFont=_unSelFont;
@property(retain, nonatomic) UIFont *selFont; // @synthesize selFont=_selFont;
@property(nonatomic) double titleWidth; // @synthesize titleWidth=_titleWidth;
@property(readonly, nonatomic) UIButton *tabTitleBt; // @synthesize tabTitleBt=_tabTitleBt;
- (void).cxx_destruct;
- (void)selectButton;
- (void)setClickEnable:(_Bool)arg1;
@property(readonly, nonatomic) _Bool isSelected;
- (double)selectViewWidth;
- (void)calculateTitleWidth:(id)arg1;
- (void)configureSubviews;
- (void)layoutSubviews;
- (id)initWithTitle:(id)arg1;
- (id)initWithTitle:(id)arg1 showBorder:(_Bool)arg2;

@end

