//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIAlertViewDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSArray, NSLayoutConstraint, NSString, UIButton, UICollectionView, UIImage, UIImageView, UILabel, UITextField, UITextView;
@protocol CTFeedbackQuestionViewProtocol;

@interface CTFeedbackQuestionView : UIView <UITextViewDelegate, UICollectionViewDelegate, UICollectionViewDataSource, UIAlertViewDelegate, UITextFieldDelegate>
{
    _Bool _isSubmiting;
    UIImage *_screenShotImage;
    id <CTFeedbackQuestionViewProtocol> _delegate;
    UIImageView *_customerServiceImageView;
    UICollectionView *_questionTypeCollectionView;
    UILabel *_descriptionTextViewPlaceHolder;
    UITextView *_descriptionTextView;
    UIImageView *_screenShotImageView;
    UITextField *_contactInfomationTextView;
    UIButton *_submitButton;
    UILabel *_contactLabel;
    NSLayoutConstraint *_questionTypeCollectionViewHeightConstraint;
    NSArray *_questionTypeArray;
    NSLayoutConstraint *_customerServiceButtonHeightConstraint;
    NSLayoutConstraint *_customerServiceButtonTopConstraint;
    NSLayoutConstraint *_viewTopConstraint;
    NSString *_contactText;
    NSString *_feedbackText;
    NSString *_hidedContactText;
    NSString *_currentQuestionType;
}

@property(nonatomic) _Bool isSubmiting; // @synthesize isSubmiting=_isSubmiting;
@property(copy, nonatomic) NSString *currentQuestionType; // @synthesize currentQuestionType=_currentQuestionType;
@property(copy, nonatomic) NSString *hidedContactText; // @synthesize hidedContactText=_hidedContactText;
@property(copy, nonatomic) NSString *feedbackText; // @synthesize feedbackText=_feedbackText;
@property(copy, nonatomic) NSString *contactText; // @synthesize contactText=_contactText;
@property(nonatomic) __weak NSLayoutConstraint *viewTopConstraint; // @synthesize viewTopConstraint=_viewTopConstraint;
@property(nonatomic) __weak NSLayoutConstraint *customerServiceButtonTopConstraint; // @synthesize customerServiceButtonTopConstraint=_customerServiceButtonTopConstraint;
@property(nonatomic) __weak NSLayoutConstraint *customerServiceButtonHeightConstraint; // @synthesize customerServiceButtonHeightConstraint=_customerServiceButtonHeightConstraint;
@property(retain, nonatomic) NSArray *questionTypeArray; // @synthesize questionTypeArray=_questionTypeArray;
@property(nonatomic) __weak NSLayoutConstraint *questionTypeCollectionViewHeightConstraint; // @synthesize questionTypeCollectionViewHeightConstraint=_questionTypeCollectionViewHeightConstraint;
@property(nonatomic) __weak UILabel *contactLabel; // @synthesize contactLabel=_contactLabel;
@property(nonatomic) __weak UIButton *submitButton; // @synthesize submitButton=_submitButton;
@property(nonatomic) __weak UITextField *contactInfomationTextView; // @synthesize contactInfomationTextView=_contactInfomationTextView;
@property(nonatomic) __weak UIImageView *screenShotImageView; // @synthesize screenShotImageView=_screenShotImageView;
@property(nonatomic) __weak UITextView *descriptionTextView; // @synthesize descriptionTextView=_descriptionTextView;
@property(nonatomic) __weak UILabel *descriptionTextViewPlaceHolder; // @synthesize descriptionTextViewPlaceHolder=_descriptionTextViewPlaceHolder;
@property(nonatomic) __weak UICollectionView *questionTypeCollectionView; // @synthesize questionTypeCollectionView=_questionTypeCollectionView;
@property(nonatomic) __weak UIImageView *customerServiceImageView; // @synthesize customerServiceImageView=_customerServiceImageView;
@property(nonatomic) id <CTFeedbackQuestionViewProtocol> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImage *screenShotImage; // @synthesize screenShotImage=_screenShotImage;
- (void).cxx_destruct;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)didClickSubmitButton:(id)arg1;
- (void)didTapCustomerServiceImage:(id)arg1;
- (void)didTapScreenShotImage:(id)arg1;
- (id)modifiedMobileNumberWithStars:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)endEditing:(_Bool)arg1;
- (void)hideCustomerServiceButton;
- (id)init;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

