//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@class FilterGroup, FilterNode, NSMutableArray;
@protocol CTHotelIndividualFilterScrollViewDelegate;

@interface CTHotelIndividualFilterScrollView : UIScrollView
{
    id <CTHotelIndividualFilterScrollViewDelegate> _filterDelegate;
    FilterGroup *_rootGroup;
    FilterNode *_openedNode;
    NSMutableArray *_cachedButtons;
    NSMutableArray *_allButtons;
}

@property(retain, nonatomic) NSMutableArray *allButtons; // @synthesize allButtons=_allButtons;
@property(retain, nonatomic) NSMutableArray *cachedButtons; // @synthesize cachedButtons=_cachedButtons;
@property(retain, nonatomic) FilterNode *openedNode; // @synthesize openedNode=_openedNode;
@property(retain, nonatomic) FilterGroup *rootGroup; // @synthesize rootGroup=_rootGroup;
@property(nonatomic) __weak id <CTHotelIndividualFilterScrollViewDelegate> filterDelegate; // @synthesize filterDelegate=_filterDelegate;
- (void).cxx_destruct;
- (void)buttonTapped:(id)arg1;
- (id)buttonForFilter:(id)arg1;
- (id)createButton;
- (void)refreshScreen;
- (id)initWithFrame:(struct CGRect)arg1;

@end

