//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CTJSONModel.h"

@class NSDictionary, NSString;

@interface CTLocationFencingRequestModel : CTJSONModel
{
    int _CountryId;
    int _CityID;
    NSString *_DeviceToken;
    double _Longitude;
    double _Latitude;
    NSString *_CountryName;
    NSString *_CityName;
    NSDictionary *_ExtendedProperties;
    NSString *_UID;
    NSString *_ClientID;
}

@property(copy, nonatomic) NSString *ClientID; // @synthesize ClientID=_ClientID;
@property(copy, nonatomic) NSString *UID; // @synthesize UID=_UID;
@property(retain, nonatomic) NSDictionary *ExtendedProperties; // @synthesize ExtendedProperties=_ExtendedProperties;
@property(nonatomic) int CityID; // @synthesize CityID=_CityID;
@property(copy, nonatomic) NSString *CityName; // @synthesize CityName=_CityName;
@property(nonatomic) int CountryId; // @synthesize CountryId=_CountryId;
@property(copy, nonatomic) NSString *CountryName; // @synthesize CountryName=_CountryName;
@property(nonatomic) double Latitude; // @synthesize Latitude=_Latitude;
@property(nonatomic) double Longitude; // @synthesize Longitude=_Longitude;
@property(copy, nonatomic) NSString *DeviceToken; // @synthesize DeviceToken=_DeviceToken;
- (void).cxx_destruct;
- (id)init;

@end

