//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CTSender.h"

@interface CTPlatformPiplineRequestSender : CTSender
{
}

+ (id)getInstance;
- (id)sendGetPlatformPiplineResponse:(id)arg1 serviceCode:(id)arg2 requestHead:(id)arg3 requestBody:(id)arg4;

@end

