//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSLayoutConstraint, NSString, UIButton, UILabel;

@interface CTTrainOrderTipsView : UIView <UIGestureRecognizerDelegate>
{
    NSString *_jumpUrlString;
    CDUnknownBlockType _dismissTips;
    CDUnknownBlockType _jump;
    NSLayoutConstraint *_contentViewHeight;
    UILabel *_tipsLabel;
    UIView *_guideView;
    NSLayoutConstraint *_guideViewHeight;
    UIView *_headIconView;
    UIButton *_cancleButton;
    UIButton *_arrgeeButton;
    UIView *_contentView;
    UILabel *_guideTipLabel;
    NSLayoutConstraint *_tipsHeight;
    NSLayoutConstraint *_confirmBtnWidth;
    UIButton *_okButton;
}

@property(nonatomic) __weak UIButton *okButton; // @synthesize okButton=_okButton;
@property(nonatomic) __weak NSLayoutConstraint *confirmBtnWidth; // @synthesize confirmBtnWidth=_confirmBtnWidth;
@property(nonatomic) NSLayoutConstraint *tipsHeight; // @synthesize tipsHeight=_tipsHeight;
@property(nonatomic) UILabel *guideTipLabel; // @synthesize guideTipLabel=_guideTipLabel;
@property(nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) UIButton *arrgeeButton; // @synthesize arrgeeButton=_arrgeeButton;
@property(nonatomic) UIButton *cancleButton; // @synthesize cancleButton=_cancleButton;
@property(nonatomic) UIView *headIconView; // @synthesize headIconView=_headIconView;
@property(nonatomic) NSLayoutConstraint *guideViewHeight; // @synthesize guideViewHeight=_guideViewHeight;
@property(nonatomic) UIView *guideView; // @synthesize guideView=_guideView;
@property(nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(nonatomic) NSLayoutConstraint *contentViewHeight; // @synthesize contentViewHeight=_contentViewHeight;
@property(copy, nonatomic) CDUnknownBlockType jump; // @synthesize jump=_jump;
@property(copy, nonatomic) CDUnknownBlockType dismissTips; // @synthesize dismissTips=_dismissTips;
- (void).cxx_destruct;
- (void)tapAggreeButton:(id)arg1;
- (void)tapCancleButton:(id)arg1;
- (void)tapGuideButton:(id)arg1;
- (void)onTapView:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)configureViewWithTips:(id)arg1 guideButtonString:(id)arg2 CancleText:(id)arg3 ConfirmText:(id)arg4;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

