//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DestinationDBUtil : NSObject
{
}

+ (id)selectCompressFailedUploadVideos;
+ (id)selectUncompleteUploadVideos;
+ (id)selectSpecificUncompleteUploadVideoWithVideoIdentifer:(id)arg1;
+ (_Bool)updateUncompleteUploadVideo:(id)arg1;
+ (_Bool)deleteUncompleteUploadVideo:(id)arg1;
+ (_Bool)insertUncompleteUploadVideo:(id)arg1;
+ (_Bool)addField:(id)arg1 toTable:(id)arg2 withType:(long long)arg3 allowNull:(_Bool)arg4;
+ (_Bool)checkTable:(id)arg1 hasField:(id)arg2;
+ (id)getUserinfoWithUserIDAndCacheAndKey:(id)arg1 cachebean:(id)arg2 itemKey:(id)arg3;
+ (_Bool)updateUserInfo:(id)arg1 cachebean:(id)arg2 itemKey:(id)arg3 itemValue:(id)arg4;
+ (_Bool)addUserInfo:(id)arg1 cachebean:(id)arg2 itemKey:(id)arg3 itemValue:(id)arg4;
+ (id)getItemValueWithUserInfo:(id)arg1 cachebean:(id)arg2 itemKey:(id)arg3;
+ (void)insertQueryHistoryOfCity:(int)arg1 CTDestCityModel:(id)arg2;

@end

