//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CTBusinessBean.h"

@class HotelInsuranceClaimInfo, HotelInsuranceReturnInfo, NSMutableArray, NSString;

@interface HotelInsurancesInformationListItemModel : CTBusinessBean
{
    int _insurancesID;
    int _insurancesType;
    int _flag;
    int _payStatus;
    int _promotionType;
    int _detailID;
    int _providerId;
    NSString *_insurancesName;
    NSString *_insurancesSummary;
    NSString *_productCode;
    NSString *_companyID;
    NSString *_url;
    NSString *_policyholders;
    NSString *_identityType;
    NSString *_identityNo;
    NSString *_birth;
    NSString *_gender;
    NSMutableArray *_costList;
    NSString *_iconUrl;
    HotelInsuranceClaimInfo *_claimInfo;
    NSString *_insurancesSummaryOn;
    NSString *_payStatusDisplay;
    NSString *_payButtonDisplay;
    long long _consumerScore;
    NSString *_insuranceShortDesc;
    NSMutableArray *_promotionPriceList;
    NSString *_typeID;
    HotelInsuranceReturnInfo *_insuranceReturnInfo;
    NSString *_companyName;
}

@property(copy, nonatomic) NSString *companyName; // @synthesize companyName=_companyName;
@property(nonatomic) int providerId; // @synthesize providerId=_providerId;
@property(nonatomic) int detailID; // @synthesize detailID=_detailID;
@property(retain, nonatomic) HotelInsuranceReturnInfo *insuranceReturnInfo; // @synthesize insuranceReturnInfo=_insuranceReturnInfo;
@property(copy, nonatomic) NSString *typeID; // @synthesize typeID=_typeID;
@property(retain, nonatomic) NSMutableArray *promotionPriceList; // @synthesize promotionPriceList=_promotionPriceList;
@property(nonatomic) int promotionType; // @synthesize promotionType=_promotionType;
@property(copy, nonatomic) NSString *insuranceShortDesc; // @synthesize insuranceShortDesc=_insuranceShortDesc;
@property(nonatomic) long long consumerScore; // @synthesize consumerScore=_consumerScore;
@property(nonatomic) int payStatus; // @synthesize payStatus=_payStatus;
@property(copy, nonatomic) NSString *payButtonDisplay; // @synthesize payButtonDisplay=_payButtonDisplay;
@property(copy, nonatomic) NSString *payStatusDisplay; // @synthesize payStatusDisplay=_payStatusDisplay;
@property(copy, nonatomic) NSString *insurancesSummaryOn; // @synthesize insurancesSummaryOn=_insurancesSummaryOn;
@property(retain, nonatomic) HotelInsuranceClaimInfo *claimInfo; // @synthesize claimInfo=_claimInfo;
@property(copy, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(retain, nonatomic) NSMutableArray *costList; // @synthesize costList=_costList;
@property(copy, nonatomic) NSString *gender; // @synthesize gender=_gender;
@property(copy, nonatomic) NSString *birth; // @synthesize birth=_birth;
@property(copy, nonatomic) NSString *identityNo; // @synthesize identityNo=_identityNo;
@property(copy, nonatomic) NSString *identityType; // @synthesize identityType=_identityType;
@property(copy, nonatomic) NSString *policyholders; // @synthesize policyholders=_policyholders;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) int flag; // @synthesize flag=_flag;
@property(copy, nonatomic) NSString *companyID; // @synthesize companyID=_companyID;
@property(copy, nonatomic) NSString *productCode; // @synthesize productCode=_productCode;
@property(copy, nonatomic) NSString *insurancesSummary; // @synthesize insurancesSummary=_insurancesSummary;
@property(copy, nonatomic) NSString *insurancesName; // @synthesize insurancesName=_insurancesName;
@property(nonatomic) int insurancesType; // @synthesize insurancesType=_insurancesType;
@property(nonatomic) int insurancesID; // @synthesize insurancesID=_insurancesID;
- (void).cxx_destruct;
- (id)getPBAnnotationArray;
- (id)init;

@end

