//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DYMNetWorkRequestParam, NSMutableArray;

@interface DayimaAPIParams : NSObject
{
    _Bool has_file;
    NSMutableArray *_array;
    DYMNetWorkRequestParam *_requestParam;
}

+ (id)params;
@property(retain, nonatomic) DYMNetWorkRequestParam *requestParam; // @synthesize requestParam=_requestParam;
- (void).cxx_destruct;
- (id)params;
- (id)description;
- (id)objectAtIndex:(unsigned long long)arg1;
- (unsigned long long)count;
- (_Bool)hasFileParams;
- (void)addParams:(id)arg1;
- (void)addFile:(id)arg1 dataParam:(id)arg2 withName:(id)arg3;
- (void)addFileParam:(id)arg1 withName:(id)arg2;
- (void)addParam:(id)arg1 withName:(id)arg2;
- (id)init;

@end

