//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class CALayer, UILabel;

@interface HistorySearchCollectionCell : UICollectionViewCell
{
    UILabel *_historyLabel;
    CALayer *_lineView;
}

@property(nonatomic) __weak CALayer *lineView; // @synthesize lineView=_lineView;
@property(nonatomic) __weak UILabel *historyLabel; // @synthesize historyLabel=_historyLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)historyModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

