//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DUIViewController.h"

@class NSMutableArray, UIScrollView;

@interface InvalidController : DUIViewController
{
    UIScrollView *_scrollView;
    NSMutableArray *_itemList;
    int _type;
}

- (void).cxx_destruct;
- (void)addItemQuestion:(id)arg1;
- (void)addItemAnswer:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)layoutYunqi;
- (void)layoutPeriod;
- (void)viewDidLoad;
- (id)initWithType:(int)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

