//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSError, NSString, NSURLRequest;

@interface HNTVRequestFailedInfo : NSObject <NSCopying>
{
    NSURLRequest *_failedRequest;
    NSString *_httpCode;
    NSError *_error;
}

@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSString *httpCode; // @synthesize httpCode=_httpCode;
@property(retain, nonatomic) NSURLRequest *failedRequest; // @synthesize failedRequest=_failedRequest;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

