//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "EssayMobileViewController.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString, SSThemedButton, UIImageView, UITextField;

@interface EssayMobileSettingViewController : EssayMobileViewController <UIImagePickerControllerDelegate, UINavigationControllerDelegate, UIActionSheetDelegate, UIAlertViewDelegate>
{
    SSThemedButton *_avatarButton;
    UIImageView *_avatarView;
    UITextField *_userNameTextField;
}

@property(nonatomic) __weak UITextField *userNameTextField; // @synthesize userNameTextField=_userNameTextField;
@property(nonatomic) __weak UIImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(nonatomic) __weak SSThemedButton *avatarButton; // @synthesize avatarButton=_avatarButton;
- (void).cxx_destruct;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)registerNotification;
- (int)nameCharacterLength:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)finishUserName;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)updateUserFinished:(id)arg1;
- (void)finishButtonClicked:(id)arg1;
- (void)avatarButtonClicked:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

