//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DownloadDuringTimeAPMBLL : NSObject
{
}

+ (id)createDownloadSheetBussinessData:(id)arg1;
+ (id)createBussinessData:(id)arg1;
+ (void)endDownSheetDuringApm:(id)arg1 error:(id)arg2;
+ (void)midDownSheetDuringApm:(id)arg1 apmInfo:(id)arg2;
+ (id)startDownSheetDuringApm;
+ (void)endDownDuringApm:(id)arg1 error:(id)arg2 APMTypeIDs:(int)arg3;
+ (void)midDownDuringApm:(id)arg1 apmInfo:(id)arg2 APMTypeIDs:(int)arg3;
+ (id)startDownDuringApmWithAPMTypeIDs:(int)arg1;
+ (void)endMVDownDuringApm:(id)arg1 error:(id)arg2;
+ (void)midMVDownDuringApm:(id)arg1 apmInfo:(id)arg2;
+ (id)startMVDownDuringApm;
+ (void)endSongDownDuringApm:(id)arg1 error:(id)arg2;
+ (void)midSongDownDuringApm:(id)arg1 apmInfo:(id)arg2;
+ (id)startSongDownDuringApm;

@end

