//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KGScrollManagerViewController.h"

@interface EQMoreScrollManagerViewController : KGScrollManagerViewController
{
    unsigned long long _defaultTab;
    CDUnknownBlockType _useEqBlock;
}

@property(copy, nonatomic) CDUnknownBlockType useEqBlock; // @synthesize useEqBlock=_useEqBlock;
@property(nonatomic) unsigned long long defaultTab; // @synthesize defaultTab=_defaultTab;
- (void).cxx_destruct;
- (long long)showPlayBarWay;
- (void)dealloc;
- (void)didSelectTabItemIndex:(unsigned long long)arg1;
- (void)jumpToUploadPage;
- (void)uploadAction:(id)arg1;
- (void)createViewIn;
- (void)backgroundAndTopViewColorInit;
- (void)viewInit;
- (void)viewDidLoad;

@end

