//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FAModel.h"

@class NSString;

@interface FALCNewTagsAnimationInfoModel : FAModel
{
    NSString *_tagName;
    NSString *_congratulationTitle;
    NSString *_nickName;
    NSString *_guideContent;
}

@property(copy, nonatomic) NSString *guideContent; // @synthesize guideContent=_guideContent;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(copy, nonatomic) NSString *congratulationTitle; // @synthesize congratulationTitle=_congratulationTitle;
@property(copy, nonatomic) NSString *tagName; // @synthesize tagName=_tagName;
- (void).cxx_destruct;

@end

