//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FAViewModelObject.h"

@class FALiveNormalRoomInfo, NSString;

@interface FALiveKglConcertInfo : FAViewModelObject
{
    NSString *_des;
    NSString *_desImg;
    NSString *_desColor;
    NSString *_rankPedant;
    long long _roomId;
    NSString *_shareContent;
    NSString *_shareImg;
    NSString *_shareTitle;
    NSString *_title;
    NSString *_columnLogo;
    long long _concertId;
    NSString *_logo;
    long long _streamType;
    FALiveNormalRoomInfo *_normalRoomInfo;
}

@property(retain, nonatomic) FALiveNormalRoomInfo *normalRoomInfo; // @synthesize normalRoomInfo=_normalRoomInfo;
@property(nonatomic) long long streamType; // @synthesize streamType=_streamType;
@property(copy, nonatomic) NSString *logo; // @synthesize logo=_logo;
@property(nonatomic) long long concertId; // @synthesize concertId=_concertId;
@property(copy, nonatomic) NSString *columnLogo; // @synthesize columnLogo=_columnLogo;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *shareTitle; // @synthesize shareTitle=_shareTitle;
@property(copy, nonatomic) NSString *shareImg; // @synthesize shareImg=_shareImg;
@property(copy, nonatomic) NSString *shareContent; // @synthesize shareContent=_shareContent;
@property(nonatomic) long long roomId; // @synthesize roomId=_roomId;
@property(copy, nonatomic) NSString *rankPedant; // @synthesize rankPedant=_rankPedant;
@property(copy, nonatomic) NSString *desColor; // @synthesize desColor=_desColor;
@property(copy, nonatomic) NSString *desImg; // @synthesize desImg=_desImg;
@property(copy, nonatomic) NSString *des; // @synthesize des=_des;
- (void).cxx_destruct;
- (id)chatInfoString;
- (id)cardInfoString;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)concertInfo:(long long)arg1;

@end

