//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface KMMusicClassfiyRecommendModel : NSObject
{
    NSArray *_info;
    long long _timestamp;
}

+ (id)modelContainerPropertyGenericClass;
@property(nonatomic) long long timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) NSArray *info; // @synthesize info=_info;
- (void).cxx_destruct;

@end

