//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KTVObjectModel.h"

@class NSString;

@interface KTVBannerInfo : KTVObjectModel
{
    long long _id;
    long long _activityId;
    long long _status;
    long long _type;
    long long _weight;
    NSString *_bannerUrl;
    NSString *_content;
}

@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *bannerUrl; // @synthesize bannerUrl=_bannerUrl;
@property(nonatomic) long long weight; // @synthesize weight=_weight;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic) long long activityId; // @synthesize activityId=_activityId;
@property(nonatomic) long long id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

