//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class KTVThemeButton, KTVThemeImageView, KTVThemeLabel, KTV_SongInfo, UIButton, UIImageView;
@protocol KTVSingleAccHeaderViewDelegate;

@interface KTVSingleAccHeaderView : UIView
{
    KTV_SongInfo *_songInfo;
    id <KTVSingleAccHeaderViewDelegate> _eventDelegate;
    CDUnknownBlockType _songBlock;
    UIImageView *_titleBg;
    UIImageView *_head;
    UIView *_songDetailContent;
    KTVThemeLabel *_songLabel;
    UIImageView *_canScoreImg;
    KTVThemeLabel *_singerNameLabel;
    KTVThemeLabel *_sizeLabel;
    KTVThemeImageView *_earthImgView;
    KTVThemeLabel *_earthLabel;
    UIView *_rightBtnContent;
    KTVThemeButton *_singBtn;
    UIButton *_qingBtn;
}

@property(retain, nonatomic) UIButton *qingBtn; // @synthesize qingBtn=_qingBtn;
@property(retain, nonatomic) KTVThemeButton *singBtn; // @synthesize singBtn=_singBtn;
@property(retain, nonatomic) UIView *rightBtnContent; // @synthesize rightBtnContent=_rightBtnContent;
@property(retain, nonatomic) KTVThemeLabel *earthLabel; // @synthesize earthLabel=_earthLabel;
@property(retain, nonatomic) KTVThemeImageView *earthImgView; // @synthesize earthImgView=_earthImgView;
@property(retain, nonatomic) KTVThemeLabel *sizeLabel; // @synthesize sizeLabel=_sizeLabel;
@property(retain, nonatomic) KTVThemeLabel *singerNameLabel; // @synthesize singerNameLabel=_singerNameLabel;
@property(retain, nonatomic) UIImageView *canScoreImg; // @synthesize canScoreImg=_canScoreImg;
@property(retain, nonatomic) KTVThemeLabel *songLabel; // @synthesize songLabel=_songLabel;
@property(retain, nonatomic) UIView *songDetailContent; // @synthesize songDetailContent=_songDetailContent;
@property(retain, nonatomic) UIImageView *head; // @synthesize head=_head;
@property(retain, nonatomic) UIImageView *titleBg; // @synthesize titleBg=_titleBg;
@property(copy, nonatomic) CDUnknownBlockType songBlock; // @synthesize songBlock=_songBlock;
@property(nonatomic) __weak id <KTVSingleAccHeaderViewDelegate> eventDelegate; // @synthesize eventDelegate=_eventDelegate;
@property(retain, nonatomic) KTV_SongInfo *songInfo; // @synthesize songInfo=_songInfo;
- (void).cxx_destruct;
- (void)singBtnAction;
- (void)rightBtnAction:(unsigned long long)arg1;
- (void)layoutSubviews;
- (void)configureForBounds;
- (id)initWithFrame:(struct CGRect)arg1;

@end

