//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KTVSimpleTableViewController.h"

#import "UISearchBarDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"
#import "UserRelationTableViewCellDelegate-Protocol.h"

@class NSString, UISearchBar, UISearchDisplayController, UserSearchResultProvider;

@interface FollowListViewController : KTVSimpleTableViewController <UISearchDisplayDelegate, UISearchBarDelegate, UserRelationTableViewCellDelegate>
{
    long long _userid;
    UISearchDisplayController *_aSearchDisplayController;
    UISearchBar *_searchBar;
    UserSearchResultProvider *_userSearchResultProvider;
}

@property(retain, nonatomic) UserSearchResultProvider *userSearchResultProvider; // @synthesize userSearchResultProvider=_userSearchResultProvider;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UISearchDisplayController *aSearchDisplayController; // @synthesize aSearchDisplayController=_aSearchDisplayController;
@property(nonatomic) long long userid; // @synthesize userid=_userid;
- (void).cxx_destruct;
- (id)getStatisticContentWithRelationUser:(id)arg1;
- (void)userRelationTableView:(id)arg1 cell:(id)arg2 follwUser:(id)arg3;
- (void)showFindFriendsViewController;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchScope:(long long)arg2;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)loadDataWithSuccess:(CDUnknownBlockType)arg1 offset:(long long)arg2 limit:(long long)arg3;
- (Class)classForCell;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

