//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@interface KTVUserEvent : MTLModel <MTLJSONSerializing>
{
    long long _competitionVersion;
    long long _familyRemindCount;
    long long _friendFeedCount;
    long long _gameRemindCount;
    long long _newDuetInvitationCount;
    long long _newFansCount;
    long long _newFollowWorkCount;
    long long _newMessageCount;
    long long _newNoticeCount;
    long long _recentVisitorCount;
}

+ (id)newFollowWorkCountJSONTransformer;
+ (id)friendFeedCountJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) long long recentVisitorCount; // @synthesize recentVisitorCount=_recentVisitorCount;
@property(nonatomic) long long newNoticeCount; // @synthesize newNoticeCount=_newNoticeCount;
@property(nonatomic) long long newMessageCount; // @synthesize newMessageCount=_newMessageCount;
@property(nonatomic) long long newFollowWorkCount; // @synthesize newFollowWorkCount=_newFollowWorkCount;
@property(nonatomic) long long newFansCount; // @synthesize newFansCount=_newFansCount;
@property(nonatomic) long long newDuetInvitationCount; // @synthesize newDuetInvitationCount=_newDuetInvitationCount;
@property(nonatomic) long long gameRemindCount; // @synthesize gameRemindCount=_gameRemindCount;
@property(nonatomic) long long friendFeedCount; // @synthesize friendFeedCount=_friendFeedCount;
@property(nonatomic) long long familyRemindCount; // @synthesize familyRemindCount=_familyRemindCount;
@property(nonatomic) long long competitionVersion; // @synthesize competitionVersion=_competitionVersion;

@end

