//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class KTVImageView, KTVRecommendUser, NSLayoutConstraint, UIButton, UIImageView, UILabel, VipNicknameLabel;

@interface RecommendTableViewCell : UITableViewCell
{
    _Bool _isPlaying;
    KTVImageView *_peopleImageView;
    VipNicknameLabel *_peopleNicknameLabel;
    UIButton *_followButton;
    UIButton *_playButton;
    UIImageView *_commentBackgroundImageView;
    UILabel *_commentLabel;
    UILabel *_reasonLabel;
    KTVRecommendUser *_user;
    NSLayoutConstraint *_followButtonWidthConstraint;
    NSLayoutConstraint *_resonLabelToTopConstraint;
    UIImageView *_vipIconImageView;
    UILabel *_vipTitleLabel;
    NSLayoutConstraint *_playButtonTopConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *playButtonTopConstraint; // @synthesize playButtonTopConstraint=_playButtonTopConstraint;
@property(nonatomic) __weak UILabel *vipTitleLabel; // @synthesize vipTitleLabel=_vipTitleLabel;
@property(nonatomic) __weak UIImageView *vipIconImageView; // @synthesize vipIconImageView=_vipIconImageView;
@property(retain, nonatomic) NSLayoutConstraint *resonLabelToTopConstraint; // @synthesize resonLabelToTopConstraint=_resonLabelToTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *followButtonWidthConstraint; // @synthesize followButtonWidthConstraint=_followButtonWidthConstraint;
@property(retain, nonatomic) KTVRecommendUser *user; // @synthesize user=_user;
@property(nonatomic) _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
@property(retain, nonatomic) UILabel *reasonLabel; // @synthesize reasonLabel=_reasonLabel;
@property(retain, nonatomic) UILabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(retain, nonatomic) UIImageView *commentBackgroundImageView; // @synthesize commentBackgroundImageView=_commentBackgroundImageView;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) UIButton *followButton; // @synthesize followButton=_followButton;
@property(retain, nonatomic) VipNicknameLabel *peopleNicknameLabel; // @synthesize peopleNicknameLabel=_peopleNicknameLabel;
@property(retain, nonatomic) KTVImageView *peopleImageView; // @synthesize peopleImageView=_peopleImageView;
- (void).cxx_destruct;
- (void)followButtonTapped:(id)arg1;
- (void)peopleImageButtonTapped;
- (void)refreshFollowButton:(long long)arg1;
- (void)configCellWithData:(id)arg1;
- (void)setUnfollowedState:(id)arg1;
- (void)setFollowedState:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)dealloc;
- (void)awakeFromNib;

@end

