//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "APNSUtilDelegate-Protocol.h"
#import "FeedbackTextViewDelegate-Protocol.h"
#import "MTViewModelDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class FeedbackTextView, FeedbackViewModel, MTProgressTipView, NSLayoutConstraint, NSString, UIAlertView, UIButton, UINavigationItem, UITableView, UITextField, UIView;

@interface FeedBackViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, FeedbackTextViewDelegate, UITextFieldDelegate, MTViewModelDelegate, APNSUtilDelegate>
{
    double _cellAndKeydistance;
    UIButton *_sendBtn;
    _Bool _hideContactView;
    _Bool _isWordNumAlertExit;
    FeedbackViewModel *_viewModel;
    UIView *_topBar;
    UINavigationItem *_navBarItem;
    UITableView *_tableView;
    UIView *_contactView;
    UITextField *_contactTextField;
    NSLayoutConstraint *_contactViewTopSpace;
    NSLayoutConstraint *_topbarHeight;
    FeedbackTextView *_feedbackTextView;
    NSLayoutConstraint *_feedbackTextViewBottomLayout;
    MTProgressTipView *_progressTipView;
    UIAlertView *_debugAlert;
}

+ (id)defaultStoryBoardName;
@property(retain, nonatomic) UIAlertView *debugAlert; // @synthesize debugAlert=_debugAlert;
@property(retain, nonatomic) MTProgressTipView *progressTipView; // @synthesize progressTipView=_progressTipView;
@property(nonatomic) _Bool isWordNumAlertExit; // @synthesize isWordNumAlertExit=_isWordNumAlertExit;
@property(nonatomic) _Bool hideContactView; // @synthesize hideContactView=_hideContactView;
@property(nonatomic) __weak NSLayoutConstraint *feedbackTextViewBottomLayout; // @synthesize feedbackTextViewBottomLayout=_feedbackTextViewBottomLayout;
@property(nonatomic) __weak FeedbackTextView *feedbackTextView; // @synthesize feedbackTextView=_feedbackTextView;
@property(nonatomic) __weak NSLayoutConstraint *topbarHeight; // @synthesize topbarHeight=_topbarHeight;
@property(nonatomic) __weak NSLayoutConstraint *contactViewTopSpace; // @synthesize contactViewTopSpace=_contactViewTopSpace;
@property(nonatomic) __weak UITextField *contactTextField; // @synthesize contactTextField=_contactTextField;
@property(nonatomic) __weak UIView *contactView; // @synthesize contactView=_contactView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UINavigationItem *navBarItem; // @synthesize navBarItem=_navBarItem;
@property(nonatomic) __weak UIView *topBar; // @synthesize topBar=_topBar;
@property(retain, nonatomic) FeedbackViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)showToastWith:(id)arg1 showTime:(int)arg2;
- (void)dataDidChange:(id)arg1;
- (void)didReceivePayload:(id)arg1;
- (void)showAlertViewWithMessage:(id)arg1 handleButtonClicked:(CDUnknownBlockType)arg2;
- (void)showWordsNumMoreThanCommand;
- (void)showContentIsEmptyAlert;
- (void)showNoMoreContentAlert;
- (void)showEmptyContactAlert;
- (id)getFormateTimeString;
- (_Bool)isNullOrEmptyString:(id)arg1;
- (void)hideKeyBoard;
- (void)addGestrue;
- (void)scrollToBottomCell;
- (void)keyBoardWillHide:(id)arg1;
- (void)keyBoardWillShow:(id)arg1;
- (void)didClickSend:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)submitActionWithContent:(id)arg1 contact:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)requestData;
- (void)messageSendSuccess:(id)arg1;
- (void)pullAppendCell;
- (void)setupView;
- (void)setupLocalData;
- (void)sendAction:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)doResend:(id)arg1;
- (void)actionBack:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)showDebugMenu;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

