//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;

@interface SNMPTMMultSelectFilterValueDTO : NSObject
{
    NSArray *_sizeList;
    NSArray *_colorList;
    long long _commodityCount;
    NSArray *_typeList;
    NSArray *_applicateList;
    long long _bomSwitch;
}

+ (id)modelContainerPropertyGenericClass;
@property(nonatomic) long long bomSwitch; // @synthesize bomSwitch=_bomSwitch;
@property(retain, nonatomic) NSArray *applicateList; // @synthesize applicateList=_applicateList;
@property(retain, nonatomic) NSArray *typeList; // @synthesize typeList=_typeList;
@property(nonatomic) long long commodityCount; // @synthesize commodityCount=_commodityCount;
@property(retain, nonatomic) NSArray *colorList; // @synthesize colorList=_colorList;
@property(retain, nonatomic) NSArray *sizeList; // @synthesize sizeList=_sizeList;
- (void).cxx_destruct;

@end

