//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIPickerViewDataSource-Protocol.h"
#import "UIPickerViewDelegate-Protocol.h"

@class NSArray, NSString, SNLeftRightToolBar, SNSLZSDDTO, SNSLZSDInterval, UILabel, UIPickerView;

@interface SNSLTimePickerView : UIView <UIPickerViewDelegate, UIPickerViewDataSource>
{
    long long _origalSelectButtonIndex;
    long long _origalRowLeft;
    long long _origalRowRight;
    long long _selectButtonIndex;
    long long _rowLeft;
    long long _rowRight;
    _Bool notNeedRefreshOrigal;
    UILabel *_installLabel;
    _Bool _needToolBar;
    _Bool _isInsatll;
    _Bool _isInsatllLater;
    NSString *_selectDateStr;
    NSString *_selectZSDDateStr;
    NSArray *_selectButtonArr;
    NSArray *_timesArr;
    NSArray *_dateArr;
    NSArray *_zsdTimeArray;
    SNSLZSDDTO *_selectedZSDDTO;
    SNSLZSDInterval *_selectedZSDInterval;
    CDUnknownBlockType _changSendTypeBlock;
    UIPickerView *_pickerView;
    NSArray *_timeArray;
    NSString *_dateStr;
    SNLeftRightToolBar *_sementView;
    NSString *_zsdDateStr;
}

@property(retain, nonatomic) NSString *zsdDateStr; // @synthesize zsdDateStr=_zsdDateStr;
@property(retain, nonatomic) SNLeftRightToolBar *sementView; // @synthesize sementView=_sementView;
@property(retain, nonatomic) NSString *dateStr; // @synthesize dateStr=_dateStr;
@property(retain, nonatomic) NSArray *timeArray; // @synthesize timeArray=_timeArray;
@property(retain, nonatomic) UIPickerView *pickerView; // @synthesize pickerView=_pickerView;
@property(copy, nonatomic) CDUnknownBlockType changSendTypeBlock; // @synthesize changSendTypeBlock=_changSendTypeBlock;
@property(nonatomic) _Bool isInsatllLater; // @synthesize isInsatllLater=_isInsatllLater;
@property(nonatomic) _Bool isInsatll; // @synthesize isInsatll=_isInsatll;
@property(nonatomic) _Bool needToolBar; // @synthesize needToolBar=_needToolBar;
@property(retain, nonatomic) SNSLZSDInterval *selectedZSDInterval; // @synthesize selectedZSDInterval=_selectedZSDInterval;
@property(retain, nonatomic) SNSLZSDDTO *selectedZSDDTO; // @synthesize selectedZSDDTO=_selectedZSDDTO;
@property(retain, nonatomic) NSArray *zsdTimeArray; // @synthesize zsdTimeArray=_zsdTimeArray;
@property(retain, nonatomic) NSArray *dateArr; // @synthesize dateArr=_dateArr;
@property(retain, nonatomic) NSArray *timesArr; // @synthesize timesArr=_timesArr;
@property(retain, nonatomic) NSArray *selectButtonArr; // @synthesize selectButtonArr=_selectButtonArr;
@property(retain, nonatomic) NSString *selectZSDDateStr; // @synthesize selectZSDDateStr=_selectZSDDateStr;
@property(retain, nonatomic) NSString *selectDateStr; // @synthesize selectDateStr=_selectDateStr;
@property(nonatomic) long long selectButtonIndex; // @synthesize selectButtonIndex=_selectButtonIndex;
- (void).cxx_destruct;
- (void)createInstallLabel;
- (void)choiceTakeWag:(unsigned long long)arg1;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (double)pickerView:(id)arg1 widthForComponent:(long long)arg2;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)prepareShowTime;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

