//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YFBCommonDTO.h"

@class NSString;

@interface YFBRechargeItemDTO : YFBCommonDTO
{
    NSString *_appFunctionCode;
    NSString *_appFunctionName;
    NSString *_detailTitle;
    NSString *_iconImageName;
    NSString *_iconImageUrlStr;
    NSString *_cornerImageUrlStr;
    NSString *_contentUrlStr;
    NSString *_appFunction;
    NSString *_joinType;
    NSString *_islogin;
    NSString *_signTime;
}

@property(retain, nonatomic) NSString *signTime; // @synthesize signTime=_signTime;
@property(retain, nonatomic) NSString *islogin; // @synthesize islogin=_islogin;
@property(retain, nonatomic) NSString *joinType; // @synthesize joinType=_joinType;
@property(retain, nonatomic) NSString *appFunction; // @synthesize appFunction=_appFunction;
@property(retain, nonatomic) NSString *contentUrlStr; // @synthesize contentUrlStr=_contentUrlStr;
@property(retain, nonatomic) NSString *cornerImageUrlStr; // @synthesize cornerImageUrlStr=_cornerImageUrlStr;
@property(retain, nonatomic) NSString *iconImageUrlStr; // @synthesize iconImageUrlStr=_iconImageUrlStr;
@property(retain, nonatomic) NSString *iconImageName; // @synthesize iconImageName=_iconImageName;
@property(retain, nonatomic) NSString *detailTitle; // @synthesize detailTitle=_detailTitle;
@property(retain, nonatomic) NSString *appFunctionName; // @synthesize appFunctionName=_appFunctionName;
@property(retain, nonatomic) NSString *appFunctionCode; // @synthesize appFunctionCode=_appFunctionCode;
- (void).cxx_destruct;
- (void)encodeFromDictionary:(id)arg1;

@end

