//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "COBaseResult.h"

@class NSDictionary, NSNumber;

@interface COFreightServiceFeeResult : COBaseResult
{
    NSNumber *_serviceFeeAll;
    NSNumber *_orderPrice;
    NSDictionary *_freightServiceVender;
}

@property(retain, nonatomic) NSDictionary *freightServiceVender; // @synthesize freightServiceVender=_freightServiceVender;
@property(retain, nonatomic) NSNumber *orderPrice; // @synthesize orderPrice=_orderPrice;
@property(retain, nonatomic) NSNumber *serviceFeeAll; // @synthesize serviceFeeAll=_serviceFeeAll;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1 error:(id *)arg2;

@end

