//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <OTSBase/OTSTableViewCell.h>

#import "NICell-Protocol.h"
#import "ScratchMaskImageViewDelegate-Protocol.h"

@class NSString, OTSLuckDrawMessageVO, OTSScratchCardResultView, ScratchMaskImageView, UIActivityIndicatorView, UIButton, UIImageView;

@interface OTSOKOrderLuckdrawCell : OTSTableViewCell <ScratchMaskImageViewDelegate, NICell>
{
    UIActivityIndicatorView *_loadingView;
    OTSScratchCardResultView *_resultView;
    ScratchMaskImageView *_scratchMaskView;
    UIImageView *_backImgView;
    UIButton *_ruleBtn;
    CDUnknownBlockType _aBlock;
    OTSLuckDrawMessageVO *_msgVo;
}

+ (double)heightForObject:(id)arg1 atIndexPath:(id)arg2 tableView:(id)arg3;
@property(retain, nonatomic) OTSLuckDrawMessageVO *msgVo; // @synthesize msgVo=_msgVo;
@property(copy, nonatomic) CDUnknownBlockType aBlock; // @synthesize aBlock=_aBlock;
@property(retain, nonatomic) UIButton *ruleBtn; // @synthesize ruleBtn=_ruleBtn;
@property(retain, nonatomic) UIImageView *backImgView; // @synthesize backImgView=_backImgView;
@property(retain, nonatomic) ScratchMaskImageView *scratchMaskView; // @synthesize scratchMaskView=_scratchMaskView;
@property(retain, nonatomic) OTSScratchCardResultView *resultView; // @synthesize resultView=_resultView;
@property(retain, nonatomic) UIActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
- (void).cxx_destruct;
- (_Bool)shouldUpdateCellWithObject:(id)arg1;
- (void)jumpContentUrl;
- (void)showRuleContent;
- (void)uncoverBlessing:(struct CGPoint)arg1;
- (void)scratchCartEnd;
- (void)scratchCartBegin:(struct CGPoint)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

