//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OTSProductBaseTVCell.h"

#import "OTSCustomTextViewDelegate-Protocol.h"

@class NSString, OTSProductTitleTVCellObject, UILabel, UITextView;

@interface OTSProductTitleTVCell : OTSProductBaseTVCell <OTSCustomTextViewDelegate>
{
    UILabel *_tagLabel;
    UITextView *_titleView;
    OTSProductTitleTVCellObject *_cellObject;
}

@property(retain, nonatomic) OTSProductTitleTVCellObject *cellObject; // @synthesize cellObject=_cellObject;
@property(retain, nonatomic) UITextView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
- (void).cxx_destruct;
- (_Bool)shouldUpdateCellWithObject:(id)arg1;
- (void)addLayoutConstraint;
- (void)initUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

