//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface LinePaymentReservation : NSObject
{
    NSString *__receiverMid;
    NSString *__productId;
    NSString *__language;
    NSString *__location;
    NSString *__currency;
    NSString *__price;
    long long __appStoreCode;
    NSString *__messageText;
    int __messageTemplate;
    long long __packageId;
    struct {
        unsigned int receiverMid:1;
        unsigned int productId:1;
        unsigned int language:1;
        unsigned int location:1;
        unsigned int currency:1;
        unsigned int price:1;
        unsigned int appStoreCode:1;
        unsigned int messageText:1;
        unsigned int messageTemplate:1;
        unsigned int packageId:1;
    } __isSet;
}

@property(nonatomic) long long packageId; // @synthesize packageId=__packageId;
@property(nonatomic) int messageTemplate; // @synthesize messageTemplate=__messageTemplate;
@property(copy, nonatomic) NSString *messageText; // @synthesize messageText=__messageText;
@property(nonatomic) long long appStoreCode; // @synthesize appStoreCode=__appStoreCode;
@property(copy, nonatomic) NSString *price; // @synthesize price=__price;
@property(copy, nonatomic) NSString *currency; // @synthesize currency=__currency;
@property(copy, nonatomic) NSString *location; // @synthesize location=__location;
@property(copy, nonatomic) NSString *language; // @synthesize language=__language;
@property(retain, nonatomic) NSString *productId; // @synthesize productId=__productId;
@property(retain, nonatomic) NSString *receiverMid; // @synthesize receiverMid=__receiverMid;
- (void).cxx_destruct;
- (void)write:(id)arg1;
- (void)read:(id)arg1;

@end

