//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, NSTimer, NeloHandle, NeloTBinaryProtocol, NeloTFramedTransport, NeloTSocketClient, ThriftNeloEventServerClient;

@interface NeloLogInstance : NSObject
{
    _Bool ls_isInit;
    _Bool ls_httpsEnabled;
    _Bool isSendSessionLog;
    NeloHandle *ls_handle;
    NSString *collectorUrl;
    long long collectorPort;
    long long sendProtocol;
    NeloTSocketClient *socket;
    NeloTFramedTransport *transport;
    NeloTBinaryProtocol *neloProtocol;
    ThriftNeloEventServerClient *neloClient;
    NSTimer *closeSocketTimer;
}

- (void).cxx_destruct;
- (id)getHost;
- (id)getNetworkString:(id)arg1;
- (id)getIPAddress;
- (_Bool)isStringEmpty:(id)arg1;
- (id)generateUUID;
- (_Bool)isValidVersion:(id)arg1;
- (_Bool)isValidField:(id)arg1;
- (void)sendLog:(id)arg1 withLogLevel:(id)arg2 errorCode:(id)arg3 withMessage:(id)arg4 atLocation:(id)arg5;
- (void)sendLog:(id)arg1 withLogLevel:(id)arg2 errorCode:(id)arg3 withMessage:(id)arg4 atLocation:(id)arg5 withException:(id)arg6;
- (_Bool)sendLog:(id)arg1;
- (_Bool)initNeloClient:(id)arg1 withPort:(int)arg2;
- (_Bool)initNeloClient;
- (id)getTimer;
- (void)timerReset;
- (void)copyCommonFields:(id)arg1;
- (void)setLogSource:(id)arg1;
- (void)setLogType:(id)arg1;
- (void)setUserId:(id)arg1;
- (void)setNeloSendMode:(id)arg1;
- (void)setLogLevelFilter:(id)arg1;
- (void)startNeloSession:(_Bool)arg1;
- (void)setCustomField:(id)arg1 forKey:(id)arg2;
- (void)removeCustomFieldForKey:(id)arg1;
- (void)removeAllCustomFields;
- (id)appInstallFilePath;
- (_Bool)init:(id)arg1 ofServer:(id)arg2 onPort:(int)arg3 byProtocol:(long long)arg4 ofProjectName:(id)arg5 withProjectVersion:(id)arg6 forUserId:(id)arg7;
- (_Bool)clsoeNeloClient;
- (_Bool)init:(id)arg1 onPort:(int)arg2 byProtocol:(long long)arg3 ofProjectName:(id)arg4 withProjectVersion:(id)arg5 forUserId:(id)arg6;
- (_Bool)init:(id)arg1 onPort:(int)arg2 ofProjectName:(id)arg3 withProjectVersion:(id)arg4 forUserId:(id)arg5;
- (_Bool)init:(id)arg1 onPort:(int)arg2 ofProjectName:(id)arg3 withProjectVersion:(id)arg4;
- (id)init;

@end

