//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSManagedObject;
@protocol ChatProtocol;

@interface NLChatActivitySettingLogicController : NSObject
{
    struct NSManagedObject *_chat;
}

@property(retain, nonatomic) NSManagedObject<ChatProtocol> *chat; // @synthesize chat=_chat;
- (void).cxx_destruct;
- (void)deleteSquareChat:(CDUnknownBlockType)arg1;
- (void)leaveGroup:(CDUnknownBlockType)arg1;
- (void)clearChatHistory:(CDUnknownBlockType)arg1;
- (id)initWithChat:(struct NSManagedObject *)arg1;

@end

