//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NLSearchBar;

@interface NLMessageSearchTitleBar : UIView
{
    // Error parsing type: , name: backgroundView
    // Error parsing type: , name: searchBar
    // Error parsing type: , name: keyboardFrameObservingView
    // Error parsing type: , name: delegate
}

- (CDUnknownBlockType).cxx_destruct;
- (_Bool)render;
- (void)configureTheme;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) NLSearchBar *searchBar; // @synthesize searchBar;

@end

