//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ATMonthOrderModel, NSString;

@interface ATOneOnOnePayViewModel : NSObject
{
    NSString *_orderId;
    ATMonthOrderModel *_packageInfo;
}

@property(retain, nonatomic) ATMonthOrderModel *packageInfo; // @synthesize packageInfo=_packageInfo;
@property(retain, nonatomic) NSString *orderId; // @synthesize orderId=_orderId;
- (void).cxx_destruct;
- (void)checkPayStatusForPayId:(id)arg1 status:(long long)arg2 block:(CDUnknownBlockType)arg3;
- (void)getPayInfoForOrderId:(id)arg1 payType:(long long)arg2 coupon:(id)arg3 block:(CDUnknownBlockType)arg4;
- (void)getPackageInfoForOrderId:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)packageInfoDidLoad:(id)arg1;
- (id)payTypeModels;
- (id)getBarcodePayAttributeString;

@end

