//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CADisplayLink, LHPerformanceStatusBar, NSMutableDictionary, UIWindow;

@interface LHPerformanceMonitorService : NSObject
{
    CADisplayLink *_displayLink;
    double _lastTimestamp;
    long long _countPerFrame;
    LHPerformanceStatusBar *_fpsStatusBar;
    UIWindow *_statusBarWindow;
    NSMutableDictionary *_configDictionary;
}

+ (void)setConfig:(id)arg1 forAttribte:(long long)arg2;
+ (void)setTextColor:(id)arg1 forState:(long long)arg2;
+ (void)stop;
+ (void)run;
+ (id)sharedService;
@property(retain, nonatomic) NSMutableDictionary *configDictionary; // @synthesize configDictionary=_configDictionary;
@property(retain, nonatomic) UIWindow *statusBarWindow; // @synthesize statusBarWindow=_statusBarWindow;
@property(retain, nonatomic) LHPerformanceStatusBar *fpsStatusBar; // @synthesize fpsStatusBar=_fpsStatusBar;
@property(nonatomic) long long countPerFrame; // @synthesize countPerFrame=_countPerFrame;
@property(nonatomic) double lastTimestamp; // @synthesize lastTimestamp=_lastTimestamp;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
- (void).cxx_destruct;
- (void)applicationWillResignActiveNotification;
- (void)applicationDidBecomeActiveNotification;
- (long long)labelStateWith:(long long)arg1 value:(double)arg2;
- (void)envokeDisplayLink:(id)arg1;
- (void)_stop;
- (void)_run;
- (void)dealloc;
- (id)init;

@end

