//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, UIColor;

@interface LiveSwitchMenuItem : NSObject
{
    NSString *_title;
    long long _itemActionType;
    id _data;
    UIColor *_selectColor;
}

@property(retain, nonatomic) UIColor *selectColor; // @synthesize selectColor=_selectColor;
@property(retain, nonatomic) id data; // @synthesize data=_data;
@property(nonatomic) long long itemActionType; // @synthesize itemActionType=_itemActionType;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

