//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ZDCourseExerciseGetengexerciselist;

@interface LiveSimpleHomeworkViewModel : NSObject
{
    ZDCourseExerciseGetengexerciselist *_exerciseData;
    long long _courseId;
    long long _lessonId;
    long long _addScoreType;
    long long _purpose;
}

@property(nonatomic) long long purpose; // @synthesize purpose=_purpose;
@property(nonatomic) long long addScoreType; // @synthesize addScoreType=_addScoreType;
@property(nonatomic) long long lessonId; // @synthesize lessonId=_lessonId;
@property(nonatomic) long long courseId; // @synthesize courseId=_courseId;
@property(retain, nonatomic) ZDCourseExerciseGetengexerciselist *exerciseData; // @synthesize exerciseData=_exerciseData;
- (void).cxx_destruct;
- (void)getExerciseDataWithCouseId:(long long)arg1 withLessonId:(long long)arg2 purpose:(long long)arg3 complete:(CDUnknownBlockType)arg4;
- (id)init;

@end

