//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface QuestionFetchModel : NSObject
{
    int _page;
    long long _gradeId;
    long long _courseId;
    long long _listType;
}

@property(nonatomic) int page; // @synthesize page=_page;
@property(nonatomic) long long listType; // @synthesize listType=_listType;
@property(nonatomic) long long courseId; // @synthesize courseId=_courseId;
@property(nonatomic) long long gradeId; // @synthesize gradeId=_gradeId;

@end

