//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WIWBHttpAnswerData.h"

@interface WIWBUpdateAuthModuleAnswer : WIWBHttpAnswerData
{
    int _moduleConfigRefreshPeriod;
    int _localAccountLockTime;
    int _clientAccountRefreshPeriod;
    int _apListRefreshPeriod;
    int _sdkVersionRefreshPeriod;
    int _eventReportPeriod;
    int _eventRecordPortal;
    int _hotspotListRefreshPeriod;
    int _hotspotListRefreshRadius;
}

@property(nonatomic) int hotspotListRefreshRadius; // @synthesize hotspotListRefreshRadius=_hotspotListRefreshRadius;
@property(nonatomic) int hotspotListRefreshPeriod; // @synthesize hotspotListRefreshPeriod=_hotspotListRefreshPeriod;
@property(nonatomic) int eventRecordPortal; // @synthesize eventRecordPortal=_eventRecordPortal;
@property(nonatomic) int eventReportPeriod; // @synthesize eventReportPeriod=_eventReportPeriod;
@property(nonatomic) int sdkVersionRefreshPeriod; // @synthesize sdkVersionRefreshPeriod=_sdkVersionRefreshPeriod;
@property(nonatomic) int apListRefreshPeriod; // @synthesize apListRefreshPeriod=_apListRefreshPeriod;
@property(nonatomic) int clientAccountRefreshPeriod; // @synthesize clientAccountRefreshPeriod=_clientAccountRefreshPeriod;
@property(nonatomic) int localAccountLockTime; // @synthesize localAccountLockTime=_localAccountLockTime;
@property(nonatomic) int moduleConfigRefreshPeriod; // @synthesize moduleConfigRefreshPeriod=_moduleConfigRefreshPeriod;
- (void)handleDataField:(id)arg1;
- (void)dealloc;
- (id)init;

@end

