//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WKAuthObject : NSObject
{
    _Bool _needUpdate;
    unsigned long long _type;
    NSString *_appName;
    NSString *_appId;
    NSString *_scope;
    NSString *_icon;
}

@property(nonatomic) _Bool needUpdate; // @synthesize needUpdate=_needUpdate;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *scope; // @synthesize scope=_scope;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)parse:(id)arg1;
- (id)init;

@end

