//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSAttributedString, NSString;

@interface BMBusRouteElement : NSObject
{
    NSAttributedString *_routeName;
    long long _vehicleType;
    long long _stepType;
    NSString *_lineColor;
}

@property(copy, nonatomic) NSString *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) long long stepType; // @synthesize stepType=_stepType;
@property(nonatomic) long long vehicleType; // @synthesize vehicleType=_vehicleType;
@property(retain, nonatomic) NSAttributedString *routeName; // @synthesize routeName=_routeName;
- (void).cxx_destruct;

@end

