//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BMCRBusinessStrategyManager.h"

#import "BMBaseControllerDelegate-Protocol.h"
#import "BMBaseOverLayerDelegate-Protocol.h"
#import "BMBaseRoutePoiSearchViewDelegate-Protocol.h"
#import "BMCRChargingPileViewDelegate-Protocol.h"
#import "BMCRClearPoiIssueViewDelegate-Protocol.h"
#import "BMCRPoiLayerManagerDelegate-Protocol.h"
#import "BMCRSearchResultSegmentViewDelegate-Protocol.h"
#import "BMRouteItemOverlayDelegate-Protocol.h"

@class BMBaseRoutePoiSearchView, BMCRChargingPileView, BMCRClearPoiIssueView, BMCRPoiLayerManager, BMCRRouteSearchSegmentContainerView, BMRouteController, NSArray, NSString, NSTimer, UIView;
@protocol BMCRRoutePoiSearchStrategyManagerDelegate;

@interface BMCRRoutePoiSearchStrategyManager : BMCRBusinessStrategyManager <BMBaseOverLayerDelegate, BMCRPoiLayerManagerDelegate, BMBaseControllerDelegate, BMBaseRoutePoiSearchViewDelegate, BMRouteItemOverlayDelegate, BMCRChargingPileViewDelegate, BMCRSearchResultSegmentViewDelegate, BMCRClearPoiIssueViewDelegate>
{
    NSTimer *_guideTimer;
    _Bool _isRouteLoading;
    _Bool _isSearchFromSegment;
    int _prvNetMode;
    BMBaseRoutePoiSearchView *_poiSearchView;
    id <BMCRRoutePoiSearchStrategyManagerDelegate> _delegate;
    BMCRRouteSearchSegmentContainerView *_segmentContainerView;
    BMCRChargingPileView *_chargingPileView;
    BMCRClearPoiIssueView *_clearPoiIssueView;
    BMCRPoiLayerManager *_poiLayerManager;
    BMRouteController *_baseMapCtrl;
    long long _revertGEOSearchId;
    double _lastRoutePlanSuccessTimeStamp;
    id _waterDropDelegate;
    NSString *_searchKey;
    NSString *_subKey;
    NSArray *_poiArray;
    UIView *_poiSearchGuideView;
}

@property(retain, nonatomic) UIView *poiSearchGuideView; // @synthesize poiSearchGuideView=_poiSearchGuideView;
@property(retain, nonatomic) NSArray *poiArray; // @synthesize poiArray=_poiArray;
@property(nonatomic) _Bool isSearchFromSegment; // @synthesize isSearchFromSegment=_isSearchFromSegment;
@property(copy, nonatomic) NSString *subKey; // @synthesize subKey=_subKey;
@property(copy, nonatomic) NSString *searchKey; // @synthesize searchKey=_searchKey;
@property(nonatomic) __weak id waterDropDelegate; // @synthesize waterDropDelegate=_waterDropDelegate;
@property(nonatomic) double lastRoutePlanSuccessTimeStamp; // @synthesize lastRoutePlanSuccessTimeStamp=_lastRoutePlanSuccessTimeStamp;
@property(nonatomic) _Bool isRouteLoading; // @synthesize isRouteLoading=_isRouteLoading;
@property(nonatomic) int prvNetMode; // @synthesize prvNetMode=_prvNetMode;
@property(nonatomic) long long revertGEOSearchId; // @synthesize revertGEOSearchId=_revertGEOSearchId;
@property(retain, nonatomic) BMRouteController *baseMapCtrl; // @synthesize baseMapCtrl=_baseMapCtrl;
@property(retain, nonatomic) BMCRPoiLayerManager *poiLayerManager; // @synthesize poiLayerManager=_poiLayerManager;
@property(retain, nonatomic) BMCRClearPoiIssueView *clearPoiIssueView; // @synthesize clearPoiIssueView=_clearPoiIssueView;
@property(retain, nonatomic) BMCRChargingPileView *chargingPileView; // @synthesize chargingPileView=_chargingPileView;
@property(retain, nonatomic) BMCRRouteSearchSegmentContainerView *segmentContainerView; // @synthesize segmentContainerView=_segmentContainerView;
@property(nonatomic) __weak id <BMCRRoutePoiSearchStrategyManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) BMBaseRoutePoiSearchView *poiSearchView; // @synthesize poiSearchView=_poiSearchView;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)tapUserGuideView:(id)arg1;
- (void)showSearchGuideView;
- (_Bool)isNeedPoiSearchGuideView;
- (void)clearPoiIssue;
- (_Bool)isRouteOffLine;
- (void)chargingViewNeedShowJudge;
- (id)segmentsBrandWithKey:(id)arg1;
- (id)segmentsTextWithKey:(id)arg1;
- (void)chargingPileBtnClicked:(id)arg1 selected:(_Bool)arg2;
- (void)showRouteSearchPoiDetailWithItemIndex:(long long)arg1 pittingType:(long long)arg2;
- (id)searchErrorMessageWithError:(id)arg1;
- (long long)poiTypeIndex;
- (struct BMRect)poiLayerAggregationDisplayBound;
- (void)poiLayerDidHide;
- (void)segmentText_click_statistic:(id)arg1 selected:(_Bool)arg2;
- (void)segmentView:(id)arg1 clickSegmentAtIndex:(unsigned long long)arg2;
- (void)clickSegmentAtIndex:(unsigned long long)arg1 withText:(id)arg2 selected:(_Bool)arg3;
- (void)showPoiLayerWithData:(id)arg1;
- (_Bool)segmentViewNeedHideWithNameKey:(id)arg1;
- (void)routePOISearchButtonClick:(id)arg1 subWord:(id)arg2;
- (void)routePOISearchButtonClick:(id)arg1;
- (void)routePOISearchPickLocationButtonClick;
- (_Bool)isRoutePOISearchSupportPickLocation;
- (id)statistic_DistribWithRouteDistance:(long long)arg1;
- (void)statisticPOISearchClick:(id)arg1;
- (long long)indexOfTitle:(id)arg1;
- (id)routePOISearchExpandViewData;
- (id)baseViewToAddPoiSearchView;
- (void)enableSearch:(_Bool)arg1;
- (_Bool)refreshNaviRoute:(int)arg1;
- (void)resetPreviousNetMode;
- (void)onReverseGEOSearchResult:(id)arg1;
- (void)onGetCarRouteResult:(id)arg1;
- (_Bool)onGetExceptionInfo:(id)arg1;
- (void)onGetAddrList:(id)arg1;
- (void)reverseGeoOnLongTouchMapPress:(struct CGPoint)arg1;
- (long long)calcPlanPrefer;
- (id)searchItsRouteInfo;
- (_Bool)routeSearch:(id)arg1 endNode:(id)arg2 exParam:(id)arg3 planPrefer:(long long)arg4;
- (_Bool)routeSearch:(id)arg1 deleteNode:(id)arg2 endNode:(id)arg3 exParam:(id)arg4;
- (_Bool)routeSearch:(id)arg1 viaNode:(id)arg2 endNode:(id)arg3 exParam:(id)arg4;
- (void)routeItemOverlayIsShowing;
- (void)routePOIModel:(id)arg1 selectType:(unsigned long long)arg2;
- (id)stringWithViaSearchEntry:(long long)arg1;
- (void)onClickFavOverlay:(id)arg1;
- (void)onClickBackMark:(id)arg1;
- (void)moveToCenterWithPoint:(struct BMPoint)arg1;
- (void)poiOverLayClick:(id)arg1 forAdd:(_Bool)arg2;
- (void)notifyShowDynamicPoi:(id)arg1;
- (void)notifyVoiceRobotClose:(id)arg1;
- (void)notifyVoiceRobotWakeUp:(id)arg1;
- (void)onHandleShowLongJouneryLayer:(id)arg1;
- (void)routeDataSync;
- (void)routeLoadFailed;
- (void)routeLoadSuccess;
- (void)routeIsLoading;
- (void)routeFavRouting;
- (void)routePreRouting;
- (void)sceneDidHide;
- (void)sceneWillHide;
- (void)sceneDidShow;
- (void)sceneDidCreate;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

