//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseNavPage.h"

#import "NSURLConnectionDataDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class BMNRANetworkTask, NSString, NSURLConnection, UIButton, UILabel, UIProgressView, UITextField;

@interface BMUploadLocalFilePage : BaseNavPage <UITextFieldDelegate, NSURLConnectionDataDelegate>
{
    UILabel *_stateLabel;
    UIProgressView *_progressView;
    UITextField *_usrName;
    long long _state;
    UIButton *_operationBtn;
    UIButton *_loadAllFilesInfoBtn;
    long long _error;
    NSURLConnection *_connection;
    NSString *_localZipFilePath;
    BMNRANetworkTask *_uplaodFileInfo;
}

@property(retain, nonatomic) BMNRANetworkTask *uplaodFileInfo; // @synthesize uplaodFileInfo=_uplaodFileInfo;
@property(retain, nonatomic) NSString *localZipFilePath; // @synthesize localZipFilePath=_localZipFilePath;
@property(retain) NSURLConnection *connection; // @synthesize connection=_connection;
@property(nonatomic) long long error; // @synthesize error=_error;
@property(retain, nonatomic) UIButton *loadAllFilesInfoBtn; // @synthesize loadAllFilesInfoBtn=_loadAllFilesInfoBtn;
@property(retain, nonatomic) UIButton *operationBtn; // @synthesize operationBtn=_operationBtn;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(retain, nonatomic) UITextField *usrName; // @synthesize usrName=_usrName;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UILabel *stateLabel; // @synthesize stateLabel=_stateLabel;
- (void).cxx_destruct;
- (void)dealLoadAllFilesInfo;
- (long long)preferredStatusBarStyle;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)processSubmitFailed;
- (void)processUploadCompleted;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)processUpload;
- (void)processCompressCompleted;
- (void)processCompressing;
- (void)dealOperation:(id)arg1;
- (void)dealloc;
- (void)onNavigationBackButton;
- (void)pageCreate:(id)arg1;
- (void)pageStart;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

