//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MDHomeEntranceTypeBaseView, MDHomeEntranceTypeEightView, MDHomeEntranceTypeFiveView, MDHomeEntranceTypeFourView, MDHomeEntranceTypeOneView, MDHomeEntranceTypeSevenView, MDHomeEntranceTypeSixView, MDHomeEntranceTypeThreeView, MDHomeEntranceTypeTwoView, MDHomeOperationModel;

@interface MDHomeEntranceCellView : UIView
{
    MDHomeOperationModel *_cellModel;
    MDHomeEntranceTypeOneView *_typeOneView;
    MDHomeEntranceTypeTwoView *_typeTwoView;
    MDHomeEntranceTypeThreeView *_typeThreeView;
    MDHomeEntranceTypeFourView *_typeFourView;
    MDHomeEntranceTypeFiveView *_typeFiveView;
    MDHomeEntranceTypeSixView *_typeSixView;
    MDHomeEntranceTypeSevenView *_typeSevenView;
    MDHomeEntranceTypeEightView *_typeEightView;
    MDHomeEntranceTypeBaseView *_currentTypeView;
}

@property(nonatomic) __weak MDHomeEntranceTypeBaseView *currentTypeView; // @synthesize currentTypeView=_currentTypeView;
@property(retain, nonatomic) MDHomeEntranceTypeEightView *typeEightView; // @synthesize typeEightView=_typeEightView;
@property(retain, nonatomic) MDHomeEntranceTypeSevenView *typeSevenView; // @synthesize typeSevenView=_typeSevenView;
@property(retain, nonatomic) MDHomeEntranceTypeSixView *typeSixView; // @synthesize typeSixView=_typeSixView;
@property(retain, nonatomic) MDHomeEntranceTypeFiveView *typeFiveView; // @synthesize typeFiveView=_typeFiveView;
@property(retain, nonatomic) MDHomeEntranceTypeFourView *typeFourView; // @synthesize typeFourView=_typeFourView;
@property(retain, nonatomic) MDHomeEntranceTypeThreeView *typeThreeView; // @synthesize typeThreeView=_typeThreeView;
@property(retain, nonatomic) MDHomeEntranceTypeTwoView *typeTwoView; // @synthesize typeTwoView=_typeTwoView;
@property(retain, nonatomic) MDHomeEntranceTypeOneView *typeOneView; // @synthesize typeOneView=_typeOneView;
@property(retain, nonatomic) MDHomeOperationModel *cellModel; // @synthesize cellModel=_cellModel;
- (void).cxx_destruct;
- (void)pauseVideo;
- (void)playVideo;
- (void)stopTimer;
- (void)pauseTimer;
- (void)startTimer;
- (void)showAnimation;
- (id)model;
- (void)bindModel:(id)arg1;
- (void)resetAllTypeView;

@end

