//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UIPanGestureRecognizer;
@protocol MDMomentSwipeViewDelegate;

@interface MDMomentSwipeView : UIView <UIGestureRecognizerDelegate>
{
    _Bool _isVerticalScroll;
    id <MDMomentSwipeViewDelegate> _delegate;
    UIPanGestureRecognizer *_panGestureRecognizer;
    UIView *_backView;
    double _accumulateNumber;
    long long _currentDirection;
    struct CGPoint _defaultCenter;
}

@property(nonatomic) long long currentDirection; // @synthesize currentDirection=_currentDirection;
@property(nonatomic) double accumulateNumber; // @synthesize accumulateNumber=_accumulateNumber;
@property(nonatomic) _Bool isVerticalScroll; // @synthesize isVerticalScroll=_isVerticalScroll;
@property(nonatomic) struct CGPoint defaultCenter; // @synthesize defaultCenter=_defaultCenter;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
@property(nonatomic) __weak id <MDMomentSwipeViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)doSwitchAnimationWithDirection:(long long)arg1;
- (void)moveCenterToPoint:(struct CGPoint)arg1 completion:(CDUnknownBlockType)arg2;
- (void)switchHorizontalPage;
- (void)switchVerticalPage;
- (struct CGPoint)transPoint;
- (_Bool)judgeDirectionWithGuesture:(id)arg1;
- (void)doPan:(id)arg1;
- (void)doDownSwipe:(id)arg1;
- (void)doUpSwipe:(id)arg1;
- (void)doRightSwipe:(id)arg1;
- (void)doLeftSwipe:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)addGestureForAllowSwitchVideo;
- (void)addGestureForForbidSwitchVideo;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

