//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UILabel;
@protocol MLLiveSDKEndBroadcastViewControllerDelegate;

@interface MLLiveSDKEndBroadcastViewController : UIViewController
{
    id <MLLiveSDKEndBroadcastViewControllerDelegate> _delegate;
    long long _onlineNumber;
    long long _starValue;
    UILabel *_starValueLabel;
    UILabel *_onlineNumLabel;
}

@property(nonatomic) __weak UILabel *onlineNumLabel; // @synthesize onlineNumLabel=_onlineNumLabel;
@property(nonatomic) __weak UILabel *starValueLabel; // @synthesize starValueLabel=_starValueLabel;
@property(nonatomic) long long starValue; // @synthesize starValue=_starValue;
@property(nonatomic) long long onlineNumber; // @synthesize onlineNumber=_onlineNumber;
@property(nonatomic) __weak id <MLLiveSDKEndBroadcastViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)backgroundBtnClicked:(id)arg1;
- (void)updateOnlineNumber:(long long)arg1;
- (void)updateStarValue:(long long)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)stopBroadcastBtnClicked:(id)arg1;
- (void)dismissSelfTriggerDelegate:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

