//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MLUIDataSource.h"

@class MLBroadcastDataSourceCoordinator, NSMutableDictionary, NSString;
@protocol MLMessageDataSourceDelegate;

@interface MLMessageDataSource : MLUIDataSource
{
    id <MLMessageDataSourceDelegate> _delegate;
    NSString *_roomId;
    NSString *_source;
    MLBroadcastDataSourceCoordinator *_dataSourceCoordinator;
    NSMutableDictionary *_successCallBackDictionary;
    NSMutableDictionary *_failureCallBackDictionary;
    NSString *_messageTemp;
    NSMutableDictionary *_messageDictionary;
}

@property(retain, nonatomic) NSMutableDictionary *messageDictionary; // @synthesize messageDictionary=_messageDictionary;
@property(retain, nonatomic) NSString *messageTemp; // @synthesize messageTemp=_messageTemp;
@property(retain, nonatomic) NSMutableDictionary *failureCallBackDictionary; // @synthesize failureCallBackDictionary=_failureCallBackDictionary;
@property(retain, nonatomic) NSMutableDictionary *successCallBackDictionary; // @synthesize successCallBackDictionary=_successCallBackDictionary;
@property(nonatomic) __weak MLBroadcastDataSourceCoordinator *dataSourceCoordinator; // @synthesize dataSourceCoordinator=_dataSourceCoordinator;
@property(copy, nonatomic) NSString *source; // @synthesize source=_source;
@property(copy, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
@property(nonatomic) __weak id <MLMessageDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)followSuccessMessage:(id)arg1;
- (void)showRoomDebugInfo:(id)arg1;
- (void)sendExtraMessage:(id)arg1 text:(id)arg2 messagePrm:(id)arg3 eventPrm:(id)arg4;
- (void)setBroadcastMessageError:(id)arg1;
- (void)setBroadcastMessageFail:(id)arg1;
- (void)setBroadcastMessageSuccess:(id)arg1;
- (void)sendBroadcastMessage:(id)arg1;
- (void)sendMessageWithText:(id)arg1 isBroadcast:(_Bool)arg2;
- (void)protobufSendMessageWithText:(id)arg1;
- (_Bool)isRepeatMessage:(id)arg1;
- (void)shutLocationError:(id)arg1;
- (void)shutLocationFail:(id)arg1;
- (void)shutLocationSuccess:(id)arg1;
- (void)requestSetLocationEnable:(id)arg1;
- (void)createFansCircleFail:(id)arg1;
- (void)createFansCircleError:(id)arg1;
- (void)createFansCircleSuccess:(id)arg1;
- (void)requestCreateFansCircle:(id)arg1;
- (void)createFansGroupFail:(id)arg1;
- (void)createFansGroupError:(id)arg1;
- (void)createFansGroupSuccess:(id)arg1;
- (void)requestCreateFansGroup:(id)arg1 roomId:(id)arg2;
- (void)noticeServerSendMessage:(long long)arg1 gotoAction:(id)arg2;
- (void)handlePostRequest:(id)arg1;
- (void)getIntoRoomMessageFail:(id)arg1;
- (void)getIntoRoomMessageError:(id)arg1;
- (void)getIntoRoomMessageSuccess:(id)arg1;
- (void)getIntoRoomMessage:(id)arg1 source:(id)arg2;
- (void)didReceiveEnterRoom:(id)arg1 withGroupInfo:(id)arg2;
- (void)didReceiveBilibili:(id)arg1 withGroupInfo:(id)arg2;
- (void)didReceiveSystemBilibili:(id)arg1 withGroupInfo:(id)arg2;
- (void)didReceiveBuyNotice:(id)arg1;
- (void)didReceiveMessageWithGoup:(id)arg1;
- (void)didReceiveEnterRoom:(id)arg1;
- (void)didReceiveBilibili:(id)arg1;
- (void)didReceiveSystemBilibili:(id)arg1;
- (void)didReceiveMessage:(id)arg1;
- (void)didReceiveSuspensionMessage:(id)arg1;
- (id)init;
- (void)dealloc;

@end

