//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface MLPublisherStatisticOptions : NSObject
{
    int _provider;
    NSString *_roomID;
    unsigned long long _sessionTime;
    double _packageCollectionInterval;
    long long _reportPackageCountThreshold;
    NSString *_publisherType;
    long long _publisherIdentify;
    NSString *_serviceType;
}

@property(copy, nonatomic) NSString *serviceType; // @synthesize serviceType=_serviceType;
@property(nonatomic) long long publisherIdentify; // @synthesize publisherIdentify=_publisherIdentify;
@property(retain, nonatomic) NSString *publisherType; // @synthesize publisherType=_publisherType;
@property(nonatomic) long long reportPackageCountThreshold; // @synthesize reportPackageCountThreshold=_reportPackageCountThreshold;
@property(nonatomic) double packageCollectionInterval; // @synthesize packageCollectionInterval=_packageCollectionInterval;
@property(nonatomic) unsigned long long sessionTime; // @synthesize sessionTime=_sessionTime;
@property(nonatomic) int provider; // @synthesize provider=_provider;
@property(copy, nonatomic) NSString *roomID; // @synthesize roomID=_roomID;
- (void).cxx_destruct;

@end

