//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface caltime : NSObject
{
    NSMutableDictionary *timer_cap;
}

+ (id)sharedInstance;
@property(retain) NSMutableDictionary *timer_cap; // @synthesize timer_cap;
- (void).cxx_destruct;
- (int)cur_cal_time:(id)arg1;
- (int)end_cal_time:(id)arg1;
- (id)set_cal_time:(id)arg1;
- (id)init;
- (void)operation;

@end

