//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface IQYOrderApiData : NSObject
{
    NSString *_fee;
    NSArray *_payPackIdSet;
    NSString *_isAdjusted;
    NSString *_isCouponInvolved;
    NSArray *_orders;
    NSArray *_rel;
}

+ (id)parseForArray:(id)arg1;
@property(retain, nonatomic) NSArray *rel; // @synthesize rel=_rel;
@property(retain, nonatomic) NSArray *orders; // @synthesize orders=_orders;
@property(retain, nonatomic) NSString *isCouponInvolved; // @synthesize isCouponInvolved=_isCouponInvolved;
@property(retain, nonatomic) NSString *isAdjusted; // @synthesize isAdjusted=_isAdjusted;
@property(retain, nonatomic) NSArray *payPackIdSet; // @synthesize payPackIdSet=_payPackIdSet;
@property(retain, nonatomic) NSString *fee; // @synthesize fee=_fee;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (void)buildWithDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

