//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSArray, NSString, QRBookViewerSpeakerCursor, QRBookViewerSpeakerSettingView, UIPanGestureRecognizer, UITapGestureRecognizer;

@interface QRBookViewerSpeakerRootView : UIView <UIGestureRecognizerDelegate>
{
    CDUnknownBlockType _cursorChanged;
    CDUnknownBlockType _rateChanged;
    CDUnknownBlockType _volumeChanged;
    CDUnknownBlockType _closeClick;
    QRBookViewerSpeakerSettingView *_settingView;
    QRBookViewerSpeakerCursor *_cursor;
    UIPanGestureRecognizer *_panGes;
    UITapGestureRecognizer *_tapGes;
    NSArray *_boxViews;
}

@property(copy, nonatomic) NSArray *boxViews; // @synthesize boxViews=_boxViews;
@property(retain, nonatomic) UITapGestureRecognizer *tapGes; // @synthesize tapGes=_tapGes;
@property(retain, nonatomic) UIPanGestureRecognizer *panGes; // @synthesize panGes=_panGes;
@property(retain, nonatomic) QRBookViewerSpeakerCursor *cursor; // @synthesize cursor=_cursor;
@property(retain, nonatomic) QRBookViewerSpeakerSettingView *settingView; // @synthesize settingView=_settingView;
@property(copy, nonatomic) CDUnknownBlockType closeClick; // @synthesize closeClick=_closeClick;
@property(copy, nonatomic) CDUnknownBlockType volumeChanged; // @synthesize volumeChanged=_volumeChanged;
@property(copy, nonatomic) CDUnknownBlockType rateChanged; // @synthesize rateChanged=_rateChanged;
@property(copy, nonatomic) CDUnknownBlockType cursorChanged; // @synthesize cursorChanged=_cursorChanged;
- (void).cxx_destruct;
- (void)setHidden:(_Bool)arg1;
- (void)didMoveToSuperview;
- (void)drawBoxLines:(id)arg1;
- (void)clearBoxLines;
- (void)closeSelf;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)moveCursorTo:(struct CGPoint)arg1;
- (void)hideCursorAt:(struct CGPoint)arg1;
- (void)showCursorAt:(struct CGPoint)arg1;
- (void)handlePan:(id)arg1;
- (void)handleTap:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

