//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QYUPhoneCardBaseCell.h"

#import "QYUCardCellCustomProtocol-Protocol.h"

@class NSString, QRCardlyBookItemView6, QRCardlyHeadView, QYUCardCellModel, UIView;

@interface QRReaderCardlyNewSpecialTopicOneCell : QYUPhoneCardBaseCell <QYUCardCellCustomProtocol>
{
    UIView *CoverView;
    QYUCardCellModel *_dataModel;
    long long _bookType;
    QRCardlyBookItemView6 *_bookItem2_1;
    QRCardlyHeadView *_headView;
}

+ (id)customizeCardCellStyle:(id)arg1 cardData:(id)arg2;
+ (id)getCellObjByContainer:(id)arg1 andIndex:(long long)arg2;
+ (long long)getLinesByCardData:(id)arg1 andShowNum:(long long)arg2;
+ (void)load;
+ (double)customizedTopBannerHeight;
@property(retain, nonatomic) QRCardlyHeadView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) QRCardlyBookItemView6 *bookItem2_1; // @synthesize bookItem2_1=_bookItem2_1;
@property(nonatomic) long long bookType; // @synthesize bookType=_bookType;
@property(retain, nonatomic) QYUCardCellModel *dataModel; // @synthesize dataModel=_dataModel;
@property(retain, nonatomic) UIView *CoverView; // @synthesize CoverView;
- (void).cxx_destruct;
- (void)routerEventWithName:(id)arg1 data:(id)arg2 withClickEvent:(id)arg3 WithCardId:(id)arg4;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setCellModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

