//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface QYCinemaMovieDetailToastData : NSObject
{
    NSString *_content;
    NSString *_second;
    NSString *_maxTimes;
}

@property(copy, nonatomic) NSString *maxTimes; // @synthesize maxTimes=_maxTimes;
@property(copy, nonatomic) NSString *second; // @synthesize second=_second;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (void)buildWithDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

