//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MNBViewController.h"

@class MNFMovieListVC;

@interface MNFMovieListContainerVC : MNBViewController
{
    MNFMovieListVC *_vcMovieList;
}

@property(retain, nonatomic) MNFMovieListVC *vcMovieList; // @synthesize vcMovieList=_vcMovieList;
- (void).cxx_destruct;
- (void)mn_setTableViewScrollsToTop:(_Bool)arg1;
- (void)reloadDataFromUser;
- (void)viewDidLoad;

@end

