//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTBModel.h"

@class MNMArticleRelatedMovie, MNMArticleTopList, MNMArticleVideo, NSArray, NSNumber, NSString;

@interface MNMArticleInfo : MTBModel
{
    NSNumber *_articleId;
    NSNumber *_isDel;
    NSNumber *_tweetId;
    unsigned long long _enumType;
    NSNumber *_type;
    NSString *_title;
    NSString *_author;
    NSNumber *_publishTime;
    NSString *_pageviews;
    NSString *_content;
    NSArray *_images;
    MNMArticleRelatedMovie *_relatedMovie;
    NSArray *_relatedArticles;
    MNMArticleTopList *_topList;
    MNMArticleVideo *_video;
}

+ (id)mtdOptional_getArrayTypePropertiesMappingDic;
@property(retain, nonatomic) MNMArticleVideo *video; // @synthesize video=_video;
@property(retain, nonatomic) MNMArticleTopList *topList; // @synthesize topList=_topList;
@property(copy, nonatomic) NSArray *relatedArticles; // @synthesize relatedArticles=_relatedArticles;
@property(retain, nonatomic) MNMArticleRelatedMovie *relatedMovie; // @synthesize relatedMovie=_relatedMovie;
@property(copy, nonatomic) NSArray *images; // @synthesize images=_images;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *pageviews; // @synthesize pageviews=_pageviews;
@property(retain, nonatomic) NSNumber *publishTime; // @synthesize publishTime=_publishTime;
@property(copy, nonatomic) NSString *author; // @synthesize author=_author;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSNumber *type; // @synthesize type=_type;
@property(nonatomic) unsigned long long enumType; // @synthesize enumType=_enumType;
@property(retain, nonatomic) NSNumber *tweetId; // @synthesize tweetId=_tweetId;
@property(retain, nonatomic) NSNumber *isDel; // @synthesize isDel=_isDel;
@property(retain, nonatomic) NSNumber *articleId; // @synthesize articleId=_articleId;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forKey:(id)arg2;

@end

