//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FullAdViewController, MNFHomePagePopAdVC, NewUserGiftViewController, UnusedTicketViewController;

@interface MNSHomeMainPopViewManager : NSObject
{
    MNFHomePagePopAdVC *_vcHomePopView;
    NewUserGiftViewController *_vcNewUserGift;
    UnusedTicketViewController *_vcUnusedTicket;
    FullAdViewController *_vcRichMediaAd;
}

+ (id)shared;
@property(retain, nonatomic) FullAdViewController *vcRichMediaAd; // @synthesize vcRichMediaAd=_vcRichMediaAd;
@property(retain, nonatomic) UnusedTicketViewController *vcUnusedTicket; // @synthesize vcUnusedTicket=_vcUnusedTicket;
@property(retain, nonatomic) NewUserGiftViewController *vcNewUserGift; // @synthesize vcNewUserGift=_vcNewUserGift;
@property(retain, nonatomic) MNFHomePagePopAdVC *vcHomePopView; // @synthesize vcHomePopView=_vcHomePopView;
- (void).cxx_destruct;
- (void)clearUnusedTicketView;
- (void)clearNewUserGiftView;
- (void)clearRichMediaAdvertiseView;
- (void)clearHomePopView;
- (void)closeAllPopView;
- (void)showRichMediaAd:(id)arg1 adEntity:(id)arg2;
- (void)showUnUsedTicket:(id)arg1;
- (void)showNewUserGift:(id)arg1 identifier:(_Bool)arg2;
- (void)showHomepagePopAd:(id)arg1 identifier:(id)arg2;

@end

