//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class QIUILabel, QSEAdsModel, QSEInMobiNativeInfo, UIImageView, UILabel, UIView;

@interface _TtC12SystemExpert12ToolsAdsCell : UICollectionViewCell
{
    // Error parsing type: , name: newModel
    // Error parsing type: , name: closeAdsAction
    // Error parsing type: , name: newInMobiModel
    // Error parsing type: , name: closeInMobiAction
    // Error parsing type: , name: headerImageView
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: subtitleLabel
    // Error parsing type: , name: separatorLine
    // Error parsing type: , name: actionLabel
    // Error parsing type: , name: sourceLabel
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)closeAction:(id)arg1;
- (void)setupLineSpacingWithLabel:(id)arg1 text:(id)arg2;
- (void)awakeFromNib;
@property(nonatomic) __weak QIUILabel *sourceLabel; // @synthesize sourceLabel;
@property(nonatomic) __weak QIUILabel *actionLabel; // @synthesize actionLabel;
@property(nonatomic) __weak UIView *separatorLine; // @synthesize separatorLine;
@property(nonatomic) __weak UILabel *subtitleLabel; // @synthesize subtitleLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak UIImageView *headerImageView; // @synthesize headerImageView;
@property(nonatomic, retain) QSEInMobiNativeInfo *inMobiModel;
@property(nonatomic, copy) CDUnknownBlockType closeInMobiAction; // @synthesize closeInMobiAction;
@property(nonatomic, retain) QSEInMobiNativeInfo *newInMobiModel; // @synthesize newInMobiModel;
@property(nonatomic, retain) QSEAdsModel *adsModel;
@property(nonatomic, copy) CDUnknownBlockType closeAdsAction; // @synthesize closeAdsAction;
@property(nonatomic, retain) QSEAdsModel *newModel; // @synthesize newModel;

@end

