//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSString;

@interface WITheme : MTLModel <MTLJSONSerializing>
{
    _Bool _isDefault;
    NSString *_name;
    NSString *_displayName;
    NSString *_themeDescription;
    long long _version;
    double _price;
    NSString *_size;
    long long _type;
    NSString *_downloadURLStringStore;
}

+ (id)encodingBehaviorsByPropertyKey;
+ (id)typeJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
+ (id)defaultDarkTheme;
+ (id)defaultTheme;
@property(copy, nonatomic) NSString *downloadURLStringStore; // @synthesize downloadURLStringStore=_downloadURLStringStore;
@property(nonatomic) _Bool isDefault; // @synthesize isDefault=_isDefault;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *size; // @synthesize size=_size;
@property(nonatomic) double price; // @synthesize price=_price;
@property(nonatomic) long long version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *themeDescription; // @synthesize themeDescription=_themeDescription;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *promotionImageURLString;
@property(readonly, nonatomic) NSString *previewImageURLString;
@property(readonly, nonatomic) NSString *iconImageURLString;
@property(copy, nonatomic) NSString *downloadURLString;
- (id)localBundle;

@end

