//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSString, UICollectionView, UIView;

@interface WIThemePannelVC : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource>
{
    UIView *_pannelView;
    NSArray *_downloadedThemes;
    UICollectionView *_collectionView;
}

+ (void)restoreSavedThemePannelViewController;
+ (void)saveThemePannelViewControllerForStateRestoration:(id)arg1;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSArray *downloadedThemes; // @synthesize downloadedThemes=_downloadedThemes;
@property(nonatomic) __weak UIView *pannelView; // @synthesize pannelView=_pannelView;
- (void).cxx_destruct;
- (void)switchToTheme:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)didReceiveMemoryWarning;
- (void)reloadDownloadedThemes;
- (void)downloadedThemeChanged;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

