//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface BHBLECommand : NSObject
{
    _Bool _isSuccess;
    _Bool _isReturn;
    unsigned int _sequenceId;
    unsigned int _commandId;
    unsigned int _key;
    unsigned int _value;
    NSData *_data;
    long long _repeatCount;
    NSString *_name;
    CDUnknownBlockType _commandBlock;
}

@property(copy, nonatomic) CDUnknownBlockType commandBlock; // @synthesize commandBlock=_commandBlock;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) _Bool isReturn; // @synthesize isReturn=_isReturn;
@property(nonatomic) _Bool isSuccess; // @synthesize isSuccess=_isSuccess;
@property(nonatomic) long long repeatCount; // @synthesize repeatCount=_repeatCount;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(nonatomic) unsigned int value; // @synthesize value=_value;
@property(nonatomic) unsigned int key; // @synthesize key=_key;
@property(nonatomic) unsigned int commandId; // @synthesize commandId=_commandId;
@property(nonatomic) unsigned int sequenceId; // @synthesize sequenceId=_sequenceId;
- (void).cxx_destruct;
- (id)initWithId:(unsigned int)arg1 key:(unsigned int)arg2 value:(unsigned int)arg3 data:(id)arg4 sequenceId:(unsigned int)arg5 name:(id)arg6 bikeBlock:(CDUnknownBlockType)arg7;

@end

