//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DCRichLabel;

@interface DCSCTXMarkContentView : UIView
{
    long long _lineNumber;
    DCRichLabel *_label;
}

@property(retain, nonatomic) DCRichLabel *label; // @synthesize label=_label;
@property(nonatomic) long long lineNumber; // @synthesize lineNumber=_lineNumber;
- (void).cxx_destruct;
- (id)editImage:(id)arg1 size:(struct CGSize)arg2;
- (void)layoutSubviews;
- (void)setDistance:(id)arg1 time:(id)arg2 text:(id)arg3;
- (id)init;

@end

