//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface DGPBaseMapViewModel : NSObject
{
    NSMutableArray *_metroBusOverlayArray;
    NSMutableArray *_stopAnnotationArray;
    NSMutableArray *_trafficOverlayArray;
    long long _selectedStopIndex;
    NSMutableArray *_selectedDynamicAnnotationArray;
    NSMutableArray *_unselectedDynamicAnnotationArray;
    NSMutableArray *_selectedPinAnnotationArray;
}

@property(retain, nonatomic) NSMutableArray *selectedPinAnnotationArray; // @synthesize selectedPinAnnotationArray=_selectedPinAnnotationArray;
@property(retain, nonatomic) NSMutableArray *unselectedDynamicAnnotationArray; // @synthesize unselectedDynamicAnnotationArray=_unselectedDynamicAnnotationArray;
@property(retain, nonatomic) NSMutableArray *selectedDynamicAnnotationArray; // @synthesize selectedDynamicAnnotationArray=_selectedDynamicAnnotationArray;
@property(nonatomic) long long selectedStopIndex; // @synthesize selectedStopIndex=_selectedStopIndex;
@property(retain, nonatomic) NSMutableArray *trafficOverlayArray; // @synthesize trafficOverlayArray=_trafficOverlayArray;
@property(retain, nonatomic) NSMutableArray *stopAnnotationArray; // @synthesize stopAnnotationArray=_stopAnnotationArray;
@property(retain, nonatomic) NSMutableArray *metroBusOverlayArray; // @synthesize metroBusOverlayArray=_metroBusOverlayArray;
- (void).cxx_destruct;

@end

