//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDelegate-Protocol.h"

@class HWSecurityPolicy, NSString, NSURLSession;

@interface HWHTTPSessionManager : NSObject <NSURLSessionDelegate>
{
    HWSecurityPolicy *_securityPolicy;
    NSURLSession *_requestSession;
}

+ (id)sharedSessionManager;
@property(retain, nonatomic) NSURLSession *requestSession; // @synthesize requestSession=_requestSession;
@property(retain, nonatomic) HWSecurityPolicy *securityPolicy; // @synthesize securityPolicy=_securityPolicy;
- (void).cxx_destruct;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2;
- (id)requestWithMethod:(id)arg1 URLString:(id)arg2 parameters:(id)arg3 body:(id)arg4 error:(id *)arg5;
- (void)finishTasksAndInvalidate;
- (id)reqeustWithURL:(id)arg1 HTTPMethod:(id)arg2 parameters:(id)arg3 body:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)dealloc;
- (id)initWithSessionConfiguration:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

