//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SFActivityConf : NSObject
{
    long long _cardID;
    long long _showStyle;
    long long _displayStyle;
}

@property(readonly, nonatomic) long long displayStyle; // @synthesize displayStyle=_displayStyle;
@property(nonatomic) long long showStyle; // @synthesize showStyle=_showStyle;
@property(nonatomic) long long cardID; // @synthesize cardID=_cardID;
- (id)initWithCardID:(long long)arg1 showStyle:(long long)arg2;
- (id)initWithCardID:(long long)arg1;

@end

