//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JMAsyncSocket.h"

#import "JMAsyncSocketDelegate-Protocol.h"

@class JMACSHostTools, NSMutableData, NSMutableDictionary, NSObject, NSString, NSTimer;
@protocol OS_dispatch_semaphore;

@interface JMBaseSocket : JMAsyncSocket <JMAsyncSocketDelegate>
{
    unsigned int _connectStatus;
    NSMutableData *_cacheBuffData;
    long long _connectionCount;
    NSMutableDictionary *_transactionHistory;
    JMACSHostTools *_hostTools;
    NSString *_host;
    long long _port;
    NSObject<OS_dispatch_semaphore> *_signlock;
    NSTimer *_reconnectTimer;
}

+ (void)timerThreadEntryPoint:(id)arg1;
+ (id)timerThread;
@property(retain, nonatomic) NSTimer *reconnectTimer; // @synthesize reconnectTimer=_reconnectTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *signlock; // @synthesize signlock=_signlock;
@property(nonatomic) long long port; // @synthesize port=_port;
@property(retain, nonatomic) NSString *host; // @synthesize host=_host;
@property(retain, nonatomic) JMACSHostTools *hostTools; // @synthesize hostTools=_hostTools;
@property(retain, nonatomic) NSMutableDictionary *transactionHistory; // @synthesize transactionHistory=_transactionHistory;
@property(nonatomic) long long connectionCount; // @synthesize connectionCount=_connectionCount;
@property(nonatomic) unsigned int connectStatus; // @synthesize connectStatus=_connectStatus;
@property(retain, nonatomic) NSMutableData *cacheBuffData; // @synthesize cacheBuffData=_cacheBuffData;
- (void).cxx_destruct;
- (void)reconnect:(id)arg1;
- (void)delayConnect;
- (void)beginReconnect;
- (void)disconnect;
- (void)connect;
- (id)initWithDelegate:(id)arg1 delegateQueue:(id)arg2;

@end

