//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JMCallCenterHomeSelfHelperModel;

@interface JMCallCenterSelfServiceView : UIView
{
    JMCallCenterHomeSelfHelperModel *_viewModel;
    CDUnknownBlockType _selfServiceButtonEvent;
}

@property(copy, nonatomic) CDUnknownBlockType selfServiceButtonEvent; // @synthesize selfServiceButtonEvent=_selfServiceButtonEvent;
@property(retain, nonatomic) JMCallCenterHomeSelfHelperModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)dealloc;

@end

