//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JMMobBaseRequest.h"

@class NSString;

@interface JMHomeCoutuanFreeActRequest : JMMobBaseRequest
{
    NSString *_card_id;
}

+ (id)createCoutuanFreeActRequestWithCardId:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
@property(copy, nonatomic) NSString *card_id; // @synthesize card_id=_card_id;
- (void).cxx_destruct;
- (long long)httpType;
- (id)subUri;

@end

