//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JMMyOrderDetailCell.h"

@class JMMyOrderDetailAddressInfoCellModel, NSLayoutConstraint, UIButton, UIImageView, UILabel;
@protocol JMMyOrderDetailModelProtocol;

@interface JMMyOrderDetailAddressInfoCell : JMMyOrderDetailCell
{
    UIButton *_modifyAddressButton;
    JMMyOrderDetailAddressInfoCellModel<JMMyOrderDetailModelProtocol> *_model;
    UIImageView *_landmarkLogoImageView;
    UILabel *_consigneeAddressLabel;
    UILabel *_consigneeTitleLabel;
    UILabel *_identityCardTitleLabel;
    UILabel *_verifyedLabel;
    NSLayoutConstraint *_addressDetailTopToId;
    UIImageView *_arrowImageView;
}

@property(nonatomic) __weak UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(nonatomic) __weak NSLayoutConstraint *addressDetailTopToId; // @synthesize addressDetailTopToId=_addressDetailTopToId;
@property(nonatomic) __weak UILabel *verifyedLabel; // @synthesize verifyedLabel=_verifyedLabel;
@property(nonatomic) __weak UILabel *identityCardTitleLabel; // @synthesize identityCardTitleLabel=_identityCardTitleLabel;
@property(nonatomic) __weak UILabel *consigneeTitleLabel; // @synthesize consigneeTitleLabel=_consigneeTitleLabel;
@property(nonatomic) __weak UILabel *consigneeAddressLabel; // @synthesize consigneeAddressLabel=_consigneeAddressLabel;
@property(nonatomic) __weak UIImageView *landmarkLogoImageView; // @synthesize landmarkLogoImageView=_landmarkLogoImageView;
@property(nonatomic) __weak JMMyOrderDetailAddressInfoCellModel<JMMyOrderDetailModelProtocol> *model; // @synthesize model=_model;
@property(nonatomic) __weak UIButton *modifyAddressButton; // @synthesize modifyAddressButton=_modifyAddressButton;
- (void).cxx_destruct;
- (void)jm_orderDetailDidTapModifyAddress:(id)arg1;
- (void)prepareForReuse;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (void)setShowIdLabel:(_Bool)arg1;
- (void)awakeFromNib;

@end

