//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (ValidObject)
- (id)validDictionaryForKey:(id)arg1;
- (id)validDictionaryForKey:(id)arg1 defaultValue:(id)arg2;
- (id)validArrayForKey:(id)arg1;
- (id)validArrayForKey:(id)arg1 defaultValue:(id)arg2;
- (id)validStringForKey:(id)arg1;
- (id)validStringForKey:(id)arg1 defaultValue:(id)arg2;
- (id)validNumberForKey:(id)arg1;
- (id)validNumberForKey:(id)arg1 defaultValue:(id)arg2;
@end

