//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ProtocolBaseJason.h"

@class NSArray;

@interface HotSongsProtocol : ProtocolBaseJason
{
    _Bool _disableWeekend;
    NSArray *_hotSongs;
}

@property _Bool disableWeekend; // @synthesize disableWeekend=_disableWeekend;
@property(readonly) NSArray *hotSongs; // @synthesize hotSongs=_hotSongs;
- (void).cxx_destruct;
- (void)onParseJasonData:(id)arg1;
- (void)onAddDataInRoot:(struct _xmlNode *)arg1;
- (id)getUrl;
- (id)init;

@end

