//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface QMMorseObject : NSObject
{
    NSString *_appVersion;
    NSString *_deviceType;
    NSString *_osVersion;
    NSString *_md5Value;
    NSString *_downloadUrl;
}

+ (id)translateToQMMorseCodeObjectFromDic:(id)arg1;
@property(retain, nonatomic) NSString *downloadUrl; // @synthesize downloadUrl=_downloadUrl;
@property(retain, nonatomic) NSString *md5Value; // @synthesize md5Value=_md5Value;
@property(retain, nonatomic) NSString *osVersion; // @synthesize osVersion=_osVersion;
@property(retain, nonatomic) NSString *deviceType; // @synthesize deviceType=_deviceType;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
- (void).cxx_destruct;
- (_Bool)isOsVersionInRange:(id)arg1;
- (_Bool)isMorseCodeFileRunForThisDevice;

@end

