//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, ShareInfo;
@protocol VideoGifSharePanelDelegate;

@interface VideoGifSharePanel : UIView
{
    ShareInfo *_shareInfo;
    id <VideoGifSharePanelDelegate> _delegate;
    NSMutableArray *_btnArray;
}

@property(retain, nonatomic) NSMutableArray *btnArray; // @synthesize btnArray=_btnArray;
@property(nonatomic) __weak id <VideoGifSharePanelDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) ShareInfo *shareInfo; // @synthesize shareInfo=_shareInfo;
- (void).cxx_destruct;
- (void)showWXMissView:(int)arg1;
- (void)shareToWeibo:(id)arg1;
- (void)shareToQZoneAppOrH5:(id)arg1;
- (void)shareToJoinQzone:(id)arg1;
- (void)shareToQzone:(id)arg1;
- (void)shareToWeiXin:(id)arg1 isTimeLine:(_Bool)arg2;
- (void)shareToQQ:(id)arg1;
- (void)buttonClick:(id)arg1;
- (void)shareToAction:(unsigned long long)arg1;
- (id)buildViewAtIndex:(unsigned long long)arg1 dataDic:(id)arg2 totalCount:(unsigned long long)arg3;
- (void)initShareButton;
- (void)reBuildShareView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

