//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAYBaseCinemaListViewController.h"

@class MAYMovie, NSDate, NSNumber, NSString;

@interface MAYHomeMovieCinemaListViewController : MAYBaseCinemaListViewController
{
    NSNumber *_movieId;
    NSString *_movieName;
    NSDate *_dataRefreshDate;
    MAYMovie *_movie;
}

+ (void)load;
@property(retain, nonatomic) MAYMovie *movie; // @synthesize movie=_movie;
@property(retain, nonatomic) NSDate *dataRefreshDate; // @synthesize dataRefreshDate=_dataRefreshDate;
@property(retain, nonatomic) NSString *movieName; // @synthesize movieName=_movieName;
@property(retain, nonatomic) NSNumber *movieId; // @synthesize movieId=_movieId;
- (void).cxx_destruct;
- (id)floatItemsInit;
- (void)whiteBoardDataInitialized;
- (void)willEnterForeground:(id)arg1;
- (void)didClickSchedule:(id)arg1 cinemaItem:(id)arg2 index:(long long)arg3 openedIndex:(id)arg4;
- (void)setWithURL:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

