//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTDragRefreshTableViewController.h"

#import "MAYFetchedResultsTableDataSourceProtocol-Protocol.h"

@class MAYImageAnimationLoadingView, MAYMovie, MAYMovieDetailService, MAYMovieMajorCommentListSerice, NSMutableArray, NSString, SAKError, SAKFetchedResultsController;

@interface MAYMovieMajorCommentListViewController : MTDragRefreshTableViewController <MAYFetchedResultsTableDataSourceProtocol>
{
    _Bool _hasMore;
    SAKFetchedResultsController *_fetchedResultsController;
    long long _mid;
    MAYMovie *_movieDetail;
    MAYImageAnimationLoadingView *_loadingView;
    MAYMovieMajorCommentListSerice *_majorCommentListService;
    MAYMovieDetailService *_movieDetailService;
    SAKError *_networkError;
    NSMutableArray *_majorComments;
}

+ (void)load;
@property(retain, nonatomic) NSMutableArray *majorComments; // @synthesize majorComments=_majorComments;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(retain, nonatomic) SAKError *networkError; // @synthesize networkError=_networkError;
@property(retain, nonatomic) MAYMovieDetailService *movieDetailService; // @synthesize movieDetailService=_movieDetailService;
@property(retain, nonatomic) MAYMovieMajorCommentListSerice *majorCommentListService; // @synthesize majorCommentListService=_majorCommentListService;
@property(retain, nonatomic) MAYImageAnimationLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) MAYMovie *movieDetail; // @synthesize movieDetail=_movieDetail;
@property(nonatomic) long long mid; // @synthesize mid=_mid;
@property(retain, nonatomic) SAKFetchedResultsController *fetchedResultsController; // @synthesize fetchedResultsController=_fetchedResultsController;
- (void).cxx_destruct;
- (id)pageParameter;
- (void)goToReplyList:(id)arg1 shouldReplyDirectlyAfterAppear:(_Bool)arg2;
- (void)goToReplyList:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)networkErrorSecion;
- (void)showMajorCommentList;
- (void)loadMovieDetail:(_Bool)arg1 group:(id)arg2;
- (void)fetchMovieMajorCommentList:(_Bool)arg1 group:(id)arg2;
- (void)loadDataFromNetwork:(_Bool)arg1;
- (void)refresh;
- (void)loadMore;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

