//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MAYGroupStyleCell.h"

@class UIImageView, UILabel, UIView;

@interface MTTicketMachineCell : MAYGroupStyleCell
{
    UIView *_containerView;
    UILabel *_placeTitleLabel;
    UILabel *_placeLabel;
    UIView *_lineView;
    UILabel *_useTitleLabel;
    UILabel *_usePatternLabel;
    UIImageView *_picImageV;
}

@property(retain, nonatomic) UIImageView *picImageV; // @synthesize picImageV=_picImageV;
@property(retain, nonatomic) UILabel *usePatternLabel; // @synthesize usePatternLabel=_usePatternLabel;
@property(retain, nonatomic) UILabel *useTitleLabel; // @synthesize useTitleLabel=_useTitleLabel;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UILabel *placeLabel; // @synthesize placeLabel=_placeLabel;
@property(retain, nonatomic) UILabel *placeTitleLabel; // @synthesize placeTitleLabel=_placeTitleLabel;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setItem:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

