//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary, NSString, UIWindow;

@interface BDNAppTestingManager : NSObject
{
    _Bool _hasTestingBuild;
    _Bool _jailbreak;
    _Bool _alertViewShowing;
    NSString *_version;
    NSString *_buildVersion;
    NSString *_uid;
    NSString *_cityId;
    NSString *_channel;
    NSString *_net;
    long long _invitationAlertType;
    long long _showAlertMaxTimes;
    long long _onlineAlertType;
    long long _showOnlineAfterDays;
    UIWindow *_displayWindow;
    NSString *_productId;
    NSString *_appSecret;
    NSString *_cuid;
    NSDictionary *_requestCommonParameters;
    NSMutableDictionary *_userCustomFilterValues;
    NSString *_appStoreUrl;
    long long _testingEnvironment;
    long long _appStatusBarStyle;
    struct CLLocationCoordinate2D _location;
}

+ (id)doSignWithParameters:(id)arg1 appSecret:(id)arg2;
+ (id)SDKVersion;
+ (id)sharedManager;
@property(nonatomic) long long appStatusBarStyle; // @synthesize appStatusBarStyle=_appStatusBarStyle;
@property(nonatomic) long long testingEnvironment; // @synthesize testingEnvironment=_testingEnvironment;
@property(nonatomic) _Bool alertViewShowing; // @synthesize alertViewShowing=_alertViewShowing;
@property(copy, nonatomic) NSString *appStoreUrl; // @synthesize appStoreUrl=_appStoreUrl;
@property(retain, nonatomic) NSMutableDictionary *userCustomFilterValues; // @synthesize userCustomFilterValues=_userCustomFilterValues;
@property(retain, nonatomic) NSDictionary *requestCommonParameters; // @synthesize requestCommonParameters=_requestCommonParameters;
@property(copy, nonatomic) NSString *cuid; // @synthesize cuid=_cuid;
@property(copy, nonatomic) NSString *appSecret; // @synthesize appSecret=_appSecret;
@property(copy, nonatomic) NSString *productId; // @synthesize productId=_productId;
@property(retain, nonatomic) UIWindow *displayWindow; // @synthesize displayWindow=_displayWindow;
@property(nonatomic) long long showOnlineAfterDays; // @synthesize showOnlineAfterDays=_showOnlineAfterDays;
@property(nonatomic) long long onlineAlertType; // @synthesize onlineAlertType=_onlineAlertType;
@property(nonatomic) long long showAlertMaxTimes; // @synthesize showAlertMaxTimes=_showAlertMaxTimes;
@property(nonatomic) long long invitationAlertType; // @synthesize invitationAlertType=_invitationAlertType;
@property(nonatomic, getter=isJailbreak) _Bool jailbreak; // @synthesize jailbreak=_jailbreak;
@property(nonatomic) struct CLLocationCoordinate2D location; // @synthesize location=_location;
@property(copy, nonatomic) NSString *net; // @synthesize net=_net;
@property(copy, nonatomic) NSString *channel; // @synthesize channel=_channel;
@property(copy, nonatomic) NSString *cityId; // @synthesize cityId=_cityId;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(copy, nonatomic) NSString *buildVersion; // @synthesize buildVersion=_buildVersion;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(nonatomic) _Bool hasTestingBuild; // @synthesize hasTestingBuild=_hasTestingBuild;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (_Bool)canShowOnlineAlert;
- (_Bool)canShowInvitationAlert;
- (void)showAlertView:(id)arg1;
- (void)showAppStoreAlertView;
- (void)checkAppTestingAvailable:(id)arg1;
- (id)parametersByAddCommonFields:(id)arg1;
- (void)appTestingHandleNotificationDidFinishLaunching:(id)arg1;
- (_Bool)isAppTestingWindow:(id)arg1;
- (void)setCustomFilterValue:(id)arg1 forKey:(id)arg2;
- (void)presentAppTestingViewController;
- (void)registerWithProductId:(id)arg1 appSecret:(id)arg2 deviceId:(id)arg3 testingEnvironment:(long long)arg4;
- (void)registerWithProductId:(id)arg1 appSecret:(id)arg2 deviceId:(id)arg3;
- (id)init;
- (void)dealloc;
- (void)dismissAppTestingViewController;
- (id)request:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)testingRelaseSwitchURL;
- (id)testingInfoURL;
- (id)testingCodeURL;

@end

