//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol MTAMainServiceDelegate;

@interface ATStore : NSObject
{
    id <MTAMainServiceDelegate> _mtaService;
}

+ (id)getMTAStorePath;
@property(nonatomic) __weak id <MTAMainServiceDelegate> mtaService; // @synthesize mtaService=_mtaService;
- (void).cxx_destruct;
- (void)deleteBinding;
- (id)loadBinding;
- (_Bool)storeBinding:(id)arg1;
- (id)initWithMtaService:(id)arg1;

@end

