//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UISwitch;

@interface TDSwitchCell : UITableViewCell
{
    _Bool _isSwitchOn;
    long long _type;
    UISwitch *_setSwitch;
}

@property(retain, nonatomic) UISwitch *setSwitch; // @synthesize setSwitch=_setSwitch;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) _Bool isSwitchOn; // @synthesize isSwitchOn=_isSwitchOn;
- (void).cxx_destruct;
- (void)setSwitch:(id)arg1;
- (void)setupUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

