//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSURL, TTTAttributedLabel, ZSShortageCell, ZSShortageQuestionItem;

@protocol ZSShortageCellDelegate <NSObject>
- (void)shortageCell:(ZSShortageCell *)arg1 attributedLabel:(TTTAttributedLabel *)arg2 didSelectLinkWithURL:(NSURL *)arg3;
- (void)goQuestionDetail:(ZSShortageCell *)arg1 questionItem:(ZSShortageQuestionItem *)arg2;
@end

