//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JOYTopicInfoModuleViewModel.h"

@class NSString;

@interface BKRSimpleTopicInfoModuleViewModel : JOYTopicInfoModuleViewModel
{
    NSString *_themeTitle;
    NSString *_themeTimer;
}

@property(copy, nonatomic) NSString *themeTimer; // @synthesize themeTimer=_themeTimer;
@property(copy, nonatomic) NSString *themeTitle; // @synthesize themeTitle=_themeTitle;
- (void).cxx_destruct;
- (_Bool)shouldShow;
- (void)setupViewModel;

@end

