//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CKBubbleCell.h"

@class UIImageView, UILabel;

@interface CKVoiceCell : CKBubbleCell
{
    UIImageView *_voiceImageView;
    UILabel *_lengthLabel;
    UIImageView *_unreadPointIcon;
}

+ (double)bubbleAccessoryViewWidthForContent:(id)arg1;
+ (struct CGSize)bubbleContentSizeForContent:(id)arg1;
+ (double)lengWithDuration:(long long)arg1;
@property(nonatomic) __weak UIImageView *unreadPointIcon; // @synthesize unreadPointIcon=_unreadPointIcon;
@property(nonatomic) __weak UILabel *lengthLabel; // @synthesize lengthLabel=_lengthLabel;
@property(nonatomic) __weak UIImageView *voiceImageView; // @synthesize voiceImageView=_voiceImageView;
- (void).cxx_destruct;
- (void)tapBubble:(id)arg1;
- (void)layoutSubviews;
- (void)refreshView:(id)arg1;
- (void)setContent:(id)arg1;
- (id)initWithMessageType:(long long)arg1;
- (void)dealloc;

@end

