//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DEFBaseModulesViewController.h"

@class DEFLBSSearchNavigationBar, DEFLBSViewModel, METEmptyView, NSString;

@interface DEFLBSSearchViewController : DEFBaseModulesViewController
{
    _Bool _searching;
    CDUnknownBlockType _searchCompletion;
    DEFLBSViewModel *_LBSViewModel;
    NSString *_lastKeyword;
    DEFLBSSearchNavigationBar *_searchNavigationBar;
    METEmptyView *_emptyView;
}

@property(nonatomic, getter=isSearching) _Bool searching; // @synthesize searching=_searching;
@property(retain, nonatomic) METEmptyView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) DEFLBSSearchNavigationBar *searchNavigationBar; // @synthesize searchNavigationBar=_searchNavigationBar;
@property(copy, nonatomic) NSString *lastKeyword; // @synthesize lastKeyword=_lastKeyword;
@property(retain, nonatomic) DEFLBSViewModel *LBSViewModel; // @synthesize LBSViewModel=_LBSViewModel;
@property(copy, nonatomic) CDUnknownBlockType searchCompletion; // @synthesize searchCompletion=_searchCompletion;
- (void).cxx_destruct;
- (id)modules;
- (void)p_switchToNormalView;
- (void)p_switchToErrorView;
- (void)p_switchToEmptyView;
- (void)p_search:(id)arg1;
- (id)p_searchQuery:(id)arg1;
- (void)refreshData;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithViewModel:(id)arg1;

@end

