//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FTKSubmitOrderValidateCell.h"

#import "NVBaseCellProtocol-Protocol.h"

@class FTKLabelAndTextFieldView, NSString, UIButton;

@interface FTKNewPassengerBirthDayCell : FTKSubmitOrderValidateCell <NVBaseCellProtocol>
{
    FTKLabelAndTextFieldView *_textView;
    UIButton *_maskButton;
}

+ (id)cellReuseId:(id)arg1;
+ (double)cellHeight:(id)arg1;
@property(retain, nonatomic) UIButton *maskButton; // @synthesize maskButton=_maskButton;
- (void)setTextView:(id)arg1;
- (void).cxx_destruct;
- (id)titleBtnImageName;
- (id)title;
- (void)chooseDate;
- (id)textView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

