//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HTKBannerViewModel.h"

@class HTLADInfoService, NSArray, NSMutableArray;

@interface HTLBannerViewModel : HTKBannerViewModel
{
    NSArray *_banners;
    unsigned long long _categoryID;
    NSMutableArray *_MGEArray;
    HTLADInfoService *_bannerService;
}

@property(retain, nonatomic) HTLADInfoService *bannerService; // @synthesize bannerService=_bannerService;
@property(retain, nonatomic) NSMutableArray *MGEArray; // @synthesize MGEArray=_MGEArray;
@property(nonatomic) unsigned long long categoryID; // @synthesize categoryID=_categoryID;
@property(retain, nonatomic) NSArray *banners; // @synthesize banners=_banners;
- (void).cxx_destruct;
- (void)loadBannerMGEWithADInfos:(id)arg1;
- (void)clickBannerMGEWithIndex:(long long)arg1;
- (void)didShowBannerAtIndex:(long long)arg1;
- (void)loadBanner:(unsigned long long)arg1;
- (id)initWithBannerCategotyID:(unsigned long long)arg1;

@end

