//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HTLFilterService.h"

#import "HTLSearchFilterServiceProtocol-Protocol.h"

@class HTLSearchFilterModel, NSDictionary, NSString;

@interface HTLSearchFilterService : HTLFilterService <HTLSearchFilterServiceProtocol>
{
    _Bool _isRequesting;
    NSString *_keyword;
    NSDictionary *_selectDict;
    long long _categoryId;
    NSString *_activePageId;
    NSString *_sourceType;
    HTLSearchFilterModel *_model;
}

@property(nonatomic) _Bool isRequesting; // @synthesize isRequesting=_isRequesting;
@property(retain, nonatomic) HTLSearchFilterModel *model; // @synthesize model=_model;
@property(copy, nonatomic) NSString *sourceType; // @synthesize sourceType=_sourceType;
@property(copy, nonatomic) NSString *activePageId; // @synthesize activePageId=_activePageId;
@property(nonatomic) long long categoryId; // @synthesize categoryId=_categoryId;
@property(copy, nonatomic) NSDictionary *selectDict; // @synthesize selectDict=_selectDict;
@property(copy, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
- (void).cxx_destruct;
- (void)loadFilterList:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

