//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GCBaseModule.h"

@class KTVDealDetailInfoModuleDateSelectCell, KTVDealDetailInfoModuleRemarkCell, KTVMultipleSelectButtonCell, NSArray, NSNumber, NVModelBaseKTVTable;

@interface KTVDealDetailInfoModule : GCBaseModule
{
    _Bool _shouldShowDefaultPackage;
    _Bool _showKtvDealDetail;
    NSArray *_cells;
    NVModelBaseKTVTable *_tableData;
    NSNumber *_dealId;
    long long _dateSelectIndex;
    long long _timeSelectIndex;
    KTVDealDetailInfoModuleDateSelectCell *_dateSelectCell;
    KTVMultipleSelectButtonCell *_timeSelectCell;
    KTVDealDetailInfoModuleRemarkCell *_remarkCell;
}

@property(retain, nonatomic) KTVDealDetailInfoModuleRemarkCell *remarkCell; // @synthesize remarkCell=_remarkCell;
@property(retain, nonatomic) KTVMultipleSelectButtonCell *timeSelectCell; // @synthesize timeSelectCell=_timeSelectCell;
@property(retain, nonatomic) KTVDealDetailInfoModuleDateSelectCell *dateSelectCell; // @synthesize dateSelectCell=_dateSelectCell;
@property(nonatomic) _Bool showKtvDealDetail; // @synthesize showKtvDealDetail=_showKtvDealDetail;
@property(nonatomic) _Bool shouldShowDefaultPackage; // @synthesize shouldShowDefaultPackage=_shouldShowDefaultPackage;
@property(nonatomic) long long timeSelectIndex; // @synthesize timeSelectIndex=_timeSelectIndex;
@property(nonatomic) long long dateSelectIndex; // @synthesize dateSelectIndex=_dateSelectIndex;
@property(retain, nonatomic) NSNumber *dealId; // @synthesize dealId=_dealId;
@property(retain, nonatomic) NVModelBaseKTVTable *tableData; // @synthesize tableData=_tableData;
@property(retain, nonatomic) NSArray *cells; // @synthesize cells=_cells;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didSelectHeaderCellForSection:(long long)arg1;
- (id)headerCellForSection:(long long)arg1;
- (_Bool)hasHeaderCellForSection:(long long)arg1;
- (id)makeCells;
- (void)setupTimeCell;
- (void)setupDateCell;
- (void)getModuleData:(id)arg1;
- (void)initialer;
- (void)setupModule;
- (id)moduleNeedRefresh;
- (_Bool)shouldShow;

@end

