//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface METDelayOperation : NSObject
{
    _Bool _hasExecuted;
    _Bool _isWaiting;
    _Bool _isCancelled;
    _Bool _isFinished;
    CDUnknownBlockType _block;
}

+ (id)operationWithBlock:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property _Bool isFinished; // @synthesize isFinished=_isFinished;
@property _Bool isCancelled; // @synthesize isCancelled=_isCancelled;
@property(nonatomic) _Bool isWaiting; // @synthesize isWaiting=_isWaiting;
@property _Bool hasExecuted; // @synthesize hasExecuted=_hasExecuted;
- (void).cxx_destruct;
- (void)cancel;
- (void)excuteBlock;
- (void)delayStartWithTimeinterval:(double)arg1;

@end

