//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTTableViewItem.h"

@class SAKMyCoupon;

@interface MTMyGroupCouponTableViewItem : MTTableViewItem
{
    _Bool _clipsToBounds;
    _Bool _showTopShadow;
    SAKMyCoupon *_myCoupon;
    double _codeLabelHeight;
    double _fullHeight;
    unsigned long long _style;
    double _zPosition;
    long long _count;
    long long _number;
}

@property(nonatomic) long long number; // @synthesize number=_number;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(nonatomic) _Bool showTopShadow; // @synthesize showTopShadow=_showTopShadow;
@property(nonatomic) _Bool clipsToBounds; // @synthesize clipsToBounds=_clipsToBounds;
@property(nonatomic) double zPosition; // @synthesize zPosition=_zPosition;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(readonly, nonatomic) double fullHeight; // @synthesize fullHeight=_fullHeight;
@property(readonly, nonatomic) double codeLabelHeight; // @synthesize codeLabelHeight=_codeLabelHeight;
@property(retain, nonatomic) SAKMyCoupon *myCoupon; // @synthesize myCoupon=_myCoupon;
- (void).cxx_destruct;
- (double)cellHeight;
- (void)calculateHeight;

@end

