//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NVBaseModel.h"

@class NSString;

@interface NVModelBaseMTOVLanguage : NVBaseModel
{
    NSString *_languageShortName;
    NSString *_languageName;
}

+ (id)metaInfo;
@property(copy, nonatomic) NSString *languageName; // @synthesize languageName=_languageName;
@property(copy, nonatomic) NSString *languageShortName; // @synthesize languageShortName=_languageShortName;
- (void).cxx_destruct;

@end

