//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SAKCell.h"

@class UILabel;

@interface PFBMyAccountTopCell : SAKCell
{
    UILabel *_titleLabel;
    UILabel *_rightLabel;
    UILabel *_attachedInfoLabel;
}

@property(retain, nonatomic) UILabel *attachedInfoLabel; // @synthesize attachedInfoLabel=_attachedInfoLabel;
@property(retain, nonatomic) UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (id)addLabel;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

