//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SAKBTDomainProtocol-Protocol.h"

@interface SAKBTRemoteBusinessConfigItem : NSObject <SAKBTDomainProtocol>
{
    _Bool _toggle;
    _Bool _userSampled;
    unsigned long long _sampleType;
    long long _sampleCount;
}

+ (id)objectWithDictionary:(id)arg1;
@property(nonatomic) long long sampleCount; // @synthesize sampleCount=_sampleCount;
@property(nonatomic) _Bool userSampled; // @synthesize userSampled=_userSampled;
@property(nonatomic) unsigned long long sampleType; // @synthesize sampleType=_sampleType;
@property(nonatomic) _Bool toggle; // @synthesize toggle=_toggle;

@end

