//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SAKDynamicLayoutCommonViewProtocol-Protocol.h"

@class CAShapeLayer, NSString, UIColor;

@interface SAKDynamicLayoutBaseView : UIView <SAKDynamicLayoutCommonViewProtocol>
{
    _Bool clipsToBorder;
    double borderWidth;
    UIColor *borderColor;
    double borderRadius;
    double borderRadiusTopLeft;
    double borderRadiusTopRight;
    double borderRadiusBottomLeft;
    double borderRadiusBottomRight;
    CAShapeLayer *borderLineLayer;
    unsigned long long clipType;
}

@property(nonatomic) unsigned long long clipType; // @synthesize clipType;
@property(nonatomic) _Bool clipsToBorder; // @synthesize clipsToBorder;
@property(retain, nonatomic) CAShapeLayer *borderLineLayer; // @synthesize borderLineLayer;
@property(nonatomic) double borderRadiusBottomRight; // @synthesize borderRadiusBottomRight;
@property(nonatomic) double borderRadiusBottomLeft; // @synthesize borderRadiusBottomLeft;
@property(nonatomic) double borderRadiusTopRight; // @synthesize borderRadiusTopRight;
@property(nonatomic) double borderRadiusTopLeft; // @synthesize borderRadiusTopLeft;
@property(nonatomic) double borderRadius; // @synthesize borderRadius;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth;
- (void).cxx_destruct;
- (void)applyPresetAttributes;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

