//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SPFTrafficInfoModel : NSObject <NSCopying>
{
    NSString *_pageName;
    long long _businessTrafficSize;
    long long _imageTrafficSize;
    long long _webTrafficSize;
}

@property(nonatomic) long long webTrafficSize; // @synthesize webTrafficSize=_webTrafficSize;
@property(nonatomic) long long imageTrafficSize; // @synthesize imageTrafficSize=_imageTrafficSize;
@property(nonatomic) long long businessTrafficSize; // @synthesize businessTrafficSize=_businessTrafficSize;
@property(copy, nonatomic) NSString *pageName; // @synthesize pageName=_pageName;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)toDictionary;
- (id)initWithName:(id)arg1;
- (id)init;

@end

