//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TPKTableViewCell.h"

@class TPKReusableTagView, UIImageView, UILabel;

@interface TPKDestinationCityMapCardCell : TPKTableViewCell
{
    UIImageView *_mainImageView;
    UILabel *_cityNameLabel;
    UILabel *_distanceLabel;
    UILabel *_coreScenicLabel;
    TPKReusableTagView *_destTagView;
}

@property(retain, nonatomic) TPKReusableTagView *destTagView; // @synthesize destTagView=_destTagView;
@property(retain, nonatomic) UILabel *coreScenicLabel; // @synthesize coreScenicLabel=_coreScenicLabel;
@property(retain, nonatomic) UILabel *distanceLabel; // @synthesize distanceLabel=_distanceLabel;
@property(retain, nonatomic) UILabel *cityNameLabel; // @synthesize cityNameLabel=_cityNameLabel;
@property(retain, nonatomic) UIImageView *mainImageView; // @synthesize mainImageView=_mainImageView;
- (void).cxx_destruct;
- (void)setItem:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

