//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class RACCommand, RACSignal;

@protocol TPKSTTPOIHeaderItemProtocol <NSObject>
@property(readonly, nonatomic) RACCommand *jumpCommand;
@property(readonly, nonatomic) RACSignal *urlSignal;
@property(readonly, nonatomic) RACSignal *jumpTipsSignal;
@property(readonly, nonatomic) RACSignal *imagesSignal;
@property(readonly, nonatomic) RACSignal *pageIndexDescSignal;
@property(readonly, nonatomic) RACSignal *imageCountSignal;
@property(readonly, nonatomic) RACCommand *currentPageIndexCommand;
@property(readonly, nonatomic) RACSignal *currentImageSignal;
@end

