//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SAKDomainObject.h"

@class NSString, POIofficialTag;

@interface travelHotPOI : SAKDomainObject
{
    long long _poiId;
    NSString *_imageTagUrl;
    NSString *_imageUrl;
    double _lowestPrice;
    NSString *_title;
    NSString *_uri;
    POIofficialTag *_officialTag;
}

+ (id)officialTagJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(retain, nonatomic) POIofficialTag *officialTag; // @synthesize officialTag=_officialTag;
@property(copy, nonatomic) NSString *uri; // @synthesize uri=_uri;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) double lowestPrice; // @synthesize lowestPrice=_lowestPrice;
@property(copy, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(copy, nonatomic) NSString *imageTagUrl; // @synthesize imageTagUrl=_imageTagUrl;
@property(nonatomic) long long poiId; // @synthesize poiId=_poiId;
- (void).cxx_destruct;

@end

