//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface WMFriendMiddleView : UIView
{
    UILabel *_bindTipLabel;
    UILabel *_firstIntroLabel;
    UILabel *_secondIntroLabel;
    UILabel *_thirdIntroLabel;
}

@property(retain, nonatomic) UILabel *thirdIntroLabel; // @synthesize thirdIntroLabel=_thirdIntroLabel;
@property(retain, nonatomic) UILabel *secondIntroLabel; // @synthesize secondIntroLabel=_secondIntroLabel;
@property(retain, nonatomic) UILabel *firstIntroLabel; // @synthesize firstIntroLabel=_firstIntroLabel;
@property(retain, nonatomic) UILabel *bindTipLabel; // @synthesize bindTipLabel=_bindTipLabel;
- (void).cxx_destruct;
- (id)creatDotView;
- (id)init;

@end

