//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GPChargeVideoErrorView, NSString;

@protocol GPChargeVideoErrorViewDelegate <NSObject>

@optional
- (void)willRefreshPlayer:(GPChargeVideoErrorView *)arg1;
- (void)didLoginEvent:(GPChargeVideoErrorView *)arg1;
- (void)didChangeSmallScreen:(GPChargeVideoErrorView *)arg1;
- (void)gpCharegeVideoErrorView:(GPChargeVideoErrorView *)arg1 clickEventWithType:(long long)arg2 eventContent:(NSString *)arg3;
@end

