//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSONModel.h"

@class MCMessageBoxModel_jumpData, MCMessageBoxModel_msgData, NSDate, NSString;
@protocol Optional;

@interface MCMessageBoxModel : JSONModel
{
    _Bool _canDelete;
    _Bool _inTop;
    long long _authAccountId;
    MCMessageBoxModel_jumpData<Optional> *_jumpData;
    unsigned long long _msgid;
    long long _badgeNum;
    MCMessageBoxModel_msgData<Optional> *_msgData;
    long long _redPoint;
    NSDate *_timestamp;
    NSString *_pageName;
    NSString<Optional> *_icon;
    long long _type;
}

+ (_Bool)propertyIsOptional:(id)arg1;
+ (void)load;
@property(nonatomic) _Bool inTop; // @synthesize inTop=_inTop;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString<Optional> *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *pageName; // @synthesize pageName=_pageName;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) long long redPoint; // @synthesize redPoint=_redPoint;
@property(retain, nonatomic) MCMessageBoxModel_msgData<Optional> *msgData; // @synthesize msgData=_msgData;
@property(nonatomic) long long badgeNum; // @synthesize badgeNum=_badgeNum;
@property(nonatomic) unsigned long long msgid; // @synthesize msgid=_msgid;
@property(nonatomic) _Bool canDelete; // @synthesize canDelete=_canDelete;
@property(retain, nonatomic) MCMessageBoxModel_jumpData<Optional> *jumpData; // @synthesize jumpData=_jumpData;
@property(nonatomic) long long authAccountId; // @synthesize authAccountId=_authAccountId;
- (void).cxx_destruct;
- (id)NSDateFromNSNumber:(id)arg1;

@end

