//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableArray.h>

@interface NSMutableArray (LTMNSArray)
- (id)ltm_addObjectsFromArray:(id)arg1;
- (id)ltm_addObject:(id)arg1;
- (id)ltm_popFirstObject;
- (id)ltm_pop:(unsigned long long)arg1;
- (void)ltm_performMap:(CDUnknownBlockType)arg1;
- (void)ltm_performReject:(CDUnknownBlockType)arg1;
- (void)ltm_performSelect:(CDUnknownBlockType)arg1;
@end

