//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CALayer, NSDictionary, OPRevolveTitle, UIButton, UILabel;
@protocol OPChannelDemandErrorViewDelegate;

@interface OPChannelDemandErrorView : UIView
{
    id <OPChannelDemandErrorViewDelegate> _delegate;
    UILabel *_titleLabel;
    CALayer *_lineLayer;
    UILabel *_priceLabel;
    UIButton *_buyButton;
    long long _screenMode;
    UIButton *_backButton;
    OPRevolveTitle *_revolveTitle;
    NSDictionary *_dataSource;
}

@property(copy, nonatomic) NSDictionary *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) OPRevolveTitle *revolveTitle; // @synthesize revolveTitle=_revolveTitle;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(nonatomic) long long screenMode; // @synthesize screenMode=_screenMode;
@property(retain, nonatomic) UIButton *buyButton; // @synthesize buyButton=_buyButton;
@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) CALayer *lineLayer; // @synthesize lineLayer=_lineLayer;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <OPChannelDemandErrorViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updataBuyInfo;
- (void)changPriceTitleColor;
- (void)backClick:(id)arg1;
- (void)buyButtonClick:(id)arg1;
- (void)setData:(id)arg1;
- (void)setVideoTitle:(id)arg1;
- (void)setChannelDemandScreenMode:(long long)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

