//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface SPRuntimeFix : NSObject
{
}

+ (void)load;
- (void)spfix_viewWillDisappear:(_Bool)arg1;
- (void)spfix_playVideo:(id)arg1 withUrlString:(id)arg2 audioMuted:(_Bool)arg3 autoPlay:(_Bool)arg4 controls:(_Bool)arg5 loop:(_Bool)arg6 timeout:(int)arg7 position:(int [4])arg8 startStyle:(id)arg9 stopStyle:(id)arg10;

@end

