//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "KSPluginDelegate-Protocol.h"

@class KSInstance, NSString;

@interface YKKSPluginPageChildCorner : NSObject <KSPluginDelegate>
{
    KSInstance *_instance;
}

+ (_Bool)isHomePageDataPrepared;
+ (_Bool)isHomePageActived;
- (void).cxx_destruct;
- (void)removeChildUI;
- (void)showHomeUI:(_Bool)arg1 homedata:(id)arg2;
- (void)ksInstance:(id)arg1 receiveEvent:(id)arg2 params:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

