//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel;
@protocol WBVideoRecordButtonViewDelegate;

@interface HSVideoRecordButtonView : UIView
{
    id <WBVideoRecordButtonViewDelegate> _delegate;
    double _progress;
    UILabel *_toastLabel;
    UIButton *_recordButton;
    long long _status;
}

@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) UIButton *recordButton; // @synthesize recordButton=_recordButton;
@property(retain, nonatomic) UILabel *toastLabel; // @synthesize toastLabel=_toastLabel;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) __weak id <WBVideoRecordButtonViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)resetRightLeftButton:(id)arg1;
- (void)resetButton:(id)arg1;
- (void)ruleInfo:(id)arg1;
- (void)delete:(id)arg1;
- (void)record:(id)arg1;
- (void)reloadStatus:(long long)arg1;
- (void)reloadRecordEnableStatus:(_Bool)arg1;
- (void)createViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

