//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBMainPageBaseModel.h"

@class NSDictionary, NSString;

@interface WBMainCateItemModel : WBMainPageBaseModel
{
    _Bool _partner;
    _Bool _new;
    _Bool _hot;
    _Bool _red;
    _Bool _discount;
    NSDictionary *_action;
    NSString *_icon;
    NSString *_list_name;
    NSString *_name;
    NSString *_cateid;
    NSString *_operation;
    NSString *_cate_type;
}

@property(retain, nonatomic) NSString *cate_type; // @synthesize cate_type=_cate_type;
@property(nonatomic) _Bool discount; // @synthesize discount=_discount;
@property(copy, nonatomic) NSString *operation; // @synthesize operation=_operation;
@property(nonatomic) _Bool red; // @synthesize red=_red;
@property(nonatomic) _Bool hot; // @synthesize hot=_hot;
@property(nonatomic) _Bool new; // @synthesize new=_new;
@property(nonatomic) _Bool partner; // @synthesize partner=_partner;
@property(retain, nonatomic) NSString *cateid; // @synthesize cateid=_cateid;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *list_name; // @synthesize list_name=_list_name;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSDictionary *action; // @synthesize action=_action;
- (void).cxx_destruct;

@end

