//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WBMsgBaseCell.h"

@class MLLinkLabel;

@interface WBMsgReceiveTextCell : WBMsgBaseCell
{
    MLLinkLabel *_contentLabel;
}

+ (double)configHeightForCell:(id)arg1;
@property(nonatomic) __weak MLLinkLabel *contentLabel; // @synthesize contentLabel=_contentLabel;
- (void).cxx_destruct;
- (void)deleteMsg:(id)arg1;
- (void)resendButtonClick:(id)arg1;
- (void)configCellWithModel:(id)arg1;

@end

