//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GLDataParserProtocol-Protocol.h"

@class NSArray, NSString;

@interface GLBannerData : NSObject <GLDataParserProtocol>
{
    NSArray *_activitiesArray;
    long long _durationTime;
    long long _loopTime;
}

@property(nonatomic) long long loopTime; // @synthesize loopTime=_loopTime;
@property(nonatomic) long long durationTime; // @synthesize durationTime=_durationTime;
@property(retain, nonatomic) NSArray *activitiesArray; // @synthesize activitiesArray=_activitiesArray;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

