//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WDSBaseData.h"

@class CLLocation, NSNumber, NSString;

@interface WDSLocationInfo : WDSBaseData
{
    NSNumber *_adcode;
    NSString *_city;
    NSString *_district;
    NSString *_name;
    NSString *_nation;
    NSString *_province;
    CLLocation *_location;
}

@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(retain, nonatomic) NSString *province; // @synthesize province=_province;
@property(retain, nonatomic) NSString *nation; // @synthesize nation=_nation;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *district; // @synthesize district=_district;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
@property(retain, nonatomic) NSNumber *adcode; // @synthesize adcode=_adcode;
- (void).cxx_destruct;
- (id)parseInfoFromDictionaryManually:(id)arg1;
- (id)parseInfoFromDictionary:(id)arg1;

@end

