//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MobFoxAdDelegate-Protocol.h"
#import "MobFoxInterstitialCustomEventDelegate-Protocol.h"
#import "NSURLSessionDataDelegate-Protocol.h"
#import "NSURLSessionDelegate-Protocol.h"
#import "NSURLSessionTaskDelegate-Protocol.h"

@class LocationServicesManager, MobFoxAd, MobFoxInterstitialCustomEvent, MobFoxInterstitialViewController, NSArray, NSDictionary, NSString, NSURLSessionDataTask, UIViewController;
@protocol MobFoxInterstitialAdDelegate;

@interface MobFoxInterstitialAd : NSObject <MobFoxAdDelegate, MobFoxInterstitialCustomEventDelegate, NSURLSessionDelegate, NSURLSessionDataDelegate, NSURLSessionTaskDelegate>
{
    NSArray *events;
    NSString *customEventPixel;
    NSString *userAgent;
    _Bool _ready;
    id <MobFoxInterstitialAdDelegate> _delegate;
    UIViewController *_rootViewController;
    MobFoxAd *_ad;
    LocationServicesManager *_locationServicesManager;
    MobFoxInterstitialCustomEvent *_customEvent;
    NSURLSessionDataTask *_task;
    NSDictionary *_adDict;
    MobFoxInterstitialViewController *_interstitialVC;
}

+ (void)locationServicesDisabled:(_Bool)arg1;
@property(retain, nonatomic) MobFoxInterstitialViewController *interstitialVC; // @synthesize interstitialVC=_interstitialVC;
@property(retain, nonatomic) NSDictionary *adDict; // @synthesize adDict=_adDict;
@property(retain, nonatomic) NSURLSessionDataTask *task; // @synthesize task=_task;
@property(retain, nonatomic) MobFoxInterstitialCustomEvent *customEvent; // @synthesize customEvent=_customEvent;
@property(retain, nonatomic) LocationServicesManager *locationServicesManager; // @synthesize locationServicesManager=_locationServicesManager;
@property(retain, nonatomic) MobFoxAd *ad; // @synthesize ad=_ad;
@property _Bool ready; // @synthesize ready=_ready;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(nonatomic) __weak id <MobFoxInterstitialAdDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 willCacheResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (id)getVideoURLFromDictionary:(id)arg1;
- (void)MFInterstitialCustomEventMobFoxAdFinished;
- (void)MFInterstitialCustomEventMobFoxAdClicked;
- (void)MFInterstitialCustomEventAdClosed;
- (void)MFInterstitialCustomEventAdDidFailToReceiveAdWithError:(id)arg1;
- (void)MFInterstitialCustomEventAdDidLoad:(id)arg1;
- (void)show;
- (void)loadAd;
- (void)loadCustomEvent;
- (void)MobFoxDelegateCustomEvents:(id)arg1 withAdDict:(id)arg2;
- (void)MobFoxAdFinished;
- (void)MobFoxAdClicked;
- (void)MobFoxAdClosed;
- (void)MobFoxAdDidFailToReceiveAdWithError:(id)arg1;
- (void)MobFoxAdDidLoad:(id)arg1;
- (id)init:(id)arg1 withRootViewController:(id)arg2;
- (id)init:(id)arg1;
- (void)appWillResignActive;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

