//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class BJChoiceCouponModel, CCCouponTagView, JDIconLabel, JDImageView, UIImageView, UILabel;

@interface CCCMainCouponView : UIView
{
    UIImageView *_bgImageView;
    UIImageView *_couponSkuBackgroundImageView;
    JDImageView *_couponSkuImageViewBottom;
    JDImageView *_couponSkuImageViewMedium;
    JDImageView *_couponSkuImageViewTop;
    UILabel *_couponFacelValueLabel;
    UILabel *_couponUseConditionLabel;
    JDIconLabel *_couponLimitDescriptionLabel;
    BJChoiceCouponModel *_couponModel;
    JDIconLabel *_receiveTitleLabel;
    CCCouponTagView *_couponTagView;
    UILabel *_couponConditonTagLabel;
}

@property(retain, nonatomic) UILabel *couponConditonTagLabel; // @synthesize couponConditonTagLabel=_couponConditonTagLabel;
@property(retain, nonatomic) CCCouponTagView *couponTagView; // @synthesize couponTagView=_couponTagView;
@property(retain, nonatomic) JDIconLabel *receiveTitleLabel; // @synthesize receiveTitleLabel=_receiveTitleLabel;
@property(retain, nonatomic) BJChoiceCouponModel *couponModel; // @synthesize couponModel=_couponModel;
@property(retain, nonatomic) JDIconLabel *couponLimitDescriptionLabel; // @synthesize couponLimitDescriptionLabel=_couponLimitDescriptionLabel;
@property(retain, nonatomic) UILabel *couponUseConditionLabel; // @synthesize couponUseConditionLabel=_couponUseConditionLabel;
@property(retain, nonatomic) UILabel *couponFacelValueLabel; // @synthesize couponFacelValueLabel=_couponFacelValueLabel;
@property(retain, nonatomic) JDImageView *couponSkuImageViewTop; // @synthesize couponSkuImageViewTop=_couponSkuImageViewTop;
@property(retain, nonatomic) JDImageView *couponSkuImageViewMedium; // @synthesize couponSkuImageViewMedium=_couponSkuImageViewMedium;
@property(retain, nonatomic) JDImageView *couponSkuImageViewBottom; // @synthesize couponSkuImageViewBottom=_couponSkuImageViewBottom;
@property(retain, nonatomic) UIImageView *couponSkuBackgroundImageView; // @synthesize couponSkuBackgroundImageView=_couponSkuBackgroundImageView;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
- (void).cxx_destruct;
- (void)setUseConditionBackgroundNoMoreFlag:(_Bool)arg1;
- (void)updateSearchCouponPattern;
- (void)updateProductImage:(id)arg1;
- (void)translationAnimation;
- (void)setSkuImageViewAnimateWithCouponId:(id)arg1 couponUseConditionColor:(id)arg2 couponConditonTagViewFlag:(unsigned char)arg3;
- (void)setNoSkuImageCoupon;
- (void)setReceivedCouponState:(id)arg1 couponUseConditionColor:(id)arg2;
- (void)changeCouponStateWithColor:(id)arg1 moneySymbolFlag:(_Bool)arg2 couponType:(long long)arg3;
- (void)setCouponOriginalState;
- (void)updateViewWithItem:(id)arg1 BackgroundImage:(id)arg2 viceCouponColor:(id)arg3;
- (void)setupSubView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

