//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OrderTemplateBaseModel.h"

@interface OrderStartFoldUpTempModel : OrderTemplateBaseModel
{
    _Bool _isNeedFold;
}

@property(nonatomic) _Bool isNeedFold; // @synthesize isNeedFold=_isNeedFold;
- (void)dealloc;
- (void)setData;

@end

