//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class KWWenkuFileInfo, NSString;

@protocol KWWenkuSearchViewControllerProtocol <NSObject>
- (void)didSelectItemWithFileInfo:(KWWenkuFileInfo *)arg1 from:(id)arg2;
- (void)cleanHistoryKeywords;
- (void)requestLoadMoreData;
- (void)searchWithKeyword:(NSString *)arg1;
- (void)searchBarShouldResignFirstResponder;
@end

