//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PSYDataScanner.h"

@class NSData;

@interface PSYDataDataScanner : PSYDataScanner
{
    NSData *_scannedData;
    unsigned long long _dataLength;
    unsigned long long _scanLocation;
}

@property(readonly, nonatomic) unsigned long long dataLength; // @synthesize dataLength=_dataLength;
@property(readonly, copy, nonatomic) NSData *data; // @synthesize data=_scannedData;
- (void).cxx_destruct;
- (_Bool)scanNullTerminatedString:(id *)arg1 withEncoding:(unsigned long long)arg2;
- (_Bool)scanUpToData:(id)arg1 intoData:(id *)arg2 options:(int)arg3;
- (_Bool)scanUpToData:(id)arg1 intoData:(id *)arg2;
- (_Bool)scanData:(id)arg1 intoData:(id *)arg2;
- (_Bool)scanData:(id *)arg1 ofLength:(unsigned long long)arg2;
@property(nonatomic) unsigned long long scanLocation; // @synthesize scanLocation=_scanLocation;
- (id)initWithData:(id)arg1;

@end

