//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WPPPenRadioButtonDelegate-Protocol.h"

@class NSString, WPPPenRadioButton;
@protocol WPPPenTypeViewDelegate;

@interface WPPPenTypeView : UIView <WPPPenRadioButtonDelegate>
{
    id <WPPPenTypeViewDelegate> _delegate;
    WPPPenRadioButton *_hardPenHeadRadioButton;
    WPPPenRadioButton *_softPenHeadRadioButton;
}

@property(retain, nonatomic) WPPPenRadioButton *softPenHeadRadioButton; // @synthesize softPenHeadRadioButton=_softPenHeadRadioButton;
@property(retain, nonatomic) WPPPenRadioButton *hardPenHeadRadioButton; // @synthesize hardPenHeadRadioButton=_hardPenHeadRadioButton;
@property(nonatomic) id <WPPPenTypeViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)radioButtonOnTap:(id)arg1;
- (id)initWithPenHeadType:(unsigned long long)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

