//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FBAutoupdaterHost.h"

@class NSString;

@interface FBAutoupdaterReactTranslationHost : FBAutoupdaterHost
{
    _Bool _allowTranslationUpdate;
    NSString *_activeUpdatePath;
    NSString *_appliedTranslationUpdateDirectory;
    NSString *_translationUpdatesDirectory;
}

@property(copy, nonatomic) NSString *translationUpdatesDirectory; // @synthesize translationUpdatesDirectory=_translationUpdatesDirectory;
@property(copy, nonatomic) NSString *appliedTranslationUpdateDirectory; // @synthesize appliedTranslationUpdateDirectory=_appliedTranslationUpdateDirectory;
@property(copy, nonatomic) NSString *activeUpdatePath; // @synthesize activeUpdatePath=_activeUpdatePath;
@property(nonatomic) _Bool allowTranslationUpdate; // @synthesize allowTranslationUpdate=_allowTranslationUpdate;
- (void).cxx_destruct;
- (id)_allAppliedPathsDictionary;
- (id)downloadedTranslationVersion:(id)arg1;
- (id)pathForActiveTranslation:(id)arg1;
- (id)activeUpdateVersion;
- (id)activeUpdate;
- (id)activeLocaleCode;
- (_Bool)activateAppliedTranslation:(id)arg1;
- (_Bool)activateAppliedUpdate;
- (id)updatesDirectory;
- (id)appliedUpdateSymlink;
- (id)allAppliedPaths;

@end

