//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IGFeedItem, IGUserSession, NSDate;
@protocol IGAnalyticsModule, IGFeedItemDirectResponseLoggingProviderDelegate;

@interface IGFeedSectionViewabilitySession : NSObject
{
    IGFeedItem *_feedItem;
    IGUserSession *_userSession;
    unsigned long long _context;
    id <IGAnalyticsModule> _analyticsModuleProvider;
    id <IGFeedItemDirectResponseLoggingProviderDelegate> _loggingProvider;
    NSDate *_viewStartDate;
    double _visiblePercentageThreshold;
    double _percentVisible;
    _Bool _visibilityLoggingFixEnabled;
}

- (void).cxx_destruct;
- (_Bool)shouldStopVisibilityTrackingWithPercentVisible:(double)arg1;
- (_Bool)shouldStopVisibilityTrackingWithPercentVisible_BUG:(double)arg1;
- (void)logAdUnitVisibilityWithReason:(unsigned long long)arg1;
- (void)updatePercentVisible:(double)arg1 withReason:(unsigned long long)arg2;
- (unsigned long long)context;
- (id)initWithFeedItem:(id)arg1 userSession:(id)arg2 context:(unsigned long long)arg3 analyticsModuleProvider:(id)arg4 loggingProvider:(id)arg5 visiblePercentageThreshold:(double)arg6;

@end

