//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAGradientLayer, IGInsetLabel, UIImageView;

@interface IGLiveIndicatorView : UIView
{
    _Bool _hasBorder;
    _Bool _isAnimatingColors;
    _Bool _hasDynamicFont;
    IGInsetLabel *_label;
    CAGradientLayer *_gradientLayer;
    UIImageView *_imageLabel;
    double _fontSize;
}

@property(readonly, nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
@property(readonly, nonatomic) _Bool hasDynamicFont; // @synthesize hasDynamicFont=_hasDynamicFont;
@property(readonly, nonatomic) UIImageView *imageLabel; // @synthesize imageLabel=_imageLabel;
@property(nonatomic) _Bool isAnimatingColors; // @synthesize isAnimatingColors=_isAnimatingColors;
@property(readonly, nonatomic) _Bool hasBorder; // @synthesize hasBorder=_hasBorder;
@property(readonly, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(readonly, nonatomic) IGInsetLabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)sizeToFit;
- (void)resetGradientColors;
- (void)stopAnimatingColors;
- (void)animateColors;
- (void)setCornerRadius:(double)arg1;
- (struct CGSize)sizeForText:(id)arg1;
- (void)configureWithSpec:(id)arg1;
- (void)setText:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

