//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IGReportHelper : NSObject
{
}

+ (void)reportMediaID:(id)arg1 reason:(long long)arg2 sourceName:(id)arg3 networker:(id)arg4 extra:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
+ (void)reportInappropriateSponsoredMediaID:(id)arg1 sourceName:(id)arg2 currentUser:(id)arg3 completionHandler:(CDUnknownBlockType)arg4 dismissHandler:(CDUnknownBlockType)arg5;
+ (void)reportInappropriateMediaID:(id)arg1 sourceName:(id)arg2 currentUser:(id)arg3 usertags:(id)arg4 extra:(id)arg5 completionHandler:(CDUnknownBlockType)arg6 dismissHandler:(CDUnknownBlockType)arg7;

@end

