//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "IGStoryCameraHeaderViewType-Protocol.h"

@class IGCameraInstructionView, IGTapButton;
@protocol IGStoryCameraHeaderViewDelegate;

@interface IGStoryCameraDirectNewHeaderView : UIView <IGStoryCameraHeaderViewType>
{
    IGCameraInstructionView *_instructionView;
    id <IGStoryCameraHeaderViewDelegate> _delegate;
    IGTapButton *_closeButton;
}

@property(readonly, nonatomic) IGTapButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) __weak id <IGStoryCameraHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) IGCameraInstructionView *instructionView; // @synthesize instructionView=_instructionView;
- (void).cxx_destruct;
- (void)closeButtonTapped;
- (void)hideCloseView:(_Bool)arg1;
- (void)hideAllViewsExceptClose:(_Bool)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

