//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDate.h>

@class NSDateComponents, NSString;

@interface NSDate (WT)
+ (id)defaultDateFormatterWithFormatMMddHHmmInChinese;
+ (id)defaultDateFormatterWithFormatYYYYMMddHHmmInChinese;
+ (id)defaultDateFormatterWithFormatHHmm;
+ (id)defaultDateFormatterWithFormatMMddHHmm;
+ (id)defaultDateFormatterWithFormatYYYYMMdd__;
+ (id)defaultDateFormatterWithFormatYYYYMMdd;
+ (id)defaultDateFormatterWithFormatYYYYMMddHHmmss;
+ (id)dateWithYear:(unsigned long long)arg1 Month:(unsigned long long)arg2 Day:(unsigned long long)arg3 Hour:(unsigned long long)arg4 Minute:(unsigned long long)arg5 Second:(unsigned long long)arg6;
+ (id)dateComponents:(unsigned long long)arg1 fromDate:(id)arg2 toDate:(id)arg3;
- (id)MMddHHmmInChinese;
- (id)YYYYMMddHHmmInChinese;
- (id)WT_HHmm;
- (id)MMddHHmm;
- (id)WT_YYYYMMdd__;
- (id)WT_YYYYMMdd;
- (id)WT_YYYYMMddHHmmss;
- (id)whatDayTheWeek;
- (id)whatTimeBefore;
- (id)whatTimeAgo;
- (_Bool)sameMonthWithDate:(id)arg1;
- (_Bool)sameWeekWithDate:(id)arg1;
- (_Bool)sameDayWithDate:(id)arg1;
- (id)sameTimeOfDate;
- (id)oneHourLater;
- (id)workEndTime;
- (id)workBeginTime;
- (unsigned long long)weekOfDayInYear;
- (unsigned long long)weekday;
- (unsigned long long)second;
- (unsigned long long)minute;
- (unsigned long long)hour;
- (unsigned long long)day;
- (unsigned long long)month;
- (unsigned long long)year;
- (id)componentsOfDay;
- (id)ymdDate;
- (_Bool)calWithValue:(long long)arg1;
@property(readonly, nonatomic) NSDateComponents *components;
@property(readonly, nonatomic) double timeStamp;
@property(readonly, copy, nonatomic) NSString *timeStampStr;
- (_Bool)isToday;
- (_Bool)isYesterday;
- (_Bool)isThisYear;
@end

