//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "NSCoding-Protocol.h"

@class UIImageView;
@protocol GJCFAssetsPickerOverlayViewDelegate;

@interface GJCFAssetsPickerOverlayView : UIView <NSCoding>
{
    _Bool _selected;
    _Bool _enableChooseToSeeBigImageAction;
    id <GJCFAssetsPickerOverlayViewDelegate> _delegate;
    UIImageView *_selectIconImgView;
    struct CGRect _frameToShowSelectedWhileBigImageActionEnabled;
}

+ (id)defaultOverlayView;
@property(nonatomic) struct CGRect frameToShowSelectedWhileBigImageActionEnabled; // @synthesize frameToShowSelectedWhileBigImageActionEnabled=_frameToShowSelectedWhileBigImageActionEnabled;
@property(nonatomic) _Bool enableChooseToSeeBigImageAction; // @synthesize enableChooseToSeeBigImageAction=_enableChooseToSeeBigImageAction;
@property(retain, nonatomic) UIImageView *selectIconImgView; // @synthesize selectIconImgView=_selectIconImgView;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic) __weak id <GJCFAssetsPickerOverlayViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didTapOnSelf:(id)arg1;
- (void)switchSelectState;
- (void)switchNormalState;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

