//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GJUIViewController.h"

#import "GJGragToSiblingDelegate-Protocol.h"
#import "RefreshViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class GJFLQuickFilterView, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSTimer, RefreshView, UITableView, UITableViewCell;

@interface GJFLLeisiFangList : GJUIViewController <UITableViewDelegate, UITableViewDataSource, RefreshViewDelegate, GJGragToSiblingDelegate>
{
    GJFLQuickFilterView *_filterView;
    NSDictionary *_filterData;
    NSMutableDictionary *_filterSelectedData;
    _Bool isQuickFiter;
    long long nowListNum;
    _Bool hasMore;
    UITableViewCell *moreListCell;
    long long masterId;
    long long majorId;
    int nowPage;
    _Bool refreshing;
    _Bool loadingNext;
    _Bool isFirstLoading;
    RefreshView *refreshView;
    NSTimer *timer;
    _Bool _showFilter;
    _Bool hasMoreHouse;
    long long totalHouse;
    NSDictionary *filterParamsFromDetail;
    NSMutableArray *_filterDefaultTitles;
    NSMutableArray *_filterKeys;
    long long _scrollToIndexWhenAppaer;
    NSMutableDictionary *_dictInfo;
    NSMutableArray *_listInfo;
    NSMutableArray *_contentArr;
    UITableView *_tableView;
    NSDictionary *_param;
    NSString *_navTitle;
    NSDictionary *_xiaoquInfo;
    long long _currentPage;
    NSString *_domainValue;
    long long _fromEntryType;
}

@property(nonatomic) long long fromEntryType; // @synthesize fromEntryType=_fromEntryType;
@property(retain, nonatomic) NSString *domainValue; // @synthesize domainValue=_domainValue;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(retain, nonatomic) NSDictionary *xiaoquInfo; // @synthesize xiaoquInfo=_xiaoquInfo;
@property(retain, nonatomic) NSString *navTitle; // @synthesize navTitle=_navTitle;
@property(retain, nonatomic) NSDictionary *param; // @synthesize param=_param;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *contentArr; // @synthesize contentArr=_contentArr;
@property(copy, nonatomic) NSDictionary *filterParamsFromDetail; // @synthesize filterParamsFromDetail;
@property(retain, nonatomic) NSMutableArray *listInfo; // @synthesize listInfo=_listInfo;
- (void).cxx_destruct;
- (void)favoritedidClick:(id)arg1;
- (_Bool)hasMoreData;
- (void)loadMorePostLists:(CDUnknownBlockType)arg1;
- (id)postListContent;
- (void)postDetailNewCurrentIndexWhenPopOrDismiss:(unsigned long long)arg1;
- (void)postDetailNewLoadMoreData:(CDUnknownBlockType)arg1;
- (_Bool)postDetailNewHasMoreData;
- (id)domainValueFromList;
- (id)postDetailNewContentArray;
- (void)addErrorTipViewWithErrorMsg:(id)arg1;
- (void)removeLoading;
- (void)addLoadingView;
- (void)removeLoadingDefault;
- (void)addLoadingViewDefault;
- (void)refreshViewDidCallBack;
- (void)refresh;
- (void)startLoading;
- (void)stopLoading;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)addTableView;
- (void)stopFangXinFangShowInfo;
- (void)fangXinFangActivity;
- (void)goBack;
- (void)removeErrorTipView;
- (void)postListRequestSuccess:(id)arg1 withMainClassName:(id)arg2 secondClassName:(id)arg3;
- (void)reloadData:(id)arg1;
- (void)getLeisiFangDataFromNetWork:(id)arg1 finished:(CDUnknownBlockType)arg2;
- (void)qfView:(id)arg1 didSelectSectionForIndex:(long long)arg2 AtIndexPath:(id)arg3 withTblData:(id)arg4;
- (long long)numOfSectionInQFView:(id)arg1 forIndex:(long long)arg2;
- (id)qfView:(id)arg1 forIndex:(long long)arg2 dataForSectionAtSection:(long long)arg3;
- (id)qfView:(id)arg1 titleForIndex:(long long)arg2;
- (long long)numOfSelectSectionInQFView:(id)arg1;
- (id)filterKeyForQfView:(id)arg1;
- (void)initFilterView;
- (void)prepareFilterData:(id)arg1;
- (void)getFilterDataFromNetwork;
- (void)netWork;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithMasterId:(long long)arg1 withMajorId:(long long)arg2 WithTitle:(id)arg3 withXiaoQuInfo:(id)arg4 withDictInfo:(id)arg5;
- (id)initWithMasterId:(long long)arg1 withMajorId:(long long)arg2 WithTitle:(id)arg3 withXiaoQuInfo:(id)arg4 hasFilter:(_Bool)arg5;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

