//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "FBSDKSharingDelegate-Protocol.h"
#import "MBProgressHUDDelegate-Protocol.h"
#import "PWCustomAlertViewDelegate-Protocol.h"
#import "PWExecutionEventDelegate-Protocol.h"
#import "PWRecommendViewDelegate-Protocol.h"
#import "PWUndoManagerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class MBProgressHUD, NSDictionary, NSString, PWExecutionController, PWFactory, PWScrollView, PWUndoManager, UIButton, UIGestureRecognizer, UIImage, UIImageView, UIView;

@interface PWEditingMainController : UIViewController <FBSDKSharingDelegate, PWRecommendViewDelegate, PWUndoManagerDelegate, PWExecutionEventDelegate, UIGestureRecognizerDelegate, MBProgressHUDDelegate, PWCustomAlertViewDelegate>
{
    UIImageView *titleBar;
    UIButton *undoButton;
    UIButton *redoButton;
    UIButton *editFeatureButton;
    UIButton *beautificationFeatureButton;
    UIButton *decorartionFeatureButton;
    UIButton *effectFeatureButton;
    UIButton *frameFeatureButton;
    UIImageView *actionBar;
    PWScrollView *editScrollView;
    PWScrollView *beautificationScrollView;
    PWScrollView *decorationScrollView;
    UIImageView *snapshot;
    PWUndoManager *imageUndoManager;
    int fromType;
    PWExecutionController *executionCtrl;
    _Bool isImageLoaded;
    _Bool needtoSave;
    _Bool thePreviousCtrlStatusBarHidden;
    struct CGRect _mainViewOrginRect;
    double _accumulatesScale;
    double _unitDistance;
    double _minScale;
    double _maxScale;
    UIImageView *_background;
    UIGestureRecognizer *_backRecognizer;
    _Bool _isStickerUsed;
    _Bool _isBubbleUsed;
    _Bool _isMosaicUsed;
    _Bool _isFilterUsed;
    int imageType;
    MBProgressHUD *alertView;
    UIImage *originImage;
    PWFactory *factory;
    UIView *beautyTipView;
    UIView *smartBeautyGuideView;
    UIView *decorateTipView;
    UIButton *hunterForSharingButton;
    UIImage *bluredBackImage;
    NSDictionary *_commonDic;
}

@property(nonatomic) _Bool isFilterUsed; // @synthesize isFilterUsed=_isFilterUsed;
@property(nonatomic) _Bool isMosaicUsed; // @synthesize isMosaicUsed=_isMosaicUsed;
@property(nonatomic) _Bool isBubbleUsed; // @synthesize isBubbleUsed=_isBubbleUsed;
@property(nonatomic) _Bool isStickerUsed; // @synthesize isStickerUsed=_isStickerUsed;
@property(retain, nonatomic) NSDictionary *commonDic; // @synthesize commonDic=_commonDic;
@property(nonatomic) int fromType; // @synthesize fromType;
@property(retain, nonatomic) UIImageView *background; // @synthesize background=_background;
@property(retain, nonatomic) UIGestureRecognizer *backRecognizer; // @synthesize backRecognizer=_backRecognizer;
@property(retain, nonatomic) UIImage *bluredBackImage; // @synthesize bluredBackImage;
@property(retain, nonatomic) UIButton *hunterForSharingButton; // @synthesize hunterForSharingButton;
@property(retain, nonatomic) UIView *decorateTipView; // @synthesize decorateTipView;
@property(retain, nonatomic) UIView *smartBeautyGuideView; // @synthesize smartBeautyGuideView;
@property(retain, nonatomic) UIView *beautyTipView; // @synthesize beautyTipView;
@property(retain, nonatomic) PWFactory *factory; // @synthesize factory;
@property(retain, nonatomic) UIImage *originImage; // @synthesize originImage;
@property int imageType; // @synthesize imageType;
@property(retain, nonatomic) PWUndoManager *imageUndoManager; // @synthesize imageUndoManager;
- (void).cxx_destruct;
- (void)recommendViewRecommendButtonClick:(id)arg1;
- (void)showWaterRecommendView;
- (void)sharerDidCancel:(id)arg1;
- (void)sharer:(id)arg1 didFailWithError:(id)arg2;
- (void)sharer:(id)arg1 didCompleteWithResults:(id)arg2;
- (void)resetMainViewCenter:(_Bool)arg1;
- (void)resetMainView:(_Bool)arg1;
- (double)getDistance:(struct CGPoint)arg1 toPoint:(struct CGPoint)arg2;
- (void)mainViewPinchWithTouches:(id)arg1;
- (void)mainViewPanWithTouches:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
@property(readonly) MBProgressHUD *alertView; // @synthesize alertView;
- (void)hudWasHidden:(id)arg1;
- (void)tapOnBackgroud:(id)arg1;
- (void)executionViewGoOnEditNextImage;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)saveToAlbum;
- (void)executionViewSaveImage:(id)arg1;
- (void)executionViewBackToHome:(_Bool)arg1;
- (void)goOnEditNextImage;
- (void)backAndEditNextImage;
- (void)pwCustomAlertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertMsg:(id)arg1;
- (void)imageTooSmallAlert;
- (void)commitImage:(id)arg1;
- (void)setSnapshot:(id)arg1;
- (void)resetFromUndoManager:(id)arg1;
- (void)redoStatusChange:(_Bool)arg1;
- (void)undoStatusChange:(_Bool)arg1;
- (void)resetButton;
- (void)hideScrollView;
- (void)resetButtonAndHideScrollView;
- (void)frameFeatureAction;
- (void)decorationFeatureBtnClick;
- (void)decorationFeatureAction;
- (void)effectFeatureAction;
- (void)beautificationFeatureBtnClick;
- (void)beautificationFeatureAction;
- (void)editFeatureBtnClick;
- (void)editFeatureAction;
- (void)pushToExecuteView;
- (void)hunterForSharing;
- (void)continuePkSaveFinished;
- (void)redoEditing;
- (void)undoEditing;
- (void)refreshRightItem;
- (void)back;
- (void)clearImageOfImageViewForPOP;
- (id)downsampleImage:(id)arg1;
- (void)initUndoManager:(id)arg1;
- (void)loadImage;
- (void)transferByType;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)initSelfData;
- (void)redPointOnSomeBtn;
- (void)initSelfView;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (id)initWithImage:(id)arg1 andImageType:(int)arg2 editFromType:(int)arg3;
- (id)viewSnapshot;
- (void)clickFrame;
- (void)clickEffect:(id)arg1;
- (void)clickEffect;
- (void)clickScrawl;
- (void)clickBubble;
- (void)clickAccessory;
- (void)clickWhitenTooth;
- (void)clickRedEye;
- (void)clickBraEnlarge;
- (void)clickMakeUp;
- (void)clickPrettyLeg;
- (void)clickPartialHighlightEye;
- (void)clickPartialDarkCircles;
- (void)clickSmooth;
- (void)clickIntelligentBeauty;
- (void)ClickLargerEye;
- (void)clickSmile;
- (void)clickBetterSkin;
- (void)clickSlim;
- (void)clickOneKeyBeauty;
- (void)clickVignette;
- (void)clickSharpen;
- (void)clickWater;
- (void)clickRotation;
- (void)ClickCrop;
- (void)clickTone;
- (void)clickMosaics;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

