//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSThread;
@protocol PWGifOperationDelegate;

@interface PWGifOperation : NSOperation
{
    NSThread *processThread;
    id <PWGifOperationDelegate> delegate;
}

@property(nonatomic) __weak id <PWGifOperationDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSThread *processThread; // @synthesize processThread;
- (void).cxx_destruct;
- (void)main;
- (void)checkContent;
- (id)initWithDelegate:(id)arg1;

@end

