//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UIImageView, UITextView;

@interface PWSocialNoticeGiftViewCtrler : UIViewController
{
    UIImageView *_topBar;
    UITextView *_textView;
    NSString *_contentStr;
}

@property(retain, nonatomic) NSString *contentStr; // @synthesize contentStr=_contentStr;
- (void).cxx_destruct;
- (void)back:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)initContentView;
- (void)initTopView;
- (void)initSelfView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

